In [1]:
from langchain_community.document_loaders import PyMuPDFLoader
from pydantic import BaseModel, Field
from langchain_core.output_parsers import PydanticOutputParser, StrOutputParser, BaseOutputParser
from textwrap import dedent

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage
from langchain_core.prompts import ChatPromptTemplate

from langchain_core.documents import Document
from langchain_chroma import Chroma
from langchain_ollama import OllamaEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter


import httpx
import json
import requests
import pandas as pd
import numpy as np


import warnings
warnings.filterwarnings("ignore", category=SyntaxWarning, message=".*escape sequence.*")
import re



#from langchain_pymupdf4llm import PyMuPDF4LLMLoader, PyMuPDF4LLMParser
#import pymupdf4llm
import requests
import uuid
from openai import OpenAI

import time
import os
from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv(usecwd=True))

pubmed_api_key= '6892c4129cef143ff92d11533848d2e0d908'#os.getenv("PUBMED_API_KEY", '')

use = 'olm'

if use == 'hf':
    os.environ["BASE_URL"] = "https://router.huggingface.co/v1"
    os.environ["MODEL_NAME"] ='Qwen/Qwen3-32B'
    os.environ["OPENAI_API_KEY"] = os.getenv("HUGGINGFACE_HUB_TOKEN2")
    
elif use == 'olm':
    os.environ["BASE_URL"] = "http://localhost:11434/v1"
    os.environ["MODEL_NAME"] ='qwen3:14b'
    os.environ["OPENAI_API_KEY"] = 'hey'
    
else:
    os.environ["BASE_URL"] = "https://gigachat.devices.sberbank.ru/api/v1"
    os.environ["MODEL_NAME"] ='GigaChat-Max'
    
    url = "https://ngw.devices.sberbank.ru:9443/api/v2/oauth"
    # Создадим идентификатор UUID (36 знаков)
    rq_uid = str(uuid.uuid4())
    payload={
      'scope': 'GIGACHAT_API_PERS'
    }
    headers = {
      'Content-Type': 'application/x-www-form-urlencoded',
      'Accept': 'application/json',
      'RqUID': rq_uid,
      'Authorization': f'Basic {os.getenv("GIGACHAT_AUTH")}'
    }

    response = requests.request("POST", url, headers=headers, data=payload, verify=False)
    os.environ["OPENAI_API_KEY"] = response.json()['access_token']
    

os.environ['TEMPERATURE'] = '0'




from trialmind.pubmed import pmid2papers, PubmedAPIWrapper, pmid2biocxml, parse_bioc_xml, pmid2fulltext
from trialmind.api import StudyCharacteristicsExtraction, ScreeningCriteriaGeneration,\
                            LiteratureScreening, ScreeningCriteriaCTGeneration,\
                            CTScreening
from trialmind.retrievers import split_text_into_chunks
import extract
import time
%load_ext autoreload
%autoreload 2

In [2]:
1

1

In [20]:
start = time.time()
print("hello")
end = time.time()
print(end - start)
end=time.time()
j = 0
for i in range(5000):
    j+=1
print(end - start)

hello
0.0
0.0

In [3]:
os.environ["MODEL_NAME"] ='qwen3:14b'

client = OpenAI(
        base_url=os.getenv("BASE_URL"),
        api_key=os.getenv("OPENAI_API_KEY"),
        http_client=httpx.Client(verify=False)
    )

In [6]:
%%time
response = client.chat.completions.create(
        model=os.getenv("MODEL_NAME"),
        messages=[{'role':'user','content':'hey'}],  # Ensure messages is a list
        temperature=0,
    extra_body={"reasoning_effort": "none"}
    )
response#.choices[0]#.message.content

CPU times: total: 15.6 ms
Wall time: 2.51 s

ChatCompletion(id='chatcmpl-900', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='Hey! How can I assist you today? 😊', refusal=None, role='assistant', annotations=None, audio=None, function_call=None, tool_calls=None))], created=1772699276, model='qwen3:14b', object='chat.completion', service_tier=None, system_fingerprint='fp_ollama', usage=CompletionUsage(completion_tokens=12, prompt_tokens=17, total_tokens=29, completion_tokens_details=None, prompt_tokens_details=None))

In [2]:
os.environ["MODEL_NAME"] ='kamekichi128/qwen3-4b-instruct-2507'

In [3]:
%%time
os.environ["MODEL_NAME"] ='kamekichi128/qwen3-4b-instruct-2507'

file_path = "docs/CC_215_L00_DL_fusion_fixed_oncobox_ru.pdf"
fin_condition,treatements_eng,df2 = extract.info_from_doc(file_path)
fin_condition, len(treatements_eng)

CPU times: total: 391 ms
Wall time: 11.6 s

('Colorectal cancer', 75)

In [8]:
treatements_eng[:5]

['Crizotinib', 'Lorlatinib', 'Nectinumab', 'Nimotuzumab', 'Panitumumab']

In [4]:
df2

             treat  score
0      Кризотиниб   19.97
1      Лорлатиниб   19.54
2     Нецитумумаб   15.28
3     Нимотузумаб   15.28
4     Панитумумаб   15.28
..             ...    ...
143     Сорафениб  -27.31
144     Довитиниб  -34.01
145    Нинтеданиб  -52.35
146    Ленватиниб  -74.55
147   Регорафениб  -80.83

[148 rows x 2 columns]

In [7]:
df2[df2.score>=0.01].treat.values

<StringArray>
[           ' Кризотиниб ',            ' Лорлатиниб ',
           ' Нецитумумаб ',           ' Нимотузумаб ',
           ' Панитумумаб ',            ' Цетуксимаб ',
            ' Бригатиниб ',           ' Рамуцирумаб ',
           ' Помалидомид ',             ' Торемифен ',
             ' Деносумаб ',             ' Дувелисиб ',
            ' Инаволисиб ',           ' Бевацизумаб ',
            ' Анастрозол ',              ' Летрозол ',
            ' Тамоксифен ',           ' Фулвестрант ',
            ' Экземестан ',             ' Бусерелин ',
             ' Гистрелин ',             ' Гозерелин ',
             ' Лейпролид ',           ' Трипторелин ',
             ' Лапатиниб ',              ' Афатиниб ',
         ' Акалабрутиниб ',             ' Ибрутиниб ',
             ' Алектиниб ',             ' Церитиниб ',
         ' Могамулизумаб ',    ' Энфортумаб ведотин ',
           ' Леналидомид ',            ' Ганетеспиб ',
          ' Мирветуксимаб',           ' Афлиберцепт ',
 ' Сацитузумаб говитекан ',            ' Гемтузумаб ',
             ' Тецемотид ',             ' Пертузумаб',
            ' Трастузумаб', ' Ибритумомаб тиуксетан ',
          ' Обинутузумаб ',            ' Офатумумаб ',
            ' Ритуксимаб ',          ' Флавопиридол ',
   ' Медроксипрогестерона',             ' Диеногест ',
        ' Левоноргестрел ',             ' Мегестрол ',
            ' Ригосертиб ',            ' Ивозидениб ',
             ' Копанлисиб',              ' Алпелисиб',
             ' Талидомид ',               ' Митотан ',
          ' Гилтеритиниб ',            ' Вориностат ',
  ' Инотузумаб озогамицин',            ' Даратумумаб',
           ' Алемтузумаб ',           ' Воразидениб ',
              ' Сиролимус',           ' Темсиролимус',
             ' Эверолимус',             ' Иделалисиб',
       ' Метилтестостерон',        ' Флюоксиместерон',
            ' Белиностат ',           ' Блинатумомаб',
             ' Бортезомиб',             ' Ромидепсин',
            ' Бендамустин',              ' Кармустин',
               ' Ломустин',            ' Темозоломид',
       ' Гомохаррингтонин']
Length: 77, dtype: str

### client.responses дает 403 ошибку, т.е. structured output не работает

In [43]:
from openai import OpenAI
from pydantic import BaseModel

client = OpenAI(
    base_url=os.getenv("BASE_URL"),
    api_key=os.getenv("OPENAI_API_KEY"),
    http_client=httpx.Client(http2=True, verify=False)
)

class ResearchPaperExtraction(BaseModel):
    title: str
    authors: list[str]
    abstract: str
    keywords: list[str]

response = client.responses.parse(
    model=os.getenv("MODEL_NAME"),
    input=[
        {
            "role": "system",
            "content": "You are an expert at structured data extraction. You will be given unstructured text from a research paper and should convert it into the given structure.",
        },
        {"role": "user", "content": "..."},
    ],
    text_format=ResearchPaperExtraction,
)

research_paper = response.output_parsed

PermissionDeniedError: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>SynGX</center>
</body>
</html>

In [46]:
response = client.responses.create(
    model=os.getenv("MODEL_NAME"),
    input=[{"role": "system", "content": "You are a helpful math tutor. Guide the user through the solution step by step."},
    {"role": "user", "content": "how can I solve 8x + 7 = -23"}],
    text={
    "format": {
        "type": "json_schema",
        "name": "math_response",
        "schema": {
            "type": "object",
            "properties": {
                "steps": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "explanation": {"type": "string"},
                            "output": {"type": "string"}
                        },
                        "required": ["explanation", "output"],
                        "additionalProperties": False
                    }
                },
                "final_answer": {"type": "string"}
            },
            "required": ["steps", "final_answer"],
            "additionalProperties": False
        },
        "strict": False
    }
    }
    )

print(response.output_text)

PermissionDeniedError: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>SynGX</center>
</body>
</html>

In [57]:
response = client.chat.completions.create(
        model=os.getenv("MODEL_NAME"),
        messages=[
            {"role": "system", "content": "You are a helpful assistant designed to output JSON."},
            {"role": "user", "content": "Who won the world series in 2020? Please respond in the format {winner: ...}"}
        ],
        text={"format": {"type": "json_object"}}
    )
print(response.choices[0].message.content)

TypeError: Completions.create() got an unexpected keyword argument 'text'

### response_format: {type: "json_schema",...} -- Error code: 400 - {'status': 400, 'message': 'Empty schema with json format type is not supported'}
Structured Outputs with response_format: {type: "json_schema", ...} is only supported with the gpt-4o-mini, gpt-4o-mini-2024-07-18, and gpt-4o-2024-08-06 model snapshots and later.

In [90]:
class CarType(str, Enum):
    sedan = "sedan"
    suv = "SUV"
    truck = "Truck"
    coupe = "Coupe"

class CarDescription(BaseModel):
    brand: str
    model: str
    car_type: CarType

json_schema = CarDescription.model_json_schema()

completion = client.chat.completions.create(
    model=os.getenv("MODEL_NAME"),
    messages=[
        {
            "role": "user",
            "content": "Generate a JSON with the brand, model and car_type of Ford Explorer (SUV) car from the 90's"
        }
    ],
    response_format={
        "type": "json_schema",
        "json_schema": {
            "name": "car-description",
            "schema": CarDescription.model_json_schema()
        },
    },
)
print(completion.choices[0].message.content)

BadRequestError: Error code: 400 - {'status': 400, 'message': 'Empty schema with json format type is not supported'}

### back

In [43]:
from enum import Enum
class CarType(str, Enum):
    sedan = "sedan"
    suv = "SUV"
    truck = "Truck"
    coupe = "Coupe"

class CarDescription(BaseModel):
    brand: str
    model: str
    car_type: CarType

json_schema = CarDescription.model_json_schema()

completion = client.chat.completions.create(
    model=os.getenv("MODEL_NAME"),
    messages=[
        {
            "role": "user",
            "content": "Generate a JSON with the brand, model and car_type of Mazda cars from the 90's  /no_think"
        }
    ],
    response_format={
        "type": "json_object",
        "json_schema": {
            "name": "car-description",
            "schema": CarDescription.model_json_schema()
        },
    },
    temperature=0,
)
print(completion.choices[0].message.content)

### JSON data for Mazda cars from the 1990s:

```json
[
  {
    "brand": "Mazda",
    "model": "MX-5 Miata",
    "car_type": "Roadster"
  },
  {
    "brand": "Mazda",
    "model": "Protege",
    "car_type": "Compact Sedan"
  },
  {
    "brand": "Mazda",
    "model": "Millenia",
    "car_type": "Full-size Luxury Sedan"
  },
  {
    "brand": "Mazda",
    "model": "B2300",
    "car_type": "Pickup Truck"
  },
  {
    "brand": "Mazda",
    "model": "MPV",
    "car_type": "Minivan"
  },
  {
    "brand": "Mazda",
    "model": "626",
    "car_type": "Mid-size Sedan"
  }
]
```

This JSON contains information about popular Mazda models from the 1990s, including their respective brands, models, and types (sedans, roadsters, minivans, etc.).

In [ ]:
response.msgs[0].parsed

In [36]:
'''
Gigachat --  Error code: 400 - {'status': 400, 'message': 'Empty schema with json format type is not supported'}
works for qwen! 
'''
from enum import Enum
class CarType(str, Enum):
    sedan = "sedan"
    suv = "SUV"
    truck = "Truck"
    coupe = "Coupe"

class CarDescription(BaseModel):
    brand: str
    model: str
    car_type: CarType

json_schema = CarDescription.model_json_schema()

completion = client.chat.completions.parse(
    model=os.getenv("MODEL_NAME"),
    messages=[
        {
            "role": "user",
            "content": "Generate a JSON with the brand, model and car_type of Mazda cars from the 90's  /no_think"
        }
    ],
    response_format=CarDescription,
    temperature=0,
)
print(completion.choices[0].message.content)

BadRequestError: Error code: 400 - {'status': 400, 'message': 'Empty schema with json format type is not supported'}

In [37]:
json_schema

{'$defs': {'CarType': {'enum': ['sedan', 'SUV', 'Truck', 'Coupe'],
   'title': 'CarType',
   'type': 'string'}},
 'properties': {'brand': {'title': 'Brand', 'type': 'string'},
  'model': {'title': 'Model', 'type': 'string'},
  'car_type': {'$ref': '#/$defs/CarType'}},
 'required': ['brand', 'model', 'car_type'],
 'title': 'CarDescription',
 'type': 'object'}

In [40]:
from enum import Enum
class CarType(str, Enum):
    sedan = "sedan"
    suv = "SUV"
    truck = "Truck"
    coupe = "Coupe"

class CarDescription(BaseModel):
    brand: str
    model: str
    car_type: CarType

json_schema = CarDescription.model_json_schema()

completion = client.chat.completions.create(
    model=os.getenv("MODEL_NAME"),
    messages=[
        {
            "role": "user",
            "content": "Generate a JSON with the brand, model and car_type of Mazda cars from the 90's"+\
        f" and follow the JSON format defined by the following JSON schema: {json_schema} /no_think"
        }
    ],
    #tools=[json_schema],
    temperature=0,
)
print(completion.choices[0].message.content)

### JSON data for Mazda cars from the 1990s

```json
[
  {
    "brand": "Mazda",
    "model": "626",
    "car_type": "sedan"
  },
  {
    "brand": "Mazda",
    "model": "MX-5",
    "car_type": "Coupe"
  },
  {
    "brand": "Mazda",
    "model": "Bongo",
    "car_type": "Van"
  },
  {
    "brand": "Mazda",
    "model": "MPV",
    "car_type": "Minivan"
  },
  {
    "brand": "Mazda",
    "model": "Navajo",
    "car_type": "Pickup Truck"
  },
  {
    "brand": "Mazda",
    "model": "Protege",
    "car_type": "Hatchback"
  },
  {
    "brand": "Mazda",
    "model": "Millenia",
    "car_type": "Sedan"
  },
  {
    "brand": "Mazda",
    "model": "Tribute",
    "car_type": "SUV"
  }
]
```

### Explanation:
- The `'$defs'` section defines the allowed values for the `car_type`.
- Each entry in the array represents a different Mazda car from the 1990s.
- The required fields (`brand`, `model`, and `car_type`) are specified as per the given JSON schema.
- The `'$ref'` is used to reference the predefined `CarType` enum within the schema.

In [39]:
'''
qwen doesnt support "structured_outputs" in body
'''
class CarType(str, Enum):
    sedan = "sedan"
    suv = "SUV"
    truck = "Truck"
    coupe = "Coupe"

class CarDescription(BaseModel):
    brand: str
    model: str
    car_type: CarType

json_schema = CarDescription.model_json_schema()

completion = client.chat.completions.create(
    model=os.getenv("MODEL_NAME"),
    messages=[
        {
            "role": "user",
            "content": "Generate a JSON with the brand, model and car_type of Mazda cars from the 90's"
        }
    ],
    extra_body={"structured_outputs": {"json": json_schema}}
)
print(completion.choices[0].message.content)

### Example JSON structure for Mazda cars from the 1990s:

```json
[
  {
    "brand": "Mazda",
    "model": "MX-5 Miata",
    "car_type": "Convertible"
  },
  {
    "brand": "Mazda",
    "model": "626",
    "car_type": "Sedan/SUV"
  },
  {
    "brand": "Mazda",
    "model": "Capella",
    "car_type": "Compact Car"
  },
  {
    "brand": "Mazda",
    "model": "Bongo Freestyle",
    "car_type": "Minivan/MPV"
  },
  {
    "brand": "Mazda",
    "model": "Millenia",
    "car_type": "Mid-size Luxury Sedan"
  },
  {
    "brand": "Mazda",
    "model": "Protégé",
    "car_type": "Compact Car"
  }
]
```

#### Explanation:
- The `brand` field contains the manufacturer name (`Mazda`).
- The `model` field specifies the individual car models that were popular in the 1990s.
- The `car_type` indicates the type (sedan, convertible, minivan, etc.) to provide more context about each vehicle.

You can modify or extend this list based on specific Mazda models you want to include from the 1990s.

In [42]:
'''
qwen doesnt support "structured_outputs" in body
'''
class CarType(str, Enum):
    sedan = "sedan"
    suv = "SUV"
    truck = "Truck"
    coupe = "Coupe"

class CarDescription(BaseModel):
    brand: str
    model: str
    car_type: CarType

json_schema = CarDescription.model_json_schema()

completion = client.chat.completions.create(
    model=os.getenv("MODEL_NAME"),
    messages=[
        {
            "role": "user",
            "content": "Generate a JSON with the brand, model and car_type of Mazda cars from the 90's"
        }
    ],
    tools = [json_schema]
)
print(completion.choices[0].message.content)

### JSON format for Mazda Cars from the 1990s

```json
[
  {
    "brand": "Mazda",
    "model": "MX-5 (Miata)",
    "car_type": "Convertible sports car"
  },
  {
    "brand": "Mazda",
    "model": "Protégé",
    "car_type": "Compact sedan/coupe"
  },
  {
    "brand": "Mazda",
    "model": "B-series pickup truck",
    "car_type": "Pickup truck"
  },
  {
    "brand": "Mazda",
    "model": "Millenia",
    "car_type": "Full-size luxury sedan"
  },
  {
    "brand": "Mazda",
    "model": "MPV",
    "car_type": "Minivan"
  },
  {
    "brand": "Mazda",
    "model": "Navajo",
    "car_type": "Sport utility vehicle (SUV)"
  }
]
```

This JSON contains information about popular Mazda models from the 1990s, including their brand, model name, and car type.

## 1. clinical trials

In [3]:
file_path = "docs/CC_215_L00_DL_fusion_fixed_oncobox_ru.pdf"
fin_condition, treatements_eng = extract.info_from_doc(file_path)
fin_condition, treatements_eng

('Colorectal cancer',
 ['Crizotinib',
  'Lorlatinib',
  'Necitumumab',
  'Nimotuzumab',
  'Panitumumab',
  'Cetuximab',
  'Brigatinib',
  'Ramucirumab',
  'Pomalidomide',
  'Tamoxifen',
  'Denosumab',
  'Duvelisib',
  'Inavilisib',
  'Bevacizumab',
  'Anastrozole',
  'Exemestane'])

1. загрузить док
2. взять 1-ую страницу; рег.выражениями взять диагноз
-- с ЛЛМ перевести на англ.
3. найти страницу с таблицей; или взять таблицы с PyMuPDFLoader
4. извлечь таблицу

In [157]:
all_studies = extract.get_clinicaltrials(f'''"{fin_condition}"''', 
                                      #' OR '.join(treatements_eng), 
                                       treatements_eng[0],  
                                      max_studies=100)
all_studies

,hasResults,nctId,briefTitle,overallStatus,briefSummary,conditions,studyType,phases,interventions,outcomeMeasures
0,True,NCT02510001,MEK and MET Inhibition in Colorectal Cancer,COMPLETED,This trial is designed to try two new cancer d...,"[Solid Tumor, Colorectal Cancer]",INTERVENTIONAL,[PHASE1],"[pf-02341066, pd-0325901, binimetinib]","[{'type': 'PRIMARY', 'title': 'Maximal Tolerat..."

In [13]:
# test the apis

api = ScreeningCriteriaCTGeneration()
ecs = api.run(
    population = f"Patients with {fin_condition} undergoing treatment with {treatements_eng[0]}",
    intervention = f"{treatements_eng[0]}",
    comparator = "",
    outcome = "",
    llm = os.getenv("MODEL_NAME"),
    num_title_criteria=2,
    num_abstract_criteria=2,
    thinking=False,
)
ecs

call_openai https://gigachat.devices.sberbank.ru/api/v1
api_call_single https://gigachat.devices.sberbank.ru/api/v1/
```json
{
    "ELIGIBILITY_ANALYSIS": [
        "Patients must have colorectal cancer confirmed by histopathology or imaging studies",
        "Treatment with crizotinib must be administered as part of standard therapy or experimental protocol",
        "Comparative intervention must involve another drug or placebo",
        "Outcomes must measure efficacy, safety, or survival endpoints relevant to colorectal cancer treatment",
        "Study design must be randomized controlled trial (RCT), cohort study, or case-control study"
    ],
    "TITLE_CRITERIA": [
        "Does the title mention 'colorectal cancer'?",
        "Does the title mention 'crizotinib'?"
    ],
    "CONTENT_CRITERIA": [
        "Is there evidence of randomization or control group in the abstract?",
        "Are outcomes related to tumor response, progression-free survival, overall survival, or adverse events mentioned in the abstract?"
    ]
}
```

{'title_criteria': ["Does the title mention 'colorectal cancer'?",
  "Does the title mention 'crizotinib'?"],
 'content_criteria': ['Is there evidence of randomization or control group in the abstract?',
  'Are outcomes related to tumor response, progression-free survival, overall survival, or adverse events mentioned in the abstract?'],
 'eligibility_analysis': ['Patients must have colorectal cancer confirmed by histopathology or imaging studies',
  'Treatment with crizotinib must be administered as part of standard therapy or experimental protocol',
  'Comparative intervention must involve another drug or placebo',
  'Outcomes must measure efficacy, safety, or survival endpoints relevant to colorectal cancer treatment',
  'Study design must be randomized controlled trial (RCT), cohort study, or case-control study']}

### __check

In [7]:
from trialmind.api import parse_json_outputs

In [29]:
parse_json_outputs(['''```json
{
    "ELIGIBILITY_ANALYSIS": [
        "Patients must have colorectal cancer confirmed by histopathology or imaging studies",
        "Treatment with crizotinib as part of standard therapy or experimental protocol",
        "Comparative intervention against placebo or other treatments",
        "Clearly reported outcomes related to efficacy or safety endpoints",
        "Published in peer-reviewed journals"
    ],
    "TITLE_CRITERIA": [
        "Does the title mention 'colorectal cancer'?",
        "Does the title mention 'crizotinib'?"
    ],
    "CONTENT_CRITERIA": [
        "Is there a description of patient population including diagnosis and stage of disease?",
        "Are details provided about the intervention and comparison groups?"
]
} ```
'''])

[{}]

In [15]:
json_pattern = r"\`\`\`json([\s\S]*?)\`\`\`"
if re.search(r"\`\`\`json([\s\S]*?)", '''```json
{{
    "ELIGIBILITY_ANALYSIS": [
        "Patients must have colorectal cancer confirmed by histopathology or imaging studies",
        "Treatment with crizotinib as part of standard therapy or experimental protocol",
        "Comparative intervention against placebo or other treatments",
        "Clearly reported outcomes related to efficacy or safety endpoints",
        "Published in peer-reviewed journals"
    ],
    "TITLE_CRITERIA": [
        "Does the title mention 'colorectal cancer'?",
        "Does the title mention 'crizotinib'?"
    ],
    "CONTENT_CRITERIA": [
        "Is there a description of patient population including diagnosis and stage of disease?",
        "Are details provided about the intervention and comparison groups?"
]'''):
    print(1)

In [128]:
from typing import Literal
class ScreeningResult(str, Enum):
    evaluations: Literal['YES', 'NO', 'UNCERTAIN'] = Field(description=f"Evaluation for a criteria")
    rationale: str = Field(description="A rationale for a criteria evaluation")

class ScreeningResults(BaseModel):
    one_result: ScreeningResult

json_schema = ScreeningResults.model_json_schema()
json_schema

{'$defs': {'ScreeningResult': {'enum': ["annotation=NoneType required=True description='Evaluation for a criteria'",
    "annotation=NoneType required=True description='A rationale for a criteria evaluation'"],
   'title': 'ScreeningResult',
   'type': 'string'}},
 'properties': {'one_result': {'$ref': '#/$defs/ScreeningResult'}},
 'required': ['one_result'],
 'title': 'ScreeningResults',
 'type': 'object'}

### 2. CT screen

In [158]:
all_text = all_studies.briefTitle.fillna("") + ": " + all_studies.briefSummary.fillna("")
all_text.values.tolist()[:1]

["MEK and MET Inhibition in Colorectal Cancer: This trial is designed to try two new cancer drugs together for the first time. The investigators think that they might be effective in some types of bowel cancer. The first part of the trial will see what doses of the two drugs can safely be given together. Once the investigators have identified a suitable dose combination they will look at how effective treatment is in bowel cancers where either the RAS gene is mutated, or MET is over-active. In the trial the investigators will look at samples of blood, skin and tumour to check the drugs are working in the way expected. The trial will take place in three sites in the UK and 5 sites in Europe. The trial is funded as part of the European commission's FP7 program."]

In [160]:
treatement = treatements_eng[0]
api = CTScreening()
ec_pred = api.run(
    population = f"Patients with {fin_condition} undergoing treatment with {treatement}",
    intervention = f"{treatement}",
    comparator = "",
    outcome = "",
    llm = os.getenv("MODEL_NAME"),
    criteria = [f"Does the trial focus on patients with '{fin_condition}'?",
                 f"Does the trial examine the use or sensitivity of '{treatement}' among main treatments?"
               ],
    papers = all_text.values.tolist(), # make for the top-100 for demo
)
ec_pred

1
False

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'UNCERTAIN'], rationale=["The trial explicitly mentions 'bowel cancer', which is synonymous with 'Colorectal cancer'.", "The trial mentions 'Crizotinib' in the context of being one of two new drugs tested together, but it does not clearly state whether Crizotinib is the main treatment or whether its use or sensitivity is being examined."])]

[PaperEvaluation(evaluations=['YES', 'UNCERTAIN'], rationale=["The trial explicitly mentions 'bowel cancer', which is synonymous with 'Colorectal cancer'.", "The trial mentions 'Crizotinib' in the context of being one of two new drugs tested together, but it does not clearly state whether Crizotinib is the main treatment or whether its use or sensitivity is being examined."])]

In [180]:
ctrials_fin = extract.ctrials_res(ec_pred, all_studies)

In [181]:
ctrials_fin

[ClinicalResult(population=30, time_frame='Dose Expansion phase: change from baseline and up to 12 months.', outcomes=[Outcome(category_name='Stable Disease', outcome=7), Outcome(category_name='Progressive Disease', outcome=22), Outcome(category_name='Early death from malignant disease', outcome=1)])]

In [154]:
os.getenv("MODEL_NAME")

'qwen3:14b'

In [23]:
evals = [i['evaluations'] for i in ec_pred]

word2int = {"YES": 1, 
            "UNCERTAIN": 0,
            "NO": -1
           }
#rev_subs = { v:k for k, v in word2int.items()} # subs.iteritems() In Python 3
new_evals = []
for one_e in evals:
    new_evals.append([word2int.get(item, 0) for item in one_e ])
new_evals = np.array(new_evals)    
print(new_evals)
print(new_evals.sum(axis=1))
all_studies['screen_eval'] = new_evals.sum(axis=1)
all_studies

[[ 1  1  0  1]
 [-1 -1  0 -1]
 [ 1 -1  0  1]
 [-1  1  0  0]
 [-1 -1  0 -1]
 [ 1  1  0  1]
 [-1  1  0  0]]
[ 3 -3  1  0 -3  3  0]

,hasResults,nctId,briefTitle,overallStatus,briefSummary,conditions,studyType,phases,interventions,outcomeMeasures,screen_eval
0,False,NCT03792568,ALK Inhibitor in Metastatic Colorectal Cancer ...,UNKNOWN,This clinical trial aims to evaluate the effic...,[Colorectal Cancer],INTERVENTIONAL,[NA],[],NaN,3
1,False,NCT02568267,Basket Study of Entrectinib (RXDX-101) for the...,ACTIVE_NOT_RECRUITING,"This is an open-label, multicenter, global Pha...","[Breast Cancer, Cholangiocarcinoma, Colorectal...",INTERVENTIONAL,[PHASE2],[entrectinib],NaN,-3
2,True,NCT02510001,MEK and MET Inhibition in Colorectal Cancer,COMPLETED,This trial is designed to try two new cancer d...,"[Solid Tumor, Colorectal Cancer]",INTERVENTIONAL,[PHASE1],"[pf-02341066, pd-0325901, binimetinib]","[{'type': 'PRIMARY', 'title': 'Maximal Tolerat...",1
3,False,NCT03947385,Study of IDE196 in Patients With Solid Tumors ...,RECRUITING,"This is a Phase 1/2, multi-center, open-label ...","[Metastatic Uveal Melanoma, Cutaneous Melanoma...",INTERVENTIONAL,"[PHASE1, PHASE2]","[ide196, binimetinib, crizotinib]",NaN,0
4,False,NCT06214793,Taletrectinib in Previously Treated Metastatic...,SUSPENDED,The purpose of this study is to evaluate the s...,"[Breast Cancer, Metastatic Breast Cancer]",INTERVENTIONAL,[PHASE2],[taletrectinib],NaN,-3
5,False,NCT05725200,Study to Investigate Outcome of Individualized...,RECRUITING,The purpose of the study is to investigate the...,[Metastatic Colorectal Cancer],INTERVENTIONAL,[PHASE2],"[alectinib, cetuximab, crizotinib, dasatinib, ...",NaN,3
6,False,NCT02465060,Targeted Therapy Directed by Genetic Testing i...,ACTIVE_NOT_RECRUITING,This phase II MATCH screening and multi-sub-tr...,"[Advanced Lymphoma, Advanced Malignant Solid N...",INTERVENTIONAL,[PHASE2],"[adavosertib, afatinib, afatinib dimaleate, bi...",NaN,0

In [24]:
all_studies[all_studies.screen_eval>=0]

,hasResults,nctId,briefTitle,overallStatus,briefSummary,conditions,studyType,phases,interventions,outcomeMeasures,screen_eval
0,False,NCT03792568,ALK Inhibitor in Metastatic Colorectal Cancer ...,UNKNOWN,This clinical trial aims to evaluate the effic...,[Colorectal Cancer],INTERVENTIONAL,[NA],[],NaN,3
2,True,NCT02510001,MEK and MET Inhibition in Colorectal Cancer,COMPLETED,This trial is designed to try two new cancer d...,"[Solid Tumor, Colorectal Cancer]",INTERVENTIONAL,[PHASE1],"[pf-02341066, pd-0325901, binimetinib]","[{'type': 'PRIMARY', 'title': 'Maximal Tolerat...",1
3,False,NCT03947385,Study of IDE196 in Patients With Solid Tumors ...,RECRUITING,"This is a Phase 1/2, multi-center, open-label ...","[Metastatic Uveal Melanoma, Cutaneous Melanoma...",INTERVENTIONAL,"[PHASE1, PHASE2]","[ide196, binimetinib, crizotinib]",NaN,0
5,False,NCT05725200,Study to Investigate Outcome of Individualized...,RECRUITING,The purpose of the study is to investigate the...,[Metastatic Colorectal Cancer],INTERVENTIONAL,[PHASE2],"[alectinib, cetuximab, crizotinib, dasatinib, ...",NaN,3
6,False,NCT02465060,Targeted Therapy Directed by Genetic Testing i...,ACTIVE_NOT_RECRUITING,This phase II MATCH screening and multi-sub-tr...,"[Advanced Lymphoma, Advanced Malignant Solid N...",INTERVENTIONAL,[PHASE2],"[adavosertib, afatinib, afatinib dimaleate, bi...",NaN,0

### 3. CT outcome results
Взяли все результаты, отдельно сохранили испытания с результатами, и з них отбираем рез-ты только с unit==participants

filter by interventional study type?

In [306]:
from trialmind.llm import batch_call_llm

In [307]:
openai_client = OpenAI(
    base_url=os.getenv("BASE_URL"),
    api_key=os.getenv("OPENAI_API_KEY"),
    http_client=httpx.Client(verify=False)
)

In [308]:
os.getenv("BASE_URL")

'https://gigachat.devices.sberbank.ru/api/v1'

In [309]:
chosen

,hasResults,nctId,briefTitle,overallStatus,briefSummary,conditions,studyType,phases,interventions,outcomeMeasures,screen_eval,screening,res_with_part
2,True,NCT02510001,MEK and MET Inhibition in Colorectal Cancer,COMPLETED,This trial is designed to try two new cancer d...,"[Solid Tumor, Colorectal Cancer]",INTERVENTIONAL,[PHASE1],"[pf-02341066, pd-0325901, binimetinib]","[{'type': 'PRIMARY', 'title': 'Maximal Tolerat...",1,"{'evaluations': ['YES', 'NO', 'UNCERTAIN', 'YE...","[{'type': 'PRIMARY', 'title': 'Clinical Respon..."

In [314]:
messages[0]

[{'role': 'system',
  'content': 'You are a helpful medical assistant. Answer with a concise description of the efficiency statistics for EACH of 1 provided outcome measures /no_think'},
 {'role': 'user',
  'content': "[{'type': 'PRIMARY', 'title': 'Clinical Response to Binimetinib Combined With PF-02341066', 'description': 'To investigate response to treatment with RPII dose of Binimetinib with Crizotinib (PF-02341066), in patients with a) RASMT CRC or b) RASWT/cMET mut amplified CRC or c) RASWT/c-MET over-expressed CRC, as defined by stable, partially or completely responding disease, per Response Evaluation Criteria In Solid Tumors Criteria (RECIST v1.1) for target lesions and assessed by CT: Complete Response (CR), Disappearance of all target lesions; Partial Response (PR), \\\\>=30% decrease in the sum of the longest diameter of target lesions; Stable Disease (SD), Neither sufficient shrinkage to qualify for PR nor sufficient increase (\\\\>=20%) to qualify for Progressive Disease; Overall Response (OR) = CR + PR + SD', 'populationDescription': 'Evaluable patients for the primary outcome are those patients who complete a response assessment after cycle 1 of treatment, or who progress early on treatment. 30 of the 36 recruited patients had a response assessment after cycle 1 or progressed early on treatment, and hence these 30 patients are evaluable for the primary analysis.', 'reportingStatus': 'POSTED', 'paramType': 'COUNT_OF_PARTICIPANTS', 'unitOfMeasure': 'Participants', 'timeFrame': 'Dose Expansion phase: change from baseline and up to 12 months.', 'groups': [{'id': 'OG000', 'title': 'Dose Expansion Phase', 'description': 'Binimetinib 30mg BD interval dose administration Days 1-21 every 28 days PF-02341066 (Crizotinib) 250mg OD Days 1-28 continuously Dosage determined following the recommended Phase II dose identification in the dose escalation phase.\\n\\nPF-02341066: PF-02341066 (Crizotinib) 250mg OD or 200mg BD or 250mg BD Days 1-28 continuously\\n\\nBinimetinib: Binimetinib 30mg or 45 mg BD either continuously or Days 1-21 every 28 days'}], 'denoms': [{'units': 'Participants', 'counts': [{'groupId': 'OG000', 'value': '30'}]}], 'classes': [{'categories': [{'title': 'Stable Disease', 'measurements': [{'groupId': 'OG000', 'value': '7'}]}, {'title': 'Progressive Disease', 'measurements': [{'groupId': 'OG000', 'value': '22'}]}, {'title': 'Early death from malignant disease', 'measurements': [{'groupId': 'OG000', 'value': '1'}]}]}]}]"}]

In [523]:
PROMPT_RES_EXTRACTION  = '''
You are a clinical specialist analyzing clinical trial study reports. 
Your task is to to extract specific information as structured data.

# Reply Format: 
Return the information in the following JSON-format.
```json
{{        
    [
        {{
            "population": n,
            "time_frame": "time_frame",
            "outcomes":
                [
                    {{
                        "category_name": "category1",
                        "outcome": k1
                    }},
                    {{
                        "category_name": "category2",
                        "outcome": k2
                    }},
                    ...
                ]
         }},
        ...
    ]
}}
```
You MUST return ONLY valid JSON, Do NOT include any explanations, comments, or extra text.
"""
'''

In [150]:
extract.ctrials_res(ec_pred, all_studies)

NameError: name 'ec_pred' is not defined

In [520]:
class Outcome(BaseModel):
    category_name: str = Field(description='Short description of a category')
    outcome: int = Field(description='Percent of participants')

class ClinicalResult(BaseModel):
    population: int = Field(description='Total number of participants.')
    time_frame: str = Field(description='Time frame')
    outcomes: list[Outcome]

In [521]:
ClinicalResult.model_json_schema()

{'$defs': {'Outcome': {'properties': {'category_name': {'description': 'Short description of a category',
     'title': 'Category Name',
     'type': 'string'},
    'outcome': {'description': 'Percent of participants',
     'title': 'Outcome',
     'type': 'integer'}},
   'required': ['category_name', 'outcome'],
   'title': 'Outcome',
   'type': 'object'}},
 'properties': {'population': {'description': 'Total number of participants.',
   'title': 'Population',
   'type': 'integer'},
  'time_frame': {'description': 'Time frame',
   'title': 'Time Frame',
   'type': 'string'},
  'outcomes': {'items': {'$ref': '#/$defs/Outcome'},
   'title': 'Outcomes',
   'type': 'array'}},
 'required': ['population', 'time_frame', 'outcomes'],
 'title': 'ClinicalResult',
 'type': 'object'}

In [488]:
- **Population**: Evaluable patients (N=30)
- **Time Frame**: Dose expansion phase - Change from baseline up to 12 months.
- **Results**:
  * Stable Disease: 7 participants
  * Progressive Disease: 22 participants
  * Early Death From Malignant Disease: 1 participa

SyntaxError: invalid syntax (1536186896.py, line 1)

In [524]:
at_once = False
openai_client = OpenAI(
    base_url=os.getenv("BASE_URL"),
    api_key=os.getenv("OPENAI_API_KEY"),
    http_client=httpx.Client(verify=False)
)

chosen = all_studies[(all_studies.screen_eval>=0)&(all_studies.hasResults==True)]
chosen['res_with_part'] = chosen['outcomeMeasures'].apply(lambda x: [obj for obj in x \
                                                          if(obj.get('unitOfMeasure','').lower() in ['percentage of participants','participants'])])

to_work = chosen[chosen.res_with_part.str.len()>0]
if to_work.shape[0]:
    messages = []
    for i in to_work.res_with_part.values:
        n_outcomes = len(i)
        messages.append([{'role':'system', 'content':PROMPT_RES_EXTRACTION+' \no_think'},
                {'role':'user', 'content':f"{i}"}])
    if at_once:
        results = batch_call_openai(messages, os.getenv('MODEL_NAME'), 
                                    int(os.getenv('TEMPERATURE')), thinking=False)
    else:
        resultsct = []
        for i in messages:
            #$answer = extract.use_llm(os.getenv('MODEL_NAME'),i)
            
            response = openai_client.chat.completions.create(
                model=os.getenv('MODEL_NAME'),
                messages=messages[0],
                temperature=0,
                response_format={
                    "type": "json_object",
                    "json_schema": {
                        "name": "schema",
                        "schema": ClinicalResult.model_json_schema()
                    },
                },
            )
            fin = response.choices[0].message.content
            answer = fin.strip('<think>\n\n</think>\n\n')
            resultsct.append(answer)
    for i in resultsct:
        print(i)
        print('-----')

C:\Users\user\AppData\Local\Temp\ipykernel_4268\2758598942.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chosen['res_with_part'] = chosen['outcomeMeasures'].apply(lambda x: [obj for obj in x \

```json
[
    {
        "population": 30,
        "time_frame": "Dose Expansion phase: change from baseline and up to 12 months.",
        "outcomes": [
            {
                "category_name": "Stable Disease",
                "outcome": 7
            },
            {
                "category_name": "Progressive Disease",
                "outcome": 22
            },
            {
                "category_name": "Early death from malignant disease",
                "outcome": 1
            }
        ]
    }
]
```
-----

In [526]:
from trialmind.api import parse_json_outputs
parse_json_outputs(resultsct)

[[{'population': 30,
   'time_frame': 'Dose Expansion phase: change from baseline and up to 12 months.',
   'outcomes': [{'category_name': 'Stable Disease', 'outcome': 7},
    {'category_name': 'Progressive Disease', 'outcome': 22},
    {'category_name': 'Early death from malignant disease', 'outcome': 1}]}]]

In [336]:
to_work.res_with_part.values[0][0]['title']

'Clinical Response to Binimetinib Combined With PF-02341066'

In [330]:
to_work.res_with_part.values[0]

[{'type': 'PRIMARY',
  'title': 'Clinical Response to Binimetinib Combined With PF-02341066',
  'description': 'To investigate response to treatment with RPII dose of Binimetinib with Crizotinib (PF-02341066), in patients with a) RASMT CRC or b) RASWT/cMET mut amplified CRC or c) RASWT/c-MET over-expressed CRC, as defined by stable, partially or completely responding disease, per Response Evaluation Criteria In Solid Tumors Criteria (RECIST v1.1) for target lesions and assessed by CT: Complete Response (CR), Disappearance of all target lesions; Partial Response (PR), \\>=30% decrease in the sum of the longest diameter of target lesions; Stable Disease (SD), Neither sufficient shrinkage to qualify for PR nor sufficient increase (\\>=20%) to qualify for Progressive Disease; Overall Response (OR) = CR + PR + SD',
  'populationDescription': 'Evaluable patients for the primary outcome are those patients who complete a response assessment after cycle 1 of treatment, or who progress early on treatment. 30 of the 36 recruited patients had a response assessment after cycle 1 or progressed early on treatment, and hence these 30 patients are evaluable for the primary analysis.',
  'reportingStatus': 'POSTED',
  'paramType': 'COUNT_OF_PARTICIPANTS',
  'unitOfMeasure': 'Participants',
  'timeFrame': 'Dose Expansion phase: change from baseline and up to 12 months.',
  'groups': [{'id': 'OG000',
    'title': 'Dose Expansion Phase',
    'description': 'Binimetinib 30mg BD interval dose administration Days 1-21 every 28 days PF-02341066 (Crizotinib) 250mg OD Days 1-28 continuously Dosage determined following the recommended Phase II dose identification in the dose escalation phase.\n\nPF-02341066: PF-02341066 (Crizotinib) 250mg OD or 200mg BD or 250mg BD Days 1-28 continuously\n\nBinimetinib: Binimetinib 30mg or 45 mg BD either continuously or Days 1-21 every 28 days'}],
  'denoms': [{'units': 'Participants',
    'counts': [{'groupId': 'OG000', 'value': '30'}]}],
  'classes': [{'categories': [{'title': 'Stable Disease',
      'measurements': [{'groupId': 'OG000', 'value': '7'}]},
     {'title': 'Progressive Disease',
      'measurements': [{'groupId': 'OG000', 'value': '22'}]},
     {'title': 'Early death from malignant disease',
      'measurements': [{'groupId': 'OG000', 'value': '1'}]}]}]}]

In [556]:
to_work#.res_with_part#.values

,hasResults,nctId,briefTitle,overallStatus,briefSummary,conditions,studyType,phases,interventions,outcomeMeasures,screen_eval,screening,res_with_part
2,True,NCT02510001,MEK and MET Inhibition in Colorectal Cancer,COMPLETED,This trial is designed to try two new cancer d...,"[Solid Tumor, Colorectal Cancer]",INTERVENTIONAL,[PHASE1],"[pf-02341066, pd-0325901, binimetinib]","[{'type': 'PRIMARY', 'title': 'Maximal Tolerat...",1,"{'evaluations': ['YES', 'NO', 'UNCERTAIN', 'YE...","[{'type': 'PRIMARY', 'title': 'Clinical Respon..."

In [339]:
'30' in str(to_work.res_with_part.values[0])

True

In [318]:
resultsct

['For the PRIMARY outcome measure "Clinical Response to Binimetinib Combined With PF-02341066":\n\n- **Population**: Evaluable patients (N=30)\n- **Time Frame**: Dose expansion phase - Change from baseline up to 12 months.\n- **Results**:\n  * Stable Disease: 7 participants\n  * Progressive Disease: 22 participants\n  * Early Death From Malignant Disease: 1 participa']

In [ ]:
at_once = False
openai_client = OpenAI(
    base_url=os.getenv("BASE_URL"),
    api_key=os.getenv("OPENAI_API_KEY"),
    http_client=httpx.Client(verify=False)
)

chosen = all_studies[(all_studies.screen_eval>=0)&(all_studies.hasResults==True)]
chosen['res_with_part'] = chosen['outcomeMeasures'].apply(lambda x: [obj for obj in x \
                                                          if(obj.get('unitOfMeasure','').lower() in ['percentage of participants','participants'])])

to_work = chosen[chosen.res_with_part.str.len()>0]
if to_work.shape[0]:
    messages = []
    for i in to_work.res_with_part.values[:2]:
        n_outcomes = len(i)
        print(n_outcomes)
        messages.append([{'role':'system', 'content':f'You are a helpful medical assistant. Answer with a concise description of the efficiency statistics for EACH of {n_outcomes} provided outcome measures /no_think'},
                {'role':'user', 'content':f"{i}"}])
    if at_once:
        results = batch_call_openai(messages, os.getenv('MODEL_NAME'), 
                                    int(os.getenv('TEMPERATURE')), thinking=False)
    else:
        resultsct = []
        for i in messages:
            #$answer = extract.use_llm(os.getenv('MODEL_NAME'),i)
            
            response = openai_client.chat.completions.create(
                model=os.getenv('MODEL_NAME'),
                messages=messages[0],
                temperature=0
            )
            fin = response.choices[0].message.content
            answer = fin.strip('<think>\n\n</think>\n\n')
            resultsct.append(answer)
    for i in resultsct:
        print(i)
        print('-----')

### results in a given format?

In [ ]:

class Info(BaseModel):
    diagnose: str = Field(..., description="База клинических испытаний")
    treatments: str = Field(..., description="Высшие позиции рейтинга таргетных препаратов")

parser = PydanticOutputParser(pydantic_object=Info)

In [ ]:
prompt = ChatPromptTemplate.from_messages([
    (
        "system", 
        dedent(
            """
            You are a helpful assistant. 
            Your goal is to extract related information from the text provided by the user.
            Return the information in the following JSON-format.
            {fmt}
            """
        )
    ),
    (
        "human", 
        dedent(
            """
            Text: {text}"
            """
        )
    ),
])
chain = (
    prompt 
    | llm_reasoning 
    | parser
)


response = await chain.ainvoke({"text": text, "fmt": parser.get_format_instructions()})
print(response)

## 4. papers

In [3]:
#fin_condition = 'Colorectal cancer'
#treatements_eng =  ['Crizotinib','Lorlatinib',]

In [183]:
search_api = PubmedAPIWrapper()
# page_size is the max number of records to return!!!! not pages!
tmp_inputs = {
        "page_size": 15,
        "keyword_map": {'conditions':[fin_condition], 
                        'treatments':[treatements_eng[0]]
                       },
        "keywords": {
            "OPERATOR": 'AND'
        }
}

time.sleep(.5)
response = search_api.build_search_query_and_get_pmid(tmp_inputs, 
                                                      api_key=pubmed_api_key)
len(response[0]), response[1]

(15,
 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=(Colorectal cancer)+AND+(Crizotinib)&retmax=15&retmode=json&api_key=6892c4129cef143ff92d11533848d2e0d908')

In [9]:
pmid_list=['38378070', '40369167', '37686423', '37543570', '37418240',
       '38212428', '38711893', '36801912', '36627781', '40211189',
       '40140597', '37773318', '41268440', '41213063', '40526090']
pmid_list = ['40369167',
 '37543570',
 '37418240',
 '38212428',
 '38711893',
 '40211189',
 '40140597',
 '37773318',
 '41213063']

In [10]:
df_papers = pmid2papers(pmid_list=pmid_list,
                        #pmid_list=response[0], 
                        api_key=pubmed_api_key)
df_papers[0].head(4)

,PMID,Journal,Year,Month,Day,Title,Publication Type,Authors,Abstract
0,40369167,Cell death and differentiation,2025,Nov,,ARID1A loss enhances sensitivity to c-MET inhi...,Journal Article,"Xu Zhang, Zihuan Wang, Yilin He, Kejin Wang, C...","ARID1A, a subunit of the SWI/SNF chromatin-rem..."
1,37543570,Journal of translational medicine,2023,Aug,05,Epithelial cell adhesion molecule (EpCAM) regu...,"Journal Article, Research Support, Non-U.S. Gov't","Chi-Chiu Lee, Chia-Jui Yu, Sushree Shankar Pan...",Epithelial cell adhesion molecule (EpCAM) is k...
2,37418240,ACS applied materials & interfaces,2023,Jul,19,Albumin-Based Cyanine Crizotinib Conjugate Nan...,Journal Article,"Zhuang Hu, Ruihan Li, Xinyue Cui, Zilin Chen",Colorectal cancer (CRC) is presently the third...
3,38212428,Cellular and molecular life sciences : CMLS,2024,Jan,12,Inhibition of autocrine HGF maturation overcom...,Journal Article,"Vivian Truong Jones, Ramona Graves-Deal, Zheng...",Although amplifications and mutations in recep...

In [11]:
df_papers[0].Abstract.str.len()

0    1772
1    1915
2    1523
3    1310
4     357
5    2420
6    1416
7    1536
8    1505
Name: Abstract, dtype: int64

In [12]:
papers = df_papers[0]["Title"] + ": " + df_papers[0]["Abstract"].fillna("") # important to fillna
papers = papers.tolist()
papers[0][:400]

'ARID1A loss enhances sensitivity to c-MET inhibition by dual targeting of GPX4 and iron homeostasis, inducing ferroptosis.: ARID1A, a subunit of the SWI/SNF chromatin-remodeling complex, functions as a tumor suppressor in various cancer types. Owing to its high frequency of inactivating mutations, ARID1A has emerged as a promising target for the development of anticancer drugs. In this study, we r'

### 5. paper screen

In [10]:
len(papers)

15

In [11]:
df_papers[0].PMID.values

<StringArray>
['38378070', '40369167', '37686423', '37543570', '37418240', '38212428',
 '38711893', '36801912', '36627781', '40211189', '40140597', '37773318',
 '41268440', '41213063', '40526090']
Length: 15, dtype: str

In [73]:
os.environ["MODEL_NAME"] ='qwen3.5:9b'

In [74]:
%%time
api = LiteratureScreening()
ec_predP = api.run(
    population = f"Patients with {fin_condition} undergoing treatment with {treatements_eng[0]}",
    intervention = f"{treatements_eng[0]}",
    comparator = "",
    outcome = "",
    
    llm = os.getenv("MODEL_NAME"),
     criteria = [f"Does the study focus on patients with '{fin_condition}'?",
                 f"Does the study examine the use or sensitivity of '{treatements_eng[0]}' among main treatments?", 
                f"Does the study describe the effect of '{treatements_eng[0]}' treatment?"],#title_criteria + content_criteria,
    papers = papers, # make for the top-100 for demo
)
ec_predP

1
False

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=['The study explicitly investigates ARID1A-deficient colorectal cancer (CRC) cells and xenograft tumor models, satisfying the criterion of focusing on patients/populations with Colorectal cancer.', "The text states that 'crizotinib' is one of the FDA-approved drugs used to selectively inhibit the growth of ARID1A-deficient CRC cells in vitro and in xenograft models, confirming the examination of Crizotinib use/sensitivity.", 'The study describes the mechanism by which Crizotinib (c-MET inhibition) induces synthetic lethality and ferroptosis in ARID1A-deficient CRC cells, detailing the effects on GPX4 expression, lipid peroxidation, and cell death.'])]
False

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=['The study explicitly investigates colorectal cancer (CRC) cell lines and metastatic/orthotopic animal models of colon cancer, satisfying the population criterion.', 'The study validates a combined therapy involving an HGFR inhibitor (crizotinib), thereby examining its use as part of the main treatment strategy.', 'The study describes the effect of crizotinib in combination with an anti-EpCAM antibody, noting that this combined treatment significantly inhibits tumor progression and prolongs survival.'])]
False

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=['The abstract explicitly states that the study addresses Colorectal cancer (CRC) and utilizes Crizotinib as a targeted inhibitor for c-Met positive tumor cells in this context.', 'The study examines the use of Crizotinib, specifically formulated into nanoparticles with an imaging agent, to target CRC tumors, satisfying the criterion regarding the examination of its use among treatments.', "The abstract describes the 'synergistic chemophototherapy effects' achieved under laser irradiation using the Crizotinib-based nanoparticles, thereby describing the effect of the treatment."])]
False

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=['The study title and abstract explicitly state that the research focuses on colorectal cancer (CRC) cell lines and discusses cetuximab resistance in this specific population.', "The text mentions that HGF-induced cetuximab resistance could be overcome by the downstream MET inhibitor, crizotinib, indicating the examination of Crizotinib's sensitivity/effectiveness as a treatment strategy.", 'The study describes the effect of Crizotinib in overcoming acquired and de novo cetuximab resistance in colorectal cancer cells, directly addressing the outcome of its treatment.'])]
False
False

RetryError: RetryError[<Future at 0x1ba1d8b6560 state=finished raised APIConnectionError>]

In [75]:
evalsP = [i.evaluations for i in ec_predP]

word2int = {"YES": 1, 
            "UNCERTAIN": 0,
            "NO": -1
           }
#rev_subs = { v:k for k, v in word2int.items()} # subs.iteritems() In Python 3
new_evalsP = []
for one_e in evalsP:
    new_evalsP.append([word2int.get(item, 0) for item in one_e ])
new_evalsP = np.array(new_evalsP)  
df_p_e = df_papers[0]
df_p_e[['s1','s2','s3']] = new_evalsP
chosen_df = df_p_e[(df_p_e['s1']==1)&(df_p_e['s2']==1)&(df_p_e['s3']>=0)]
'''
print(new_evalsP.sum(axis=1))
df_papers[0]['screen_eval'] = -5

#.iloc[:5].copy()
df_p_e['screen_eval'] = new_evalsP.sum(axis=1)
'''
print(chosen_df.shape[0])
chosen_df.head(3)

NameError: name 'ec_predP' is not defined

### RAG db for papers

In [13]:
chosen_df = df_papers[0].copy()

In [14]:
from langchain_core.documents import Document
from langchain_chroma import Chroma
from langchain_ollama import OllamaEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter

In [15]:
pmid_list = chosen_df.PMID.values.tolist()
#['41213063',#'26451310',]

res = pmid2fulltext(pmid_list, api_key=pubmed_api_key)
#print(res)
res = [parse_bioc_xml(r) for r in res]
# transform the parsed xml into paper content
papers0 = []
for parsed in res:
    paper_content = []
    for parsed_ in parsed["passage"]:
        paper_content.append(parsed_['content'])
    paper_content = "\n".join(paper_content)
    papers0.append(paper_content)

chosen_df['FullText'] = ''
chosen_df['FullText'] = papers0

In [16]:
pmid_list = chosen_df.PMID.values.tolist()
papers_ch = chosen_df.FullText.values
#papers_ch_ta = chosen_df.Title.values +': ' + chosen_df.Abstract.values
docs =  [Document(page_content=i, 
                  metadata={"source": j}
                 ) for i,j in zip(papers_ch,pmid_list)]
print(papers_ch.shape)
docs[0].page_content[:400]

(9,)

'ARID1A loss enhances sensitivity to c-MET inhibition by dual targeting of GPX4 and iron homeostasis, inducing ferroptosis\nARID1A, a subunit of the SWI/SNF chromatin-remodeling complex, functions as a tumor suppressor in various cancer types. Owing to its high frequency of inactivating mutations, ARID1A has emerged as a promising target for the development of anticancer drugs. In this study, we rep'

In [19]:
vector_store._client.delete_collection(vector_store._collection.name)

In [20]:
embeddings = OllamaEmbeddings(model="qwen3-embedding")

vector_store = Chroma(
    collection_name="example_collection",
    embedding_function=embeddings,
    collection_metadata={"hnsw:space": "cosine"},
    #persist_directory="./chroma_langchain_db",  # Where to save data locally, remove if not necessary
)

text_splitter=RecursiveCharacterTextSplitter(chunk_size=400, 
                                             chunk_overlap=100)

In [31]:
doc1 = '''
A phase Ia study of the MEK1/2 inhibitor PD-0325901 with the c-MET inhibitor crizotinib in patients with advanced solid cancers 

Abstract

Background: Single-agent MEK1/2 inhibition has been disappointing in clinical trials targeting RAS mutant (MT) cancers, probably due to upstream receptor activation, resulting in resistance. We previously found that dual c-MET/MEK1/2 inhibition attenuated RASMT colorectal cancer (CRC) xenograft growth. In this study, we assessed safety of MEK1/2 inhibitor PD-0325901 with c-MET inhibitor crizotinib and determined the optimal biological doses for subsequent clinical trials.

Methods: In this dose-escalation phase I trial, patients with advanced solid tumours received PD-0325901 with crizotinib, using a rolling-6 design to determine the maximum tolerable dose (MTD) and safety/tolerability. Blood samples for pharmacokinetics and skin biopsies were collected.

Results: Twenty-five patients were recruited in 4 cohorts up to doses of crizotinib 200 mg B.D continuously with PD-0325901 8 mg B.D, days 1-21 every 28 days. One in six patients exhibited a dose-limiting toxicity at this dose level. Drug-related adverse events were in keeping with single-agent toxicity profiles. The best clinical response was stable disease in seven patients (29%).

Conclusions: PD-0325901/crizotinib can be given together at pharmacologically-active doses. The MTD for PD-0325901/crizotinib was 8 mg B.D (days 1-21) and 200 mg B.D continuously in a 28-days cycle. The combination was further explored with an alternate MEK1/2 inhibitor in RASMT CRC patients.

Eudract-number: 2014-000463-40.

'''
doc1_D = Document(page_content=doc1, 
                  metadata={"source": "40140597"}
                 )

In [21]:
all_splits = text_splitter.split_documents(docs)
document_ids = vector_store.add_documents(documents=all_splits)

In [22]:
pmid_list

['40369167',
 '37543570',
 '37418240',
 '38212428',
 '38711893',
 '40211189',
 '40140597',
 '37773318',
 '41213063']

In [23]:
vector_store.similarity_search_with_score(f"treating {fin_condition} with {treatements_eng[0]}",
                               k=8,
                               filter={"source": "40140597"}
)

[(Document(id='218a52eb-652d-4e4d-8ab8-826a20bb8a44', metadata={'source': '40140597'}, page_content='selected population of patients with advanced CRC was not pursued due to the termination of the clinical development of PD-0325901. Moving forward, a phase Ia/b trial evaluating the combination of crizotinib with an alternative MEK1/2 inhibitor binimetinib in RAS mutant CRC patients with aberrant c-MET was completed.'),
  0.33809322118759155),
 (Document(id='cd0f972f-5ca1-4bb2-8afa-53ab2d9e7339', metadata={'source': '40140597'}, page_content='that MET could represent a valuable therapeutic target when combined with MEK1/2 inhibitors in patients with KRASMT mCRC, and selected the combination of crizotinib and the MEK1/2 inhibitor PD-0325901 for clinical investigation.'),
  0.3405834436416626),
 (Document(id='e05c5dad-382e-4d08-bde9-9a36265cc91f', metadata={'source': '40140597'}, page_content='A phase Ia study of the MEK1/2 inhibitor PD-0325901 with the c-MET inhibitor crizotinib in patients with advanced solid cancers\nBackground'),
  0.3429509997367859),
 (Document(id='f3bb3142-16b1-4a39-9bcc-7923f7447e8c', metadata={'source': '40140597'}, page_content='In summary, inhibition of the MEK1/2 and c-MET kinases using PD-0325901 and crizotinib, was well tolerated with a manageable toxicity profile, but with limited activity in unselected heavily pre-treated patients with advanced solid tumours. Further exploration of this combination in a biomarker selected population of patients with advanced CRC was not pursued due to the termination of the'),
  0.35381436347961426),
 (Document(id='9087de1e-aabf-4cfd-83ba-afbac0213638', metadata={'source': '40140597'}, page_content='Single-agent MEK1/2 inhibition has been disappointing in clinical trials targeting RAS mutant (MT) cancers, probably due to upstream receptor activation, resulting in resistance. We previously found that dual c-MET/MEK1/2 inhibition attenuated RASMT colorectal cancer (CRC) xenograft growth. In this study, we assessed safety of MEK1/2 inhibitor PD-0325901 with c-MET inhibitor crizotinib and'),
  0.35454219579696655),
 (Document(id='393e9629-6378-4a16-9ea5-999175c991db', metadata={'source': '40140597'}, page_content='CRC in vitro and in vivo. Additionally, pharmacological blockade of this resistance pathway using the cMET inhibitor crizotinib (formerly PF-02341066) increased MEK1/2-inhibitor-induced apoptosis and growth inhibition in vitro and in vivo in KRASMT CRC models. Based on this and other studies, we reasoned that MET could represent a valuable therapeutic target when combined with MEK1/2 inhibitors'),
  0.3696799874305725),
 (Document(id='31c47c14-e620-4456-be65-da1b4a7438b2', metadata={'source': '40140597'}, page_content='Targeting oncogenic drivers has improved outcomes for several human malignancies. Compared with lung or breast cancers, fewer clinically-actionable oncogenic alterations have been identified in colorectal cancer (CRC). Monoclonal antibodies against the epidermal growth factor receptor (EGFR), such as cetuximab and panitumumab, together with standard chemotherapies form the mainstay of tumour'),
  0.3710639476776123),
 (Document(id='dd498f06-227c-4d57-8599-3073786465aa', metadata={'source': '40140597'}, page_content='due to the late occurrence of retinal vein occlusion (RVO). The second drug, crizotinib, is an oral ATP-competitive small-molecule inhibitor of c-MET, ALK and ROS1. Crizotinib is approved for the first-line treatment of patients with metastatic lung cancer whose tumours are either ALK or ROS1 positive, and the recommended oral dose is 250â\x80\x89mg B.D.'),
  0.3716633915901184)]

In [84]:
vector_store.similarity_search_with_score(f"treating {fin_condition} with {treatements_eng[0]}",
                               k=8,
                               filter={"source": "40140597"}
)

[(Document(id='7030effa-6916-4740-b172-4ea70b6d5996', metadata={'source': '40140597'}, page_content='selected population of patients with advanced CRC was not pursued due to the termination of the clinical development of PD-0325901. Moving forward, a phase Ia/b trial evaluating the combination of crizotinib with an alternative MEK1/2 inhibitor binimetinib in RAS mutant CRC patients with aberrant c-MET was completed.'),
  0.3373193144798279),
 (Document(id='5af92adc-743c-4434-be73-9548ab6373b1', metadata={'source': '40140597'}, page_content='that MET could represent a valuable therapeutic target when combined with MEK1/2 inhibitors in patients with KRASMT mCRC, and selected the combination of crizotinib and the MEK1/2 inhibitor PD-0325901 for clinical investigation.'),
  0.33801013231277466),
 (Document(id='5a15dc49-3e6a-4439-96fe-894e3be4c767', metadata={'source': '40140597'}, page_content='A phase Ia study of the MEK1/2 inhibitor PD-0325901 with the c-MET inhibitor crizotinib in patients with advanced solid cancers\nBackground'),
  0.34783393144607544),
 (Document(id='0e874b53-7e27-42a3-98bd-e9c3546469d0', metadata={'source': '40140597'}, page_content='Single-agent MEK1/2 inhibition has been disappointing in clinical trials targeting RAS mutant (MT) cancers, probably due to upstream receptor activation, resulting in resistance. We previously found that dual c-MET/MEK1/2 inhibition attenuated RASMT colorectal cancer (CRC) xenograft growth. In this study, we assessed safety of MEK1/2 inhibitor PD-0325901 with c-MET inhibitor crizotinib and'),
  0.35187792778015137),
 (Document(id='fc92abdc-702f-487a-8a3c-64e73dba0b17', metadata={'source': '40140597'}, page_content='In summary, inhibition of the MEK1/2 and c-MET kinases using PD-0325901 and crizotinib, was well tolerated with a manageable toxicity profile, but with limited activity in unselected heavily pre-treated patients with advanced solid tumours. Further exploration of this combination in a biomarker selected population of patients with advanced CRC was not pursued due to the termination of the'),
  0.3560218811035156),
 (Document(id='f1886117-e8b9-4bc8-b0a3-24083b7abc7f', metadata={'source': '40140597'}, page_content='due to the late occurrence of retinal vein occlusion (RVO). The second drug, crizotinib, is an oral ATP-competitive small-molecule inhibitor of c-MET, ALK and ROS1. Crizotinib is approved for the first-line treatment of patients with metastatic lung cancer whose tumours are either ALK or ROS1 positive, and the recommended oral dose is 250â\x80\x89mg B.D.'),
  0.3689587116241455),
 (Document(id='c894539a-e984-4402-a3e6-dde7ea4c2827', metadata={'source': '40140597'}, page_content='Targeting oncogenic drivers has improved outcomes for several human malignancies. Compared with lung or breast cancers, fewer clinically-actionable oncogenic alterations have been identified in colorectal cancer (CRC). Monoclonal antibodies against the epidermal growth factor receptor (EGFR), such as cetuximab and panitumumab, together with standard chemotherapies form the mainstay of tumour'),
  0.36937493085861206),
 (Document(id='7863e84d-95df-4d64-81f1-d03739fc5205', metadata={'source': '40140597'}, page_content='data would indicate that co-administration of crizotinib with PD-0325901 appears to reduce the plasma concentration of PD-0325901 and its metabolite on Cycle 1 Day 21 compared to Day -1, especially at the highest 8â\x80\x89mg B.D dose.'),
  0.37030911445617676)]

In [56]:
all_splits[4].page_content

'Results: Twenty-five patients were recruited in 4 cohorts up to doses of crizotinib 200 mg B.D continuously with PD-0325901 8 mg B.D, days 1-21 every 28 days. One in six patients exhibited a dose-limiting toxicity at this dose level. Drug-related adverse events were in keeping with single-agent toxicity profiles. The best clinical response was stable disease in seven patients (29%).'

In [57]:
p1 = '''
DOCUMENT_CONTEXT_PROMPT = """
<document>
{doc_content}
</document>
"""

CHUNK_CONTEXT_PROMPT = """
Here is the chunk we want to situate within the whole document
<chunk>
{chunk_content}
</chunk>

Please give a short succinct context to situate this chunk within the overall document for the purposes of improving search retrieval of the chunk.
Answer only with the succinct context and nothing else.
"""
'''
print(
    p1.format(doc_content=doc1, chunk_content=all_splits[4].page_content)
)

DOCUMENT_CONTEXT_PROMPT = """
<document>

A phase Ia study of the MEK1/2 inhibitor PD-0325901 with the c-MET inhibitor crizotinib in patients with advanced solid cancers

Abstract

Background: Single-agent MEK1/2 inhibition has been disappointing in clinical trials targeting RAS mutant (MT) cancers, probably due to upstream receptor activation, resulting in resistance. We previously found that dual c-MET/MEK1/2 inhibition attenuated RASMT colorectal cancer (CRC) xenograft growth. In this study, we assessed safety of MEK1/2 inhibitor PD-0325901 with c-MET inhibitor crizotinib and determined the optimal biological doses for subsequent clinical trials.

Methods: In this dose-escalation phase I trial, patients with advanced solid tumours received PD-0325901 with crizotinib, using a rolling-6 design to determine the maximum tolerable dose (MTD) and safety/tolerability. Blood samples for pharmacokinetics and skin biopsies were collected.

Results: Twenty-five patients were recruited in 4 cohorts up to doses of crizotinib 200 mg B.D continuously with PD-0325901 8 mg B.D, days 1-21 every 28 days. One in six patients exhibited a dose-limiting toxicity at this dose level. Drug-related adverse events were in keeping with single-agent toxicity profiles. The best clinical response was stable disease in seven patients (29%).

Conclusions: PD-0325901/crizotinib can be given together at pharmacologically-active doses. The MTD for PD-0325901/crizotinib was 8 mg B.D (days 1-21) and 200 mg B.D continuously in a 28-days cycle. The combination was further explored with an alternate MEK1/2 inhibitor in RASMT CRC patients.

Eudract-number: 2014-000463-40.


</document>
"""

CHUNK_CONTEXT_PROMPT = """
Here is the chunk we want to situate within the whole document
<chunk>
Results: Twenty-five patients were recruited in 4 cohorts up to doses of crizotinib 200 mg B.D continuously with PD-0325901 8 mg B.D, days 1-21 every 28 days. One in six patients exhibited a dose-limiting toxicity at this dose level. Drug-related adverse events were in keeping with single-agent toxicity profiles. The best clinical response was stable disease in seven patients (29%).
</chunk>

Please give a short succinct context to situate this chunk within the overall document for the purposes of improving search retrieval of the chunk.
Answer only with the succinct context and nothing else.
"""

In [65]:
os.environ["MODEL_NAME"] ='qwen3.5:9b'

In [67]:
%%time
response = client.chat.completions.create(
        model=os.getenv("MODEL_NAME"),
        messages=[{'role':'user',
                   'content':p1.format(doc_content=doc1, 
                                       chunk_content=all_splits[4].page_content)
                                       }],  # Ensure messages is a list
        temperature=0,
    extra_body={"reasoning_effort": "none"}
    )
response.choices[0].message.content

CPU times: total: 125 ms
Wall time: 4min 28s

'This chunk presents the Results section of the Phase Ia study, detailing patient recruitment, dosing regimens, toxicity profiles, and clinical response outcomes for the PD-0325901/crizotinib combination therapy.'

In [63]:
response.choices[0].message.content+all_splits[4].page_content

'Phase Ia trial evaluating PD-0325901 (MEK1/2 inhibitor) and crizotinib (c-MET inhibitor) in 25 patients with advanced solid tumours, assessing safety, MTD, and clinical response at specified doses.Results: Twenty-five patients were recruited in 4 cohorts up to doses of crizotinib 200 mg B.D continuously with PD-0325901 8 mg B.D, days 1-21 every 28 days. One in six patients exhibited a dose-limiting toxicity at this dose level. Drug-related adverse events were in keeping with single-agent toxicity profiles. The best clinical response was stable disease in seven patients (29%).'

In [24]:
vector_store.max_marginal_relevance_search(f"treating {fin_condition} with {treatements_eng[0]}",
                                          k=5,lambda_mult = 1,
                                           filter={"source": "40140597"}
                                          )

InvalidArgumentError: Collection expecting embedding with dimension of 384, got 4096

### 6. papers results extraction
Только для статей с оценкой выше 0 !! Чтобы не загружать полный текст у всех

+ надо посмотреть: если фул текст недоступен, то загружается ли абстракт

In [23]:
chosen_df.shape

(9, 9)

In [25]:
chosen_df.FullText.str.len()#.sum()

0    46819
1    53833
2     1637
3    48168
4    16750
5    37077
6    26580
7    50595
8     1652
Name: FullText, dtype: int64

### __check

In [ ]:
{
     "fieldresult": [
       {
         "name": "Title",
         "value": "Основы программирования на Python",
         "source_id": [104]
       },
       {
         "name": "Pages",
         "value": "300 страниц",
         "source_id": [105]
       }
     ]
   }

In [ ]:

        Format:
        ```json
        [
            {{
                "name":  \\ str, length <= 25 tokens
                "value":  \\ str, length <= 25 tokens
                "source_id":  \\ list[int], length <= 3 ids
            }},
            {{
                "name":, \\ str, length <= 25 tokens
                "value":  \\ str, length <= 25 tokens
                "source_id":  \\ list[int], length <= 3 ids
            }},
            ...
        ]
        ```
    \"\"\"
```
    
    
new
```json
        [
            {{
                "name": "fieldName1",
                "value": "extractedInfo1",
                "source_id":[source1, source2, ...]
            }},
            {{
                "name":["fieldName2"],
                "value":["extractedInfo2"],
                "source_id":[source1, source2, ...]
            }},
            ...
        ]
```

In [26]:
from pydantic import BaseModel, validator, Field, conlist  # This is the new version
from typing import Dict, Literal
class FieldResult(BaseModel):
    name: str = Field(description='Field name that accurately represents the content of the field based on its description.',
                     max_length=25)
    value: str = Field(description='Extracted information from the text based on the field description.',
                      max_length=50)
    source_id: conlist(int,min_length=1, max_length=3) = Field(description='Cited document IDs.')
    
class Results(BaseModel):
    fieldresult: FieldResult
    
Results.model_json_schema()

{'$defs': {'FieldResult': {'properties': {'name': {'description': 'Field name that accurately represents the content of the field based on its description.',
     'maxLength': 25,
     'title': 'Name',
     'type': 'string'},
    'value': {'description': 'Extracted information from the text based on the field description.',
     'maxLength': 50,
     'title': 'Value',
     'type': 'string'},
    'source_id': {'description': 'Cited document IDs.',
     'items': {'type': 'integer'},
     'maxItems': 3,
     'minItems': 1,
     'title': 'Source Id',
     'type': 'array'}},
   'required': ['name', 'value', 'source_id'],
   'title': 'FieldResult',
   'type': 'object'}},
 'properties': {'fieldresult': {'$ref': '#/$defs/FieldResult'}},
 'required': ['fieldresult'],
 'title': 'Results',
 'type': 'object'}

In [69]:
from pydantic import BaseModel, validator, Field, conlist,   # This is the new version
from typing import Dict, Literal
import pydantic
import random
class Nested(pydantic.BaseModel):
    a: str = pydantic.Field(examples=["hello"])


class ExampleData(pydantic.BaseModel):
    a: int = pydantic.Field(examples=[1])
    b: str = pydantic.Field(min_length=10, max_length=10, examples=["abc-123-45"])
    c: int = pydantic.Field(default=100)
    # Note: Example will be populated by child, so no explicit example needs
    # to be provided for nested models
    n: Nested
    
nn = 1    
class FieldResult(BaseModel):
    name: str = Field(description='Field name that accurately represents the content of the field based on its description.',
                     max_length=25, default='effectiveness')
    value: str = Field(description='Extracted information from the text based on the field description.',
                      max_length=50, default='total of 5% died')
    #source_id: conlist(int,min_length=1, max_length=3) = Field(description='Cited document IDs.', examples=[1,3])
    
class Results(BaseModel):
    fieldresult: list[FieldResult]

    
def populate_with_examples_recursive(model: pydantic.BaseModel) -> dict:
    """Populate fields with example values"""

    result = {}
    
    for name, field_info in model.model_fields.items():
        if issubclass(field_info.annotation, pydantic.BaseModel):
            result[name] = populate_with_examples_recursive(field_info.annotation)
        elif field_info.examples:
            result[name] = random.choice(field_info.examples)
        elif field_info.default:
            result[name] = field_info.default

    return dict(result)


# Execute it:
#json.loads(f'''{populate_with_examples_recursive(ExampleData)}''')

(populate_with_examples_recursive(Results))

SyntaxError: trailing comma not allowed without surrounding parentheses (1178800490.py, line 1)

In [83]:
class FieldResult(BaseModel):
    name: str = Field(description='Field name that accurately represents the content of the field based on its description.',
                     max_length=25, default='effectiveness')
    value: str = Field(description='Extracted information from the text based on the field description.',
                      max_length=50, default='total of 5% died')
    source_id: list[int] = Field(description='Cited document IDs.', examples=[1,3])
    #conlist ,min_length=1, max_length=3
class Results(BaseModel):
    fieldresult: list[FieldResult]

a1 = FieldResult()
a = Results(fieldresult=[a1,a1])

print(a.model_dump_json(indent=4))

ValidationError: 1 validation error for FieldResult
source_id
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/missing

In [27]:
papers[:2]

['Partial response to crizotinib + regorafenib + PD-1 inhibitor in a metastatic: Colorectal cancer (CRC) with the Raf murine sarcoma viral oncogene homolog B (\nA 49-year-old Chinese male was diagnosed with ascending colon adenocarcinoma (cT3N+?M1) with liver metastases. The patient performed next-generation sequencing (NGS) using tissue and circulating tumor DNA (ctDNA), and the results showed a\nThis study reported a co-existence of a',
 'ARID1A loss enhances sensitivity to c-MET inhibition by dual targeting of GPX4 and iron homeostasis, inducing ferroptosis.: ARID1A, a subunit of the SWI/SNF chromatin-remodeling complex, functions as a tumor suppressor in various cancer types. Owing to its high frequency of inactivating mutations, ARID1A has emerged as a promising target for the development of anticancer drugs. In this study, we report that ARID1A-deficient colorectal cancer (CRC) cells induce synthetic lethality when treated with inhibitors of c-MET receptor tyrosine kinase. c-MET specific inhibitor PHA-665752 as well as two other FDA-approved drugs, crizotinib and cabozantinib, selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models. Mechanistically, we identified a tripartite functional association among ARID1A, c-MET, and NRF2, where ARID1A and c-MET pathways converge on the NRF2 transcription factor, which regulates the transcription of GPX4, a key regulator of ferroptosis. ARID1A inactivation reduces c-MET expression, decreasing NRF2 nuclear localization and its binding to the GPX4 promoter, resulting in reduced GPX4 transcription. This creates a cellular dependency on the residual c-MET for minimal GPX4 expression to survive the ferroptotic cell death. Additionally, we demonstrate that ARID1A loss leads to increased intracellular labile iron accumulation by downregulating the iron-exporting protein SLC40A1, thereby increasing cellular susceptibility to ferroptosis. Inhibition of c-MET in ARID1A-deficient CRC cells diminishes GPX4 expression, resulting in elevated lipid peroxidation and glutathione depletion, ultimately inducing ferroptosis. This study reveals a novel synthetic lethal relationship between ARID1A and c-MET signaling in promoting ferroptosis and proposes c-MET inhibitors as a potential therapeutic strategy for ARID1A-deficient CRC.']

['',
 'Partial response to crizotinib + regorafenib + PD-1 inhibitor in a metastatic: Colorectal cancer (CRC) with the Raf murine sarcoma viral oncogene homolog B (\nA 49-year-old Chinese male was diagnosed with ascending colon adenocarcinoma (cT3N+?M1) with liver metastases. The patient performed next-generation sequencing (NGS) using tissue and circulating tumor DNA (ctDNA), and the results showed a\nThis study reported a co-existence of a',
 'ARID1A loss enhances sensitivity to c-MET inhibition by dual targeting of GPX4 and iron homeostasis, inducing ferroptosis.: ARID1A, a subunit of the SWI/SNF chromatin-remodeling complex, functions as a tumor suppressor in various cancer types. Owing to its high frequency of inactivating mutations, ARID1A has emerged as a promising target for the development of anticancer drugs. In this study, we report that ARID1A-deficient colorectal cancer (CRC) cells induce synthetic lethality when treated with inhibitors of c-MET receptor tyrosine kinase. c-MET specific inhibitor PHA-665752 as well as two other FDA-approved drugs, crizotinib and cabozantinib, selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models. Mechanistically, we identified a tripartite functional association among ARID1A, c-MET, and NRF2, where ARID1A and c-MET pathways converge on the NRF2 transcription factor, which regulates the transcription of GPX4, a key regulator of ferroptosis. ARID1A inactivation reduces c-MET expression, decreasing NRF2 nuclear localization and its binding to the GPX4 promoter, resulting in reduced GPX4 transcription. This creates a cellular dependency on the residual c-MET for minimal GPX4 expression to survive the ferroptotic cell death. Additionally, we demonstrate that ARID1A loss leads to increased intracellular labile iron accumulation by downregulating the iron-exporting protein SLC40A1, thereby increasing cellular susceptibility to ferroptosis. Inhibition of c-MET in ARID1A-deficient CRC cells diminishes GPX4 expression, resulting in elevated lipid peroxidation and glutathione depletion, ultimately inducing ferroptosis. This study reveals a novel synthetic lethal relationship between ARID1A and c-MET signaling in promoting ferroptosis and proposes c-MET inhibitors as a potential therapeutic strategy for ARID1A-deficient CRC.']

### back

In [44]:
os.environ["MODEL_NAME"] ='qwen3:14b'

In [53]:
vector_store.similarity_search(f"The outcome of treating {fin_condition} with {treatements_eng[0]}",
                               k=4,
                               filter={"source": "37543570"}
)

[Document(id='50657083-dc28-493d-8002-416a72793f47', metadata={'source': '37543570'}, page_content='we show that the combined treatment of an anti-EpCAM neutralizing antibody (EpAb2-6) and an HGFR inhibitor (crizotinib) significantly inhibits tumor progression and prolongs survival in metastatic and orthotopic animal models of colon cancer.'),
 Document(id='d5a9d60b-f7c5-4600-8aa6-ac8a2e2169dd', metadata={'source': '37543570'}, page_content='Our findings illuminate the molecular mechanisms underlying EpCAM signaling promotion of colon cancer metastasis, further suggesting that the combination of EpAb2-6 and crizotinib may be an effective strategy for treating cancer patients with high EpCAM'),
 Document(id='d0c6a69c-977b-4a0a-98bd-172680dd3549', metadata={'source': '37543570'}, page_content='Western blotting was taken to determine the expression of proteins in colorectal cancer (CRC) cell lines. The functions of EpEX in CRC were investigated by proliferation, migration, and invasion analysis. The combined therapy was validated via a tail vein'),
 Document(id='83723f5f-d2fd-4db3-a2b1-0183bdaf640c', metadata={'source': '37543570'}, page_content='combined therapy was validated via a tail vein injection method for the metastasis and orthotopic colon cancer models.')]

In [45]:
%%time
ii =len(pmid_list) #4

api = StudyCharacteristicsExtraction()
extracted = api.run(
    papers_inp=[pmid_list[:ii],papers_ch[:ii]],
    #fields=[f'The effectiveness of treating {fin_condition} with {treatements_eng[0]}',
    #       ],
    fields=[f'Crizotinib effectiveness, string, The outcome of treating {fin_condition} with {treatements_eng[0]}'
           ],
    llm=os.getenv("MODEL_NAME"),
    chunk_size=0,
    chunk_overlap=0,
    thinking=False,
    vector_store = vector_store,
)

extracted

['40369167', '37543570', '37418240', '38212428', '38711893', '40211189', '40140597', '37773318', '41213063']
9
1
False

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib is approved for the treatment of advanced non-small cell lung cancer and ROS1-positive lung cancer, and it selectively inhibits the growth of ARID1A-deficient CRC cells.', source_id=[1, 2, 3])])]
False

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib improves the efficacy of treatment in colon cancer animal models when combined with EpAb2-6.', source_id=[2, 4, 7])])]
False

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib-IR808@BSA NPs exhibited synergistic chemophototherapy effects on tumors.', source_id=[0, 5])])]
False

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib combined with cetuximab markedly inhibited CC-HGF colony growth and reduced colony area.', source_id=[5, 8])])]
False

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Partial response (PR) was achieved in a metastatic BRAF V600E CRC patient treated with crizotinib combined with regorafenib and tislelizumab.', source_id=[3, 4, 6])])]
False

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Combination binimetinib/crizotinib showed poor tolerability with no objective responses observed in RASMT advanced CRC patients.', source_id=[4])])]
False

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='limited activity in unselected heavily pre-treated patients with advanced solid tumours', source_id=[1, 9])])]
False

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='In a study, one patient with metastatic cecal cancer treated with crizotinib showed a marked decrease in size of a skin metastasis and resolution of all contrast-enhancing tumors on imaging studies, a', source_id=[1])])]
False

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib was more sensitive to low-risk group in CRC patients.', source_id=[4])])]
CPU times: total: 297 ms
Wall time: 1min 30s

[Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib is approved for the treatment of advanced non-small cell lung cancer and ROS1-positive lung cancer, and it selectively inhibits the growth of ARID1A-deficient CRC cells.', source_id=[1, 2, 3])]),
 Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib improves the efficacy of treatment in colon cancer animal models when combined with EpAb2-6.', source_id=[2, 4, 7])]),
 Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib-IR808@BSA NPs exhibited synergistic chemophototherapy effects on tumors.', source_id=[0, 5])]),
 Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib combined with cetuximab markedly inhibited CC-HGF colony growth and reduced colony area.', source_id=[5, 8])]),
 Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Partial response (PR) was achieved in a metastatic BRAF V600E CRC patient treated with crizotinib combined with regorafenib and tislelizumab.', source_id=[3, 4, 6])]),
 Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Combination binimetinib/crizotinib showed poor tolerability with no objective responses observed in RASMT advanced CRC patients.', source_id=[4])]),
 Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='limited activity in unselected heavily pre-treated patients with advanced solid tumours', source_id=[1, 9])]),
 Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='In a study, one patient with metastatic cecal cancer treated with crizotinib showed a marked decrease in size of a skin metastasis and resolution of all contrast-enhancing tumors on imaging studies, a', source_id=[1])]),
 Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib was more sensitive to low-risk group in CRC patients.', source_id=[4])])]

In [46]:
for one_extr in extracted:
    for one_filed_res in one_extr.fieldresult:
        if one_filed_res.value!="NP":
            print(one_filed_res.value)
            print('. /n/n '.join(one_filed_res._cited_blocks))
            print()

Crizotinib is approved for the treatment of advanced non-small cell lung cancer and ROS1-positive lung cancer, and it selectively inhibits the growth of ARID1A-deficient CRC cells.
['a number of small-molecule drugs targeting c-MET are under clinical investigation, with two drugs, crizotinib and cabozantinib, receiving FDA approval. Crizotinib is approved by the FDA for the treatment of advanced non-small cell lung cancer and ROS1-positive lung cancer, whereas cabozantinib is approved for the treatment of progressive metastatic thyroid medullary carcinoma and advanced renal', 'colorectal cancer (CRC) cells induce synthetic lethality when treated with inhibitors of c-MET receptor tyrosine kinase. c-MET specific inhibitor PHA-665752 as well as two other FDA-approved drugs, crizotinib and cabozantinib, selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models. Mechanistically, we identified a tripartite functional association', 'synthetic lethality in ARID1A-deficient CRC. Notably, FDA-approved c-MET inhibitors, such as crizotinib and cabozantinib, have demonstrated enhanced cytotoxicity in ARID1A-deficient cancers, facilitating the translation of these approved drugs for repurposing in ARID1A-targeted precision cancer medicine.']

Crizotinib improves the efficacy of treatment in colon cancer animal models when combined with EpAb2-6.
['To determine whether EpAb2-6 improves the efficacy of crizotinib therapy in colon cancer animal model, we first examined the effect of crizotinib and EpAb2-6 in the colon cancer cell HCT116 metastasis model. As illustrated in Fig.Â\xa07C, NOD/SCID mice were injected intravenously with HCT116 cells and then co-treated with crizotinib and EpAb2-6, or an equivalent volume of control IgG, at 3Â\xa0days', 'In this study, we found decreased phosphorylated HGFR was observed after EpAb2-6 treatment. Furthermore, EpAb2-6 could attenuate the invasion and migration capacity of colorectal cancer cells. We confirmed that after crizotinib treatment, colorectal cancer cells were sensitized to EpAb2-6-induced apoptosis (Fig.Â\xa07A). Our results from the metastatic and orthotopic colon cancer animal model also', 'and then co-treated with crizotinib and EpAb2-6, or an equivalent volume of control IgG, at 3Â\xa0days after cell injection. As a result, the median and overall survival times of HCT116-implanted mice that received the combination of EpAb2-6 and crizotinib were increased compared to the control IgG group (Fig.Â\xa07D), supporting the idea that EpAb2-6 can improve the anti-metastatic action of']

Crizotinib-IR808@BSA NPs exhibited synergistic chemophototherapy effects on tumors.
['to guide tumor resection. Under 808 nm laser irradiation, Crizotinib-IR808@BSA NPs exhibited synergistic chemophototherapy effects on tumors. In conclusion, this innovative imaging-mediated multifunctional combination therapy strategy with good c-Met targeting ability may provide a new approach for colorectal cancer treatment.', 'was fabricated by using bovine serum albumin (BSA) nanoparticles (NPs) with excellent biocompatibility and biosafety. The prepared Crizotinib-IR808@BSA NPs showed tumor targeting capability as well as use for noninvasive biomedical vascular NIR-II imaging with intraoperative real-time NIR-II imaging to guide tumor resection. Under 808 nm laser irradiation, Crizotinib-IR808@BSA NPs exhibited']

Crizotinib combined with cetuximab markedly inhibited CC-HGF colony growth and reduced colony area.
['However, both cetuximab and crizotinib combined, markedly inhibited CC-HGF colony growth (Fig.Â\xa04A). Additionally, the average colony area and total colony area of CC-HGF 3D colonies were also reduced in the cetuximab and crizotinib combination (Fig. S5). We next tested the effect of cetuximab and/or crizotinib treatments at the signaling level by immunoblotting. Here, as expected, cetuximab', 'are shared in Fig.Â\xa04C, which showed that CC colony growth was extremely sensitive to cetuximab but were unperturbed by crizotinib addition. In contrast, growth of CC-HGF cell colonies was not affected by cetuximab, but inhibition of colony growth was only observed in cetuximab/crizotinib combination. More interestingly, while crizotinib alone treatment didnâ\x80\x99t affect colony growth of CC-HGF']

Partial response (PR) was achieved in a metastatic BRAF V600E CRC patient treated with crizotinib combined with regorafenib and tislelizumab.
['This study reported a co-existence of a BRAF V600E mutation, c-MET amplification and TPM4-ALK fusion in a CRC patient. Administration of crizotinib combined with regorafenib and tislelizumab obtained an obvious response. Furthermore, continuous ctDNA detection appears to be a promising technique to monitor tumor burden, which may provide better clinical decision support during the disease course.', 'In this study, we identified a rarely reported TPM4-ALK fusion co-occurring with MET amplification in a CRC patient with BRAF V600E mutation who achieved partial response (PR) after the combined therapy of programmed cell death protein 1 (PD-1) inhibitor (tislelizumab), MET/ALK inhibitor (crizotinib) plus multikinase inhibitor (regorafenib), and whose response was monitored by continuous ctDNA', 'response (PR) after the combined therapy of programmed cell death protein 1 (PD-1) inhibitor (tislelizumab), MET/ALK inhibitor (crizotinib) plus multikinase inhibitor (regorafenib), and whose response was monitored by continuous circulating tumor DNA (ctDNA) detection.']

Combination binimetinib/crizotinib showed poor tolerability with no objective responses observed in RASMT advanced CRC patients.
['Conclusions\nCombination binimetinib/crizotinib showed a poor tolerability with no objective responses observed in RASMT advanced CRC patients.\nEudraCT-Number: 2014â\x80\x93000463 -â\x80\x8940 (20/06/2014: A Sequential Phase I study of MEK1/2 inhibitors PD- 0325901 or Binimetinib combined with cMET inhibitor Crizotinib in RAS Mutant and RAS Wild Type with aberrant c-MET).\nSupplementary Information']

limited activity in unselected heavily pre-treated patients with advanced solid tumours
['In summary, inhibition of the MEK1/2 and c-MET kinases using PD-0325901 and crizotinib, was well tolerated with a manageable toxicity profile, but with limited activity in unselected heavily pre-treated patients with advanced solid tumours. Further exploration of this combination in a biomarker selected population of patients with advanced CRC was not pursued due to the termination of the', 'the limited anti-tumour activity observed in our clinical trial with crizotinib and PD-0325901 could be attributable to the heavily pre-treated, heterogeneous and biomarker-unselected participants in our study, together with the limited dataset.']

In a study, one patient with metastatic cecal cancer treated with crizotinib showed a marked decrease in size of a skin metastasis and resolution of all contrast-enhancing tumors on imaging studies, a
['In a study of nine ALK -rearranged colorectal cancers (~0.2% of colorectal malignancies), one metastatic cecal cancer patient with a STRN-ALK fusion protein was treated with the ALK inhibitor ceritinib, which resulted in a marked decrease in size of a skin metastasis, and resolution of all contrast-enhancing tumors on imaging studies. This patient-derived treatment benefit for almost 9 months.']

Crizotinib was more sensitive to low-risk group in CRC patients.
['showed significantly greater levels of immune infiltration (P P ARHGEF17 mutation rate was 6%. Medications such as CGP-082996, Dasatinib, Erlotinib, and Salubrinal were more sensitive to high-risk group, whereas drugs such as FTI-277, DMOG, and Crizotinib were more sensitive to low-risk group. UGT1A6 and IRGM were significantly upregulated in tumor group as revealed by qRT-PCR. This study']

In [123]:
os.getenv("MODEL_NAME")

'qwen3:14b'

In [ ]:
h = FieldResult(
                                 name='Crizotinib effectiveness', 
                                 value='NP', 
                                 source_id=[]
                  )
h._cited_blocks=[]
hey = Results(fieldresult=[h])
hey

In [144]:
rr = extract.combine_res(fin_condition, treatements_eng[0], 
                         extracted, pmid_list)
rr

'Crizotinib selectively inhibits the growth of ARID1A-deficient CRC cells [40369167]. Crizotinib improves the efficacy of treatment in colon cancer animal models when combined with EpAb2-6 [37543570]. Crizotinib-IR808@BSA NPs exhibited synergistic chemophototherapy effects on tumors [37418240]. Crizotinib combined with cetuximab markedly inhibited CC-HGF colony growth and reduced colony area [38212428]. Partial response (PR) was achieved in a metastatic BRAF V600E CRC patient treated with crizotinib combined with regorafenib and tislelizumab [38711893]. Combination binimetinib/crizotinib showed poor tolerability with no objective responses observed in RASMT advanced CRC patients [40211189]. In a study, one patient with metastatic cecal cancer treated with crizotinib showed a marked decrease in size of a skin metastasis and resolution of all contrast-enhancing tumors on imaging studies [37773318]. Crizotinib was more sensitive to low-risk group in CRC patients [41213063].'

### results with qwen3:14b

In [230]:
ii =len(pmid_list) #4

api = StudyCharacteristicsExtraction()
extracted = api.run(
    papers_inp=[pmid_list[:ii],papers_ch[:ii]],
    #fields=[f'The effectiveness of treating {fin_condition} with {treatements_eng[0]}',
    #       ],
    fields=[f'Crizotinib effectiveness, string, The outcome of treating {fin_condition} with {treatements_eng[0]}'
           ],
    llm=os.getenv("MODEL_NAME"),
    chunk_size=0,
    chunk_overlap=0,
    thinking=False,
    vector_store = vector_store,
)

extracted

['40369167', '37543570', '37418240', '38212428', '38711893', '40211189', '40140597', '37773318', '41213063']
9
1
False

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models.', source_id=[1, 3, 6])])]
False

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib shows efficacy in treating colorectal cancer when combined with EpAb2-6, significantly inhibiting tumor progression and improving survival in animal models.', source_id=[0, 5, 7])])]
False

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib-IR808@BSA NPs showed tumor targeting capability and synergistic chemophototherapy effects on tumors.', source_id=[5, 6])])]
False

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib overcomes cetuximab resistance in colorectal cancer by inhibiting MET/RON in vitro and in vivo xenograft studies.', source_id=[2, 5, 9])])]
False

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Partial response to crizotinib + regorafenib + PD-1 inhibitor in a metastatic BRAF V600EMT colon cancer patient with acquired C-MET amplification and TPM4-ALK fusion', source_id=[1, 2, 3])])]
False

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='limited anti-tumour activity in these heterogeneous', source_id=[1])])]
False

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='dual c-MET/MEK1/2 inhibition attenuated RASMT colorectal cancer (CRC) xenograft growth', source_id=[0])])]
False

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='NP', source_id=[])])]
False

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib was more sensitive to low-risk group in CRC patients.', source_id=[3])])]

[Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models.', source_id=[1, 3, 6])]),
 Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib shows efficacy in treating colorectal cancer when combined with EpAb2-6, significantly inhibiting tumor progression and improving survival in animal models.', source_id=[0, 5, 7])]),
 Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib-IR808@BSA NPs showed tumor targeting capability and synergistic chemophototherapy effects on tumors.', source_id=[5, 6])]),
 Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib overcomes cetuximab resistance in colorectal cancer by inhibiting MET/RON in vitro and in vivo xenograft studies.', source_id=[2, 5, 9])]),
 Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Partial response to crizotinib + regorafenib + PD-1 inhibitor in a metastatic BRAF V600EMT colon cancer patient with acquired C-MET amplification and TPM4-ALK fusion', source_id=[1, 2, 3])]),
 Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='limited anti-tumour activity in these heterogeneous', source_id=[1])]),
 Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='dual c-MET/MEK1/2 inhibition attenuated RASMT colorectal cancer (CRC) xenograft growth', source_id=[0])]),
 Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='NP', source_id=[])]),
 Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib was more sensitive to low-risk group in CRC patients.', source_id=[3])])]

In [69]:
pmid_list[5:]

['40211189', '40140597', '37773318', '41213063']

In [253]:
vector_store.similarity_search_with_score(f"The outcome/response of {treatements_eng[0]} treatment",
                               k=10,
                               filter={"source": "40140597"}
)

[(Document(id='4e961c9f-d43d-45e8-b326-a781839001f7', metadata={'source': '40140597'}, page_content='with O.D dosing, with values comparable to those published by Tan et al. for crizotinib monotherapy. Additionally, the median trough plasma concentrations of crizotinib observed in all cohorts was in excess of 62â\x80\x89ng/mL, the pre-clinically predicted'),
  0.23538672924041748),
 (Document(id='3f5e2d26-d1a2-41df-8a9a-6e7985f58e46', metadata={'source': '40140597'}, page_content='Twenty-five patients were recruited in 4 cohorts up to doses of crizotinib 200â\x80\x89mg B.D continuously with PD-0325901 8â\x80\x89mg B.D, days 1â\x80\x9321 every 28 days. One in six patients exhibited a dose-limiting toxicity at this dose level. Drug-related adverse'),
  0.27453482151031494),
 (Document(id='8d9d512a-1e90-49bf-b8fd-2e6304e6f864', metadata={'source': '40140597'}, page_content='selected the combination of crizotinib and the MEK1/2 inhibitor PD-0325901 for clinical investigation.'),
  0.2841690182685852),
 (Document(id='ae5455a8-3aa3-41ee-b714-aa55f9c81232', metadata={'source': '40140597'}, page_content='activity observed in our clinical trial with crizotinib and PD-0325901 could be attributable to the heavily pre-treated, heterogeneous and biomarker-unselected participants in our study, together with the limited dataset.'),
  0.2932877540588379),
 (Document(id='a1e90784-d6d5-4b58-8a26-ff0350038c75', metadata={'source': '40140597'}, page_content='This phase I dose-escalation study demonstrated that the combination of PD-0325901 with crizotinib is safe, without any unexpected toxicities. The most common adverse events included rash, nausea, diarrhoea, fatigue, vomiting, oedema, anaemia and'),
  0.29893219470977783),
 (Document(id='bf4ddb02-3721-4a9f-b6f7-4503aa6e4320', metadata={'source': '40140597'}, page_content='crizotinib was absorbed with peak plasma concentrations occurring within 2.76 and 5.21 after dosing, comparable to those observed when administered alone. The Tmax, Cmax, Cmin, AUC0-10h, AUC0-24h of crizotinib (measured for 0â\x80\x9324â\x80\x89h and 0â\x80\x9310â\x80\x89h in'),
  0.29973751306533813),
 (Document(id='21ed5a68-a1fa-46aa-b223-c1bef5016606', metadata={'source': '40140597'}, page_content='of 62â\x80\x89ng/mL, the pre-clinically predicted effective concentration to inhibit c-MET (data not shown). Importantly, the dose escalation of PD-0325901 between cohort 2 and 4 did not appear to affect the PK parameters of crizotinib measured.'),
  0.3129346966743469),
 (Document(id='c6bcc97f-17bf-41d4-bc4a-4cbbfacf6e97', metadata={'source': '40140597'}, page_content='the study and compared with available values from the literature. B.D dosing of crizotinib did result in significant (1.6â\x80\x932.6 fold) increases in Cmax, Cmin and AUC0-10h on days 21 and 28 compared with O.D dosing, with values comparable to those'),
  0.31412774324417114),
 (Document(id='0daa2eb9-2a44-43eb-a887-8028db47c1d3', metadata={'source': '40140597'}, page_content='also showed a marked reduction in pERK1/2 levels following 15 days of combined PD-0325901/crizotinib treatment in all cohorts, but this was only significant in cohorts 1, 2 and 4.'),
  0.31599903106689453),
 (Document(id='e3a26c65-3dc0-4047-8d52-b59bc4056905', metadata={'source': '40140597'}, page_content='The effect of PD-0325901 and crizotinib on PK parameters of crizotinib and PD-0325901 respectively was assessed in 22 patients at the 4 dose levels (Fig.Â\xa01; Supplementary TableÂ\xa0S5). Following oral administration, crizotinib was absorbed with peak plasma'),
  0.3232305645942688)]

In [31]:
STUDY_FIELDS_EXTRACTION_3 = """You are now the following python function: ```
def extract_fields_from_input_study(inputs: Dict[str, Any]) -> str:
    \"\"\"
    This function is tasked with analyzing clinical trial study reports or papers to extract specific information as structured data and provide citations for the extracted information.
    The user will provide a list of fields they are interested in, along with a natural language description for each field to guide you on what content to look for and from which parts of the report to extract it.

    IMPORTANT:
    For each field described by the user, you need to:
    1. Identify and extract the relevant information from the report, based on the provided description.
       The answer should be under 200 characters. Summarize the information without losing clarity. 
       The final answer should be a complete sentence with necessary context.
    2. Structure the extracted information into a standard format whenever possible (e.g., integer, numerical values, dates, keywords, list of terms). 
        If standardization is not possible, the information should be presented in text format.
        If the field is not found in the report, the extracted value should be "NP".
    3. Provide a reference to the document ID from which this information was extracted.
        This citation id should be restricted to be integers only.
        You should NOT cite more than three sources for a single field.
        If the field is "NP", sources should be an empty list.
        You should try your best to provide the most relevant and specific citation for each field.
        If two or more sources are equally relevant, you can just cite one of them.

    The function returns a string representing a dictionary with each key representing a field and its extracted value.

# User provided inputs
paper_content = \"\"\"{paper_content}\"\"\"
fields = \"\"\"{fields}\"\"\"

inputs = {{
    "paper_content": paper_content,
    "fields": fields
}}

# Reply Format: 
Return the information in the following JSON-format.
```json
{{      
    [
        {{
            "name": "fieldName1",
            "value": "extractedInfo1",
            "source_id":[1, 3]
        }}
    ]
}}
```
You MUST return ONLY valid JSON, Do NOT include any explanations, comments, or extra text.
"""

In [32]:
def search(query, doc_id):
        
    retrieved_docs = vector_store.similarity_search(query, k=10,
                                                         filter={"source": doc_id})
    #docs_content = "\n\n".join(doc.page_content for doc in retrieved_docs)
    return [i.page_content for i in retrieved_docs]

def combine_blocks_text(blocks, format="xml"):
    #from langchain.docstore.document import Document
    from langchain_core.documents import Document
    # combine the blocks
    new_blocks = []
    for i, block in enumerate(blocks):
        if isinstance(block, Document):
            block = block.page_content
        new_blocks.append(block)
    new_blocks = list(new_blocks)
    if format == "xml":
        new_block_strs = [f"<source id=\"{i}\"><content>{block}</content></source>" for i,block in enumerate(new_blocks)]
    else:
        new_block_strs = [f"[[citation:{i}]] {block}" for i,block in enumerate(new_blocks)]
    combined = '\n\n'.join(new_block_strs)
    return combined#, new_blocks

In [33]:
#from trialmind.prompts.extraction import STUDY_FIELDS_EXTRACTION_3
fields=[f'Crizotinib effectiveness, string, The outcome of treating {fin_condition} with {treatements_eng[0]}'
           ]
fields_info = '\n'.join([f"<field id={idx+1}>\"{field}\"</field>" for idx, field in enumerate(fields)])
batch_inputs = []
for paper_id in pmid_list[6:7]:
    
    found_parts =search(fields[0].split(',')[-1], paper_id)
    combined = combine_blocks_text(found_parts)
    batch_inputs.append({
                    "paper_content": combined,
                    "fields": fields_info
                })

prompt_content = STUDY_FIELDS_EXTRACTION_3.format(**batch_inputs[0])
messages = [
    {
        "role": "user",
        "content": prompt_content#+prompt_template[fin_idx:]
    }
]

In [34]:
pmid_list[6:9]

['40140597', '37773318', '41213063']

In [35]:
print(prompt_content)

You are now the following python function: ```
def extract_fields_from_input_study(inputs: Dict[str, Any]) -> str:
    """
    This function is tasked with analyzing clinical trial study reports or papers to extract specific information as structured data and provide citations for the extracted information.
    The user will provide a list of fields they are interested in, along with a natural language description for each field to guide you on what content to look for and from which parts of the report to extract it.

    IMPORTANT:
    For each field described by the user, you need to:
    1. Identify and extract the relevant information from the report, based on the provided description.
       The answer should be under 200 characters. Summarize the information without losing clarity.
       The final answer should be a complete sentence with necessary context.
    2. Structure the extracted information into a standard format whenever possible (e.g., integer, numerical values, dates, keywords, list of terms).
        If standardization is not possible, the information should be presented in text format.
        If the field is not found in the report, the extracted value should be "NP".
    3. Provide a reference to the document ID from which this information was extracted.
        This citation id should be restricted to be integers only.
        You should NOT cite more than three sources for a single field.
        If the field is "NP", sources should be an empty list.
        You should try your best to provide the most relevant and specific citation for each field.
        If two or more sources are equally relevant, you can just cite one of them.

    The function returns a string representing a dictionary with each key representing a field and its extracted value.

# User provided inputs
paper_content = """<source id="0"><content>selected population of patients with advanced CRC was not pursued due to the termination of the clinical development of PD-0325901. Moving forward, a phase Ia/b trial evaluating the combination of crizotinib with an alternative MEK1/2 inhibitor binimetinib in RAS mutant CRC patients with aberrant c-MET was completed.</content></source>

<source id="1"><content>In summary, inhibition of the MEK1/2 and c-MET kinases using PD-0325901 and crizotinib, was well tolerated with a manageable toxicity profile, but with limited activity in unselected heavily pre-treated patients with advanced solid tumours. Further exploration of this combination in a biomarker selected population of patients with advanced CRC was not pursued due to the termination of the</content></source>

<source id="2"><content>A phase Ia study of the MEK1/2 inhibitor PD-0325901 with the c-MET inhibitor crizotinib in patients with advanced solid cancers
Background</content></source>

<source id="3"><content>that MET could represent a valuable therapeutic target when combined with MEK1/2 inhibitors in patients with KRASMT mCRC, and selected the combination of crizotinib and the MEK1/2 inhibitor PD-0325901 for clinical investigation.</content></source>

<source id="4"><content>Single-agent MEK1/2 inhibition has been disappointing in clinical trials targeting RAS mutant (MT) cancers, probably due to upstream receptor activation, resulting in resistance. We previously found that dual c-MET/MEK1/2 inhibition attenuated RASMT colorectal cancer (CRC) xenograft growth. In this study, we assessed safety of MEK1/2 inhibitor PD-0325901 with c-MET inhibitor crizotinib and</content></source>

<source id="5"><content>due to the late occurrence of retinal vein occlusion (RVO). The second drug, crizotinib, is an oral ATP-competitive small-molecule inhibitor of c-MET, ALK and ROS1. Crizotinib is approved for the first-line treatment of patients with metastatic lung cancer whose tumours are either ALK or ROS1 positive, and the recommended oral dose is 250âmg B.D.</content></source>

<source id="6"><content>Targeting oncogenic drivers has improved outcomes for several human malignancies. Compared with lung or breast cancers, fewer clinically-actionable oncogenic alterations have been identified in colorectal cancer (CRC). Monoclonal antibodies against the epidermal growth factor receptor (EGFR), such as cetuximab and panitumumab, together with standard chemotherapies form the mainstay of tumour</content></source>

<source id="7"><content>CRC in vitro and in vivo. Additionally, pharmacological blockade of this resistance pathway using the cMET inhibitor crizotinib (formerly PF-02341066) increased MEK1/2-inhibitor-induced apoptosis and growth inhibition in vitro and in vivo in KRASMT CRC models. Based on this and other studies, we reasoned that MET could represent a valuable therapeutic target when combined with MEK1/2 inhibitors</content></source>

<source id="8"><content>data would indicate that co-administration of crizotinib with PD-0325901 appears to reduce the plasma concentration of PD-0325901 and its metabolite on Cycle 1 Day 21 compared to Day -1, especially at the highest 8âmg B.D dose.</content></source>

<source id="9"><content>the limited anti-tumour activity observed in our clinical trial with crizotinib and PD-0325901 could be attributable to the heavily pre-treated, heterogeneous and biomarker-unselected participants in our study, together with the limited dataset.</content></source>"""
fields = """<field id=1>"Crizotinib effectiveness, string, The outcome of treating Colorectal cancer with Crizotinib"</field>"""

inputs = {
    "paper_content": paper_content,
    "fields": fields
}

# Reply Format:
Return the information in the following JSON-format.
```json
{
    [
        {
            "name": "fieldName1",
            "value": "extractedInfo1",
            "source_id":[1, 3]
        }
    ]
}
```
You MUST return ONLY valid JSON, Do NOT include any explanations, comments, or extra text.

In [36]:
from pydantic import BaseModel, validator, Field, conlist  
from typing import Dict, Literal
from openai import AsyncOpenAI
class FieldResult(BaseModel):
    name: Literal[fields[0].split(',')[0]] = Field( description='Field name that accurately represents the content of the field based on its description.',
                     max_length=25)
    value: str = Field(description='Extracted information from the text based on the field description.',
                      max_length=200)
    source_id: conlist(int,min_length=0, max_length=3) = Field(description='Cited document IDs.')
class Results(BaseModel):
    fieldresult: list[FieldResult] = Field(min_length=1, max_length=1)

In [42]:
async_openai_client = AsyncOpenAI(
    base_url=os.getenv("BASE_URL"),
    api_key=os.getenv("OPENAI_API_KEY"),
    http_client=httpx.AsyncClient(verify=False)
)

response = await async_openai_client.chat.completions.parse(
        model=os.getenv("MODEL_NAME"),
        messages=messages,
        #tools=tools,
        temperature=0,
        #extra_body={"structured_outputs": {"json": tools[0]}},
        response_format=Results.model_json_schema(),
        #extra_body={"reasoning_effort": "none"}
        #**kwargs
    )
print(response.choices[0].message.content)

[{
    "name": "Crizotinib effectiveness",
    "value": "Limited anti-tumour activity was observed in unselected heavily pre-treated patients with advanced solid tumours treated with crizotinib and PD-0325901.",
    "source_id": [1, 9]
}]

In [43]:
async_openai_client = AsyncOpenAI(
    base_url=os.getenv("BASE_URL"),
    api_key=os.getenv("OPENAI_API_KEY"),
    http_client=httpx.AsyncClient(verify=False)
)

response = await async_openai_client.chat.completions.parse(
        model=os.getenv("MODEL_NAME"),
        messages=messages,
        #tools=tools,
        temperature=0,
        #extra_body={"structured_outputs": {"json": tools[0]}},
        response_format=Results,
        extra_body={"reasoning_effort": "none"}
        #**kwargs
    )
print(response.choices[0].message.content)

ValidationError: 1 validation error for Results
fieldresult
  Field required [type=missing, input_value={'Crizotinib effectivenes...CRC.', 'source_id': [9]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.12/v/missing

In [240]:
vector_store.similarity_search(f"The outcome/response of {treatements_eng[0]} treatment",
                               k=10,
                               filter={"source": "40140597"}
)

[Document(id='4e961c9f-d43d-45e8-b326-a781839001f7', metadata={'source': '40140597'}, page_content='with O.D dosing, with values comparable to those published by Tan et al. for crizotinib monotherapy. Additionally, the median trough plasma concentrations of crizotinib observed in all cohorts was in excess of 62â\x80\x89ng/mL, the pre-clinically predicted'),
 Document(id='3f5e2d26-d1a2-41df-8a9a-6e7985f58e46', metadata={'source': '40140597'}, page_content='Twenty-five patients were recruited in 4 cohorts up to doses of crizotinib 200â\x80\x89mg B.D continuously with PD-0325901 8â\x80\x89mg B.D, days 1â\x80\x9321 every 28 days. One in six patients exhibited a dose-limiting toxicity at this dose level. Drug-related adverse'),
 Document(id='8d9d512a-1e90-49bf-b8fd-2e6304e6f864', metadata={'source': '40140597'}, page_content='selected the combination of crizotinib and the MEK1/2 inhibitor PD-0325901 for clinical investigation.'),
 Document(id='ae5455a8-3aa3-41ee-b714-aa55f9c81232', metadata={'source': '40140597'}, page_content='activity observed in our clinical trial with crizotinib and PD-0325901 could be attributable to the heavily pre-treated, heterogeneous and biomarker-unselected participants in our study, together with the limited dataset.'),
 Document(id='a1e90784-d6d5-4b58-8a26-ff0350038c75', metadata={'source': '40140597'}, page_content='This phase I dose-escalation study demonstrated that the combination of PD-0325901 with crizotinib is safe, without any unexpected toxicities. The most common adverse events included rash, nausea, diarrhoea, fatigue, vomiting, oedema, anaemia and'),
 Document(id='bf4ddb02-3721-4a9f-b6f7-4503aa6e4320', metadata={'source': '40140597'}, page_content='crizotinib was absorbed with peak plasma concentrations occurring within 2.76 and 5.21 after dosing, comparable to those observed when administered alone. The Tmax, Cmax, Cmin, AUC0-10h, AUC0-24h of crizotinib (measured for 0â\x80\x9324â\x80\x89h and 0â\x80\x9310â\x80\x89h in'),
 Document(id='21ed5a68-a1fa-46aa-b223-c1bef5016606', metadata={'source': '40140597'}, page_content='of 62â\x80\x89ng/mL, the pre-clinically predicted effective concentration to inhibit c-MET (data not shown). Importantly, the dose escalation of PD-0325901 between cohort 2 and 4 did not appear to affect the PK parameters of crizotinib measured.'),
 Document(id='c6bcc97f-17bf-41d4-bc4a-4cbbfacf6e97', metadata={'source': '40140597'}, page_content='the study and compared with available values from the literature. B.D dosing of crizotinib did result in significant (1.6â\x80\x932.6 fold) increases in Cmax, Cmin and AUC0-10h on days 21 and 28 compared with O.D dosing, with values comparable to those'),
 Document(id='0daa2eb9-2a44-43eb-a887-8028db47c1d3', metadata={'source': '40140597'}, page_content='also showed a marked reduction in pERK1/2 levels following 15 days of combined PD-0325901/crizotinib treatment in all cohorts, but this was only significant in cohorts 1, 2 and 4.'),
 Document(id='e3a26c65-3dc0-4047-8d52-b59bc4056905', metadata={'source': '40140597'}, page_content='The effect of PD-0325901 and crizotinib on PK parameters of crizotinib and PD-0325901 respectively was assessed in 22 patients at the 4 dose levels (Fig.Â\xa01; Supplementary TableÂ\xa0S5). Following oral administration, crizotinib was absorbed with peak plasma')]

In [28]:
extracted_gm = extracted

In [29]:
extracted_gm

[Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models.', source_id=[1, 3])]),
 Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib, when combined with EpAb2-6, significantly inhibits tumor progression and prolongs survival in metastatic and orthotopic colon cancer models.', source_id=[1, 3])]),
 Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Provides a new approach for colorectal cancer treatment with good c-Met targeting ability', source_id=[1])]),
 Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Crizotinib could overcome HGF-induced cetuximab resistance in colorectal cancer.', source_id=[3])]),
 Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Partial response to crizotinib + regorafenib + PD-1 inhibitor in metastatic colorectal cancer', source_id=[2])])]

### with hf

In [269]:
os.environ["BASE_URL"] = "https://router.huggingface.co/v1"
os.environ["MODEL_NAME"] ='zai-org/GLM-4.7'#'meta-llama/Llama-3.3-70B-Instruct'
os.environ["OPENAI_API_KEY"] = os.getenv("HUGGINGFACE_HUB_TOKEN2")

In [271]:

api = StudyCharacteristicsExtraction()
extracted = api.run(
    papers=papers0[:2],
    fields=[f'Crizotinib Results, string, the effectiveness of treating {fin_condition} with {treatements_eng[0]}',
           'Participants, string, number of participants'],#api.DEFAULT_FIELDS,
    llm=os.getenv("MODEL_NAME"),
    chunk_size=500,
    chunk_overlap=200,
    thinking=False,
)
extracted

You are now the following python function: ```
def extract_fields_from_input_study(inputs: Dict[str, Any]) -> str:
    """
    This function is tasked with analyzing clinical trial study reports or papers to extract specific information as structured data and provide citations for the extracted information.
    The user will provide a list of fields they are interested in, along with a natural language description for each field to guide you on what content to look for and from which parts of the report to extract it.

    IMPORTANT:
    For each field described by the user, you need to:
    1. Identify and extract the relevant information from the report, based on the provided description.
    2. Generate a field name that accurately represents the content of the field based on its description.
    3. Structure the extracted information into a standard format whenever possible (e.g., integer, numerical values, dates, keywords, list of terms).
        If standardization is not possible, the information should be presented in text format.
        If the field is not found in the report, the extracted value should be "NP".
    4. Provide a reference to the document ID from which this information was extracted.
        This citation id should be restricted to be integers only.
        You should NOT cite more than three sources for a single field.
        You should try your best to provide the most relevant and specific citation for each field.
        If two or more sources are equally relevant, you can just cite one of them.

    The function returns a string representing a dictionary with each key representing a field and its extracted value.

# User provided inputs
paper_content = """{paper_content}"""
fields = """{fields}"""

inputs = {{
    "paper_content": paper_content,
    "fields": fields
}}

# Reply Format:
Return the information in the following JSON-format.
```json
{{
    [
        {{
            "name": "fieldName1",
            "value": "extractedInfo1",
            "source_id":[1, 2, 3]
        }},
        {{
            "name":"fieldName2",
            "value":"extractedInfo2",
            "source_id":[4]
        }},
        ...
    ]
}}
```
You MUST return ONLY valid JSON, Do NOT include any explanations, comments, or extra text.

1

parsed_results in asynch ['[{"name":"Crizotinib Results","value":"Partial response (PR) was achieved when crizotinib was combined with regorafenib and tislelizumab. The treatment resulted in significantly reduced BRAF mutation frequency, and MET amplification and TPM4-ALK fusion became undetectable. The patient achieved 11 months overall survival.","source_id":[3,4,8]},{"name":"Participants","value":"1","source_id":[0]}]']

parsed_results in asynch ['[{"name": "Crizotinib Results", "value": "The best clinical response was stable disease in seven patients (29%).", "source_id": [4]}, {"name": "Participants", "value": "Twenty-five patients", "source_id": [1, 5]}]']

parsed_outputs: [[{'name': 'Crizotinib Results', 'value': 'Partial response (PR) was achieved when crizotinib was combined with regorafenib and tislelizumab. The treatment resulted in significantly reduced BRAF mutation frequency, and MET amplification and TPM4-ALK fusion became undetectable. The patient achieved 11 months overall survival.', 'source_id': [3, 4, 8]}, {'name': 'Participants', 'value': '1', 'source_id': [0]}], [{'name': 'Crizotinib Results', 'value': 'The best clinical response was stable disease in seven patients (29%).', 'source_id': [4]}, {'name': 'Participants', 'value': 'Twenty-five patients', 'source_id': [1, 5]}]]

[[{'name': 'Crizotinib Results',
   'value': 'Partial response (PR) was achieved when crizotinib was combined with regorafenib and tislelizumab. The treatment resulted in significantly reduced BRAF mutation frequency, and MET amplification and TPM4-ALK fusion became undetectable. The patient achieved 11 months overall survival.',
   'source_id': [3, 4, 8],
   'cited_blocks': ['reported a co-existence of a BRAF V600E mutation, c-MET amplification and TPM4-ALK fusion in a CRC patient. Administration of crizotinib combined with regorafenib and tislelizumab obtained an obvious response. Furthermore, continuous ctDNA detection appears to be a promising technique to monitor tumor burden, which may provide better clinical decision support during the disease course.',
    'Partial response to crizotinib + regorafenib + PD-1 inhibitor in a metastatic BRAF V600EMT colon cancer patient with acquired C-MET amplification and TPM4-ALK fusion: a case report.',
    '(tislelizumab, dabrafenib, and trametinib), thus he was finally treated with programmed cell death protein 1 (PD-1) inhibitor (tislelizumab), MET/ALK inhibitor (crizotinib) plus multikinase inhibitor (regorafenib). Imageological examinations showed that PR was achieved and ctDNA sequencing results indicated a significantly reduced BRAF mutation frequency, MET amplification and TPM4-ALK fusion were undetectable. NGS analysis of peripheral blood showed a recurrence of the MET acquired resistant']},
  {'name': 'Participants',
   'value': '1',
   'source_id': [0],
   'cited_blocks': ['targets in non-small cell lung cancer (NSCLC). However, both of them are of extremely lower frequencies (<2%) in metastatic CRC, and few studies have mentioned the real application of their inhibitors in CRC treatment. Case Description: A 49-year-old Chinese male was diagnosed with ascending colon adenocarcinoma (cT3N+?M1) with liver metastases. The patient performed next-generation sequencing (NGS) using tissue and circulating tumor DNA (ctDNA), and the results showed a BRAF V600E mutation. He']}],
 [{'name': 'Crizotinib Results',
   'value': 'The best clinical response was stable disease in seven patients (29%).',
   'source_id': [4],
   'cited_blocks': ['B.D, days 1-21 every 28 days. One in six patients exhibited a dose-limiting toxicity at this dose level. Drug-related adverse events were in keeping with single-agent toxicity profiles. The best clinical response was stable disease in seven patients (29%). CONCLUSIONS: PD-0325901/crizotinib can be given together at pharmacologically-active doses. The MTD for PD-0325901/crizotinib was 8â\x80\x89mg B.D (days 1-21) and 200â\x80\x89mg B.D continuously in a 28-days cycle. The combination was further explored']},
  {'name': 'Participants',
   'value': 'Twenty-five patients',
   'source_id': [1, 5],
   'cited_blocks': ['growth. In this study, we assessed safety of MEK1/2 inhibitor PD-0325901 with c-MET inhibitor crizotinib and determined the optimal biological doses for subsequent clinical trials. METHODS: In this dose-escalation phase I trial, patients with advanced solid tumours received PD-0325901 with crizotinib, using a rolling-6 design to determine the maximum tolerable dose (MTD) and safety/tolerability. Blood samples for pharmacokinetics and skin biopsies were collected. RESULTS: Twenty-five patients',
    'using a rolling-6 design to determine the maximum tolerable dose (MTD) and safety/tolerability. Blood samples for pharmacokinetics and skin biopsies were collected. RESULTS: Twenty-five patients were recruited in 4 cohorts up to doses of crizotinib 200â\x80\x89mg B.D continuously with PD-0325901 8â\x80\x89mg B.D, days 1-21 every 28 days. One in six patients exhibited a dose-limiting toxicity at this dose level. Drug-related adverse events were in keeping with single-agent toxicity profiles. The best']}]]

In [272]:
1

1

In [273]:
extracted

[[{'name': 'Crizotinib Results',
   'value': 'Partial response (PR) was achieved when crizotinib was combined with regorafenib and tislelizumab. The treatment resulted in significantly reduced BRAF mutation frequency, and MET amplification and TPM4-ALK fusion became undetectable. The patient achieved 11 months overall survival.',
   'source_id': [3, 4, 8],
   'cited_blocks': ['reported a co-existence of a BRAF V600E mutation, c-MET amplification and TPM4-ALK fusion in a CRC patient. Administration of crizotinib combined with regorafenib and tislelizumab obtained an obvious response. Furthermore, continuous ctDNA detection appears to be a promising technique to monitor tumor burden, which may provide better clinical decision support during the disease course.',
    'Partial response to crizotinib + regorafenib + PD-1 inhibitor in a metastatic BRAF V600EMT colon cancer patient with acquired C-MET amplification and TPM4-ALK fusion: a case report.',
    '(tislelizumab, dabrafenib, and trametinib), thus he was finally treated with programmed cell death protein 1 (PD-1) inhibitor (tislelizumab), MET/ALK inhibitor (crizotinib) plus multikinase inhibitor (regorafenib). Imageological examinations showed that PR was achieved and ctDNA sequencing results indicated a significantly reduced BRAF mutation frequency, MET amplification and TPM4-ALK fusion were undetectable. NGS analysis of peripheral blood showed a recurrence of the MET acquired resistant']},
  {'name': 'Participants',
   'value': '1',
   'source_id': [0],
   'cited_blocks': ['targets in non-small cell lung cancer (NSCLC). However, both of them are of extremely lower frequencies (<2%) in metastatic CRC, and few studies have mentioned the real application of their inhibitors in CRC treatment. Case Description: A 49-year-old Chinese male was diagnosed with ascending colon adenocarcinoma (cT3N+?M1) with liver metastases. The patient performed next-generation sequencing (NGS) using tissue and circulating tumor DNA (ctDNA), and the results showed a BRAF V600E mutation. He']}],
 [{'name': 'Crizotinib Results',
   'value': 'The best clinical response was stable disease in seven patients (29%).',
   'source_id': [4],
   'cited_blocks': ['B.D, days 1-21 every 28 days. One in six patients exhibited a dose-limiting toxicity at this dose level. Drug-related adverse events were in keeping with single-agent toxicity profiles. The best clinical response was stable disease in seven patients (29%). CONCLUSIONS: PD-0325901/crizotinib can be given together at pharmacologically-active doses. The MTD for PD-0325901/crizotinib was 8â\x80\x89mg B.D (days 1-21) and 200â\x80\x89mg B.D continuously in a 28-days cycle. The combination was further explored']},
  {'name': 'Participants',
   'value': 'Twenty-five patients',
   'source_id': [1, 5],
   'cited_blocks': ['growth. In this study, we assessed safety of MEK1/2 inhibitor PD-0325901 with c-MET inhibitor crizotinib and determined the optimal biological doses for subsequent clinical trials. METHODS: In this dose-escalation phase I trial, patients with advanced solid tumours received PD-0325901 with crizotinib, using a rolling-6 design to determine the maximum tolerable dose (MTD) and safety/tolerability. Blood samples for pharmacokinetics and skin biopsies were collected. RESULTS: Twenty-five patients',
    'using a rolling-6 design to determine the maximum tolerable dose (MTD) and safety/tolerability. Blood samples for pharmacokinetics and skin biopsies were collected. RESULTS: Twenty-five patients were recruited in 4 cohorts up to doses of crizotinib 200â\x80\x89mg B.D continuously with PD-0325901 8â\x80\x89mg B.D, days 1-21 every 28 days. One in six patients exhibited a dose-limiting toxicity at this dose level. Drug-related adverse events were in keeping with single-agent toxicity profiles. The best']}]]

## all in one

In [8]:
vector_store._client.delete_collection(vector_store._collection.name)

In [9]:
embeddings = OllamaEmbeddings(model="qwen3-embedding")

vector_store = Chroma(
    collection_name="example_collection",
    embedding_function=embeddings,
    collection_metadata={"hnsw:space": "cosine"},
    persist_directory="./chroma_langchain_db",  # Where to save data locally, remove if not necessary
)

text_splitter=RecursiveCharacterTextSplitter(chunk_size=400, 
                                             chunk_overlap=100)

In [192]:
df_p_e

,PMID,Journal,Year,Month,Day,Title,Publication Type,Authors,Abstract,s1,s2,s3
0,41268440,Frontiers in pharmacology,2025,,,Case Report: HGF and NF1 mutations as putative...,"Case Reports, Journal Article","Zhitao Chen, Shan Luo, Yangjun Gu, Qiyong Li",Hepatocellular carcinoma (HCC) is a highly agg...,-1,1,1

In [ ]:
start = time.time()
os.environ["MODEL_NAME"] ='qwen3:8b'

# get main info from .pdf
file_path = "docs/CC_215_L00_DL_fusion_fixed_oncobox_ru.pdf"
fin_condition,treatements_eng,df2 = extract.info_from_doc(file_path)
end = time.time()
print(end - start)

os.environ["MODEL_NAME"] ='qwen3:14b'
for treatement in treatements_eng[:1]:
    
    # ________________Get clinical trials
    print('\nGETTING CLINICAL TRIALS')
    all_studies = extract.get_clinicaltrials(f'''"{fin_condition}"''', 
                                          #' OR '.join(treatements_eng), 
                                           treatement,  
                                          max_studies=500)
    print(all_studies.shape)
    all_text = all_studies.briefTitle.fillna("") + ": " + all_studies.briefSummary.fillna("")
    api = CTScreening()
    end2 = time.time()
    print('getting c.t.:', end2 - end)
    print('\nSCREENING CLINICAL TRIALS')
    ec_pred = api.run(
        population = f"Patients with {fin_condition} undergoing treatment with {treatement}",
        intervention = f"{treatement}",
        comparator = "",
        outcome = "",
        llm = os.getenv("MODEL_NAME"),
        criteria = [f"Does the trial focus on patients with '{fin_condition}'?",
                 f"Does the trial examine the use or sensitivity of '{treatement}' among main treatments?"
               ],
        papers = all_text.values.tolist(), # make for the top-100 for demo
    )
    all_studies[['s1','s2']] = [i.evaluations for i in ec_pred]
    all_studies[['r1','r2']] = [i.rationale for i in ec_pred]
    all_studies.to_csv(f"res_files/ctrials_all_df_{treatement.replace(' ','_')}_{fin_condition.replace(' ','_')}.csv", 
              index=False)
    end3 = time.time()
    print('time:', end3 - end2)
    print('\nEXTR RESULTS FROM CLINICAL TRIALS')
    ctrials_fin = extract.ctrials_res(ec_pred, all_studies)
    chosen_st = all_studies[(all_studies.screen_eval>=0)&(all_studies.hasResults==True)]
    chosen_st['res']= ctrials_fin
    chosen_st.to_csv(f"res_files/ctrials_res_df_{treatement.replace(' ','_')}_{fin_condition.replace(' ','_')}.csv", 
              index=False)
    print(ctrials_fin)
    end4 = time.time()
    print('time:', end4 - end3)
    # ________________Get papers
    print('\nGETTING PAPERS')
    search_api = PubmedAPIWrapper()
        # page_size is the max number of records to return!!!! not pages!
    tmp_inputs = {
            "page_size": 100,
            "keyword_map": {'conditions':[fin_condition], 
                            'treatments':[treatements_eng[0]]
                           },
            "keywords": {
                "OPERATOR": 'AND'
            }
    }
    response = search_api.build_search_query_and_get_pmid(tmp_inputs, 
                                                          api_key=pubmed_api_key)
    print(response[0],len(response[0]), response[1])
    df_papers = pmid2papers(pmid_list=response[0], 
                        api_key=pubmed_api_key)
    papers = df_papers[0]["Title"] + ": " + df_papers[0]["Abstract"].fillna("") # important to fillna
    papers = papers.tolist()
    end5 = time.time()
    print('time:', end5 - end4)
        # screening
    print('\nSCREENING PAPERS')
    api = LiteratureScreening()
    ec_predP = api.run(
        population = f"Patients with {fin_condition} undergoing treatment with {treatements_eng[0]}",
        intervention = f"{treatements_eng[0]}",
        comparator = "",
        outcome = "",
        llm = os.getenv("MODEL_NAME"),
        criteria = [f"Does the study focus on patients/models/cells with '{fin_condition}'?",
                     f"Does the study examine the use/effect/sensitivity of '{treatements_eng[0]}' among main treatments?", 
                    f"Does the study describe the effect of '{treatements_eng[0]}' treatment?"],#title_criteria + content_criteria,
        papers = papers, # make for the top-100 for demo
    )
    
    evalsP = [i.evaluations for i in ec_predP]
    word2int = {"YES": 1, "UNCERTAIN": 0, "NO": -1}
    new_evalsP = []
    for one_e in evalsP:
        new_evalsP.append([word2int.get(item, 0) for item in one_e ])
    new_evalsP = np.array(new_evalsP)  
    df_p_e = df_papers[0]
    df_p_e[['s1','s2','s3']] = new_evalsP
    df_p_e[['r1','r2','r3']] = [i.rationale for i in ec_predP]
    df_p_e.to_csv(f"res_files/papers_all_df_{treatement.replace(' ','_')}_{fin_condition.replace(' ','_')}.csv", 
              index=False)
    chosen_df = df_p_e[(df_p_e['s1']==1)&(df_p_e['s2']==1)&(df_p_e['s3']>=0)]
    print(chosen_df.shape[0])
    end6 = time.time()
    print('time:', end6 - end5)
    # if there are papers left AFTER screening
    if chosen_df.shape[0]:
        # ________________To RAG
            # full texts
        pmid_list = chosen_df.PMID.values.tolist()
        #['41213063',#'26451310',]
        print('\nGETTING FULL TEXT PAPERS')
        res = pmid2fulltext(pmid_list, api_key=pubmed_api_key)
        res = [parse_bioc_xml(r) for r in res]

        # transform the parsed xml into paper content
        papers0 = []
        for parsed in res:
            paper_content = []
            for parsed_ in parsed["passage"]:
                paper_content.append(parsed_['content'])
            paper_content = "\n".join(paper_content)
            papers0.append(paper_content)

        chosen_df['FullText'] = ''
        chosen_df['FullText'] = papers0

        pmid_list = chosen_df.PMID.values.tolist()
        papers_ch = chosen_df.FullText.values
        docs =  [Document(page_content=i, 
                          metadata={"source": j}
                         ) for i,j in zip(papers_ch,pmid_list)]
        end7 = time.time()
        print('time:', end7 - end6)
        print('\nEMBEDDING...')
        all_splits = text_splitter.split_documents(docs)
        document_ids = vector_store.add_documents(documents=all_splits)
        print('\nFIN EMBEDDING')
        end8= time.time()
        print('time:', end8 - end7)

        ii =len(pmid_list) #4
        print('\nEXTR RESULTS FROM PAPERS')
        api = StudyCharacteristicsExtraction()
        res_extracted = api.run(
            papers_inp=[pmid_list[:ii],papers_ch[:ii]],
            #fields=[f'The effectiveness of treating {fin_condition} with {treatements_eng[0]}',
            #       ],
            fields=[f'Crizotinib effectiveness, string, The outcome of treating {fin_condition} with {treatements_eng[0]}'
                   ],
            llm=os.getenv("MODEL_NAME"),
            chunk_size=0,
            chunk_overlap=0,
            thinking=False,
            vector_store = vector_store,
        )
        papers_fin_df = pd.DataFrame([[i.fieldresult[0].value, 
                               i.fieldresult[0].source_id,
                              i.fieldresult[0]._cited_blocks,] for i in res_extracted 
                             ],
                            columns = ['result','idxs','citations'])
        papers_fin_df['id'] = pmid_list
        papers_fin_df.to_csv(f"res_files/papers_res_df_{treatement.replace(' ','_')}_{fin_condition.replace(' ','_')}.csv", 
                             index=False)
        end9 = time.time()
        print('time:', end9 - end8)
        print('\nCOMBINING RESULTS FROM CLINICAL TRIALS')
        rr = extract.combine_res(fin_condition, treatement, 
                             res_extracted, pmid_list)
        end10 = time.time()
        print('time:', end10 - end9)
        print(rr)
        
endf = time.time()
print('time:', endf - start)

C:\Users\105\GitHub\TrialMind-SLR\extract.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df.score.isin(['- ','-',' -']),'score'] = '10.00'
C:\Users\105\GitHub\TrialMind-SLR\extract.py:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.score = df.score.astype(float)

80.76476240158081

GETTING CLINICAL TRIALS
(1, 10)
getting c.t.: 0.5108687877655029

SCREENING CLINICAL TRIALS

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'UNCERTAIN'], rationale=["The trial explicitly mentions 'bowel cancer', which is synonymous with 'Colorectal cancer'.", "The trial mentions the use of two new drugs, but does not specifically mention 'Crizotinib' as one of them. There is no clear information on whether Crizotinib is being examined or used in the trial."])]
time: 63.04219937324524

EXTR RESULTS FROM CLINICAL TRIALS
[ClinicalResult(population=30, time_frame='Dose Expansion phase: change from baseline and up to 12 months.', outcomes=[Outcome(category_name='Stable Disease', outcome=7), Outcome(category_name='Progressive Disease', outcome=22), Outcome(category_name='Early death from malignant disease', outcome=1)])]
time: 79.50150799751282

GETTING PAPERS
['34101765', '26716414', '33414136', '26468446', '26375439', '23719267', '22269210', '38378070', '33895750', '36053834', '33676682', '37418240', '34853656', '31399568', '40526090', '28437395', '32111984', '24695225', '23585220', '23427294', '41268440', '36129915', '27565250', '28886275', '26438251', '37686423', '30863492', '36801912', '36627781', '30412912', '34036227', '26995877', '24583837', '29125233', '40211189', '34230141', '24992173', '28183697', '27325282', '24789362', '29466887', '28465216', '32245659', '32208873', '37773318', '38212428', '36316649', '38711893', '34898475', '28320945', '35343863', '40369167', '22845480', '34766064', '37543570', '23656699', '28654634', '32821654', '41213063', '26939704', '40140597', '30692572', '29803964', '23400546', '26172300', '25139705', '28903995'] 67 https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=(Colorectal cancer)+AND+(Crizotinib)&retmax=100&retmode=json&api_key=6892c4129cef143ff92d11533848d2e0d908
time: 2.585836887359619

SCREENING PAPERS

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=['The study uses LoVo colon cancer cells, which are relevant to colorectal cancer.', 'The study examines the use and effect of Crizotinib on spheroids formed by LoVo cells.', 'The study describes the effect of Crizotinib treatment on mass density and spheroid structure.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'NO', 'UNCERTAIN'], rationale=['The paper discusses Korean patients with colon cancer, which falls under the broader category of colorectal cancer.', 'The study does not mention or examine the use, effect, or sensitivity of Crizotinib.', 'The paper does not describe the effect of Crizotinib treatment, as it focuses on TrkA inhibitors in general without specifying Crizotinib.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'NO', 'UNCERTAIN'], rationale=['The paper explicitly mentions patients with colorectal cancer.', 'The paper does not mention the use or examination of Crizotinib as a treatment.', 'The paper does not describe the effect of Crizotinib treatment.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'UNCERTAIN'], rationale=['The paper mentions colorectal cancer as one of the cancer types affected by ALK rearrangements.', 'The paper discusses the use of Crizotinib as a treatment for ALK-driven tumors, including colorectal cancer.', 'The paper does not provide specific details on the effect of Crizotinib treatment in colorectal cancer patients, only general information on its use in ALK-driven tumors.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'NO', 'UNCERTAIN'], rationale=['The study includes patients with colon cancer, which is a subtype of colorectal cancer.', 'The study does not mention the use or examination of Crizotinib as a treatment.', 'The study does not describe the effect of Crizotinib treatment.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'UNCERTAIN'], rationale=['The paper mentions colorectal cancer as one of the cancer types where ROS1 rearrangements occur.', 'The paper discusses the use of crizotinib as a therapy targeting ROS1 fusion proteins in various cancers, including colorectal cancer.', 'The paper does not provide specific details on the effect of crizotinib treatment in colorectal cancer patients.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=['The study includes Colo205 (colorectal) tumor cells, which are relevant to colorectal cancer.', 'The study examines the use of Crizotinib as a treatment, both as a single agent and in combination with sunitinib.', 'The study describes the effect of Crizotinib treatment, showing that it reduced metastasis in all models tested.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'UNCERTAIN'], rationale=['The study focuses on patients with colorectal cancer.', 'The study examines the correlation between SDHB expression and sensitivity to Crizotinib using PharmacoGx data.', 'The study does not explicitly describe the effect of Crizotinib treatment on patients or cells, only its potential association with drug sensitivity based on gene expression.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['NO', 'YES', 'YES'], rationale=['The paper discusses a patient with an inflammatory myofibroblastic tumor (IMFT), not colorectal cancer.', 'The paper examines the use of crizotinib as part of the treatment regimen.', 'The paper describes the effect of crizotinib treatment in downsizing the tumor and enabling sphincter-sparing surgery.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=['The study focuses on patients with colorectal cancer.', 'The study examines the use of crizotinib as a treatment for a patient with ROS1-rearranged metastatic CRC.', 'The study describes the effect of crizotinib treatment, including a rapid and sustained partial response in the index patient.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'NO', 'UNCERTAIN'], rationale=['The paper explicitly mentions colorectal cancer (CRC) as the focus of the study.', 'The study does not examine the use, effect, or sensitivity of Crizotinib as a treatment; it discusses Crizotinib as a component of a fluorescent probe for imaging purposes.', 'The paper does not describe the effect of Crizotinib treatment on patients or models, but rather its use in a molecular probe.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=["The paper explicitly mentions 'Colorectal cancer (CRC)' as the focus of the study.", 'The study examines the use of Crizotinib as part of a conjugate nanoparticle for cancer treatment.', 'The paper describes the effect of Crizotinib treatment in combination with IR808 and BSA nanoparticles for chemophototherapy.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=['The study focuses on colorectal cancer cell lines (HT29 and HCT116).', 'The study examines the effect of crizotinib on CCL20-dependent proliferation of colorectal cancer cells.', 'The study describes that crizotinib inhibits CCL20-dependent proliferation in colorectal cancer cells.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'UNCERTAIN'], rationale=['The paper mentions that ROS1 gene rearrangement is observed in colorectal cancer, indicating relevance to the population of interest.', 'The paper discusses crizotinib as a treatment for ROS1-rearranged cancers, including its use in clinical settings and its resistance mechanisms.', 'While the paper mentions crizotinib resistance and its limitations, it does not specifically describe the effect of crizotinib treatment in detail, making it uncertain whether the effect is fully described.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'UNCERTAIN'], rationale=['The paper describes a patient with metastatic colorectal cancer.', 'The paper examines the use of Crizotinib as part of the treatment strategy.', 'The paper does not provide sufficient detail on the specific effect of Crizotinib treatment.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['NO', 'YES', 'YES'], rationale=['The study does not focus on patients/models/cells with Colorectal cancer; it is a global survey of small molecules and their immunomodulatory potential, without specific mention of Colorectal cancer.', 'The study examines the effect of Crizotinib, specifically its immunomodulatory properties, which is relevant to its use as a treatment.', 'The study describes the effect of Crizotinib treatment, including its impact on T cell interactions and MSTR1 inhibition.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=['The study focuses on patients with colorectal cancer.', 'The study examines the use of crizotinib as a treatment.', 'The study describes the effect of crizotinib treatment in inhibiting CRC metastasis.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=['The study mentions human colon carcinoma cells, which are relevant to colorectal cancer.', 'The study examines the use and effect of crizotinib, specifically the (S)-enantiomer, on MTH1 activity.', 'The study describes the effect of (S)-crizotinib treatment, including increased DNA single-strand breaks, activation of DNA repair, and suppression of tumor growth.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['NO', 'YES', 'YES'], rationale=["The study does not specify that the patients have Colorectal cancer; it refers to 'male cancer patients' in general.", 'The study examines the use and effect of Crizotinib in male cancer patients, which is relevant to the intervention criterion.', 'The study describes the effect of Crizotinib treatment on testosterone levels and associated symptoms, fulfilling the outcome criterion.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=['The study focuses on colon cancer cells, which are relevant to colorectal cancer.', 'The study examines the use and effect of Crizotinib in colon cancer cells.', 'The study describes the effect of Crizotinib treatment, including its induction of PUMA-dependent apoptosis.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['NO', 'YES', 'YES'], rationale=['The study focuses on hepatocellular carcinoma (HCC), not colorectal cancer.', 'The study examines the use and effect of crizotinib in a patient with MET-amplified HCC.', 'The study describes the effect of crizotinib treatment, including initial tumor regression and subsequent disease progression.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'UNCERTAIN'], rationale=['The study focuses on colorectal cancer, specifically PTPRK-RSPO3 fusion-positive CRC.', 'The study mentions crizotinib as a putative therapeutic candidate based on bioinformatics analysis.', 'The study does not describe the effect of crizotinib treatment in patients or models, only its potential as a therapeutic candidate based on target involvement.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['NO', 'YES', 'YES'], rationale=['The study focuses on patients with metastatic lung cancer and metastatic colon cancer, but the primary focus is on fertility outcomes in cancer survivors, not specifically on patients with colorectal cancer.', 'The study examines the use of crizotinib in a patient with metastatic lung cancer, including its potential impact on fertility and pregnancy.', 'The study describes the effect of crizotinib treatment on fertility outcomes, including its potential impact on oocytes and pregnancy.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=['The study focuses on colorectal cancer (CRC) cell lines and xenograft models.', 'The study examines the use and effect of crizotinib in combination with mitomycin C in CRC cell lines and xenograft models.', 'The study describes the effect of crizotinib treatment, including its synergistic anti-cancer effect when combined with mitomycin C.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'UNCERTAIN'], rationale=['The paper mentions that ROS1 plays a role in colorectal cancer, indicating focus on this population.', 'The paper discusses Crizotinib in the context of ROS1 inhibition, suggesting examination of its use.', 'The paper does not provide specific data or results on the effect of Crizotinib treatment, making it uncertain.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'NO', 'UNCERTAIN'], rationale=['The paper mentions colorectal cancer as one of the cancer types discussed.', 'The paper does not specifically examine the use, effect, or sensitivity of Crizotinib in colorectal cancer or any other cancer type.', 'The paper does not describe the effect of Crizotinib treatment in any detail.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['UNCERTAIN', 'UNCERTAIN', 'UNCERTAIN'], rationale=['The paper title does not specify whether the study focuses on patients, models, or cells with Colorectal cancer.', 'The paper title does not mention whether Crizotinib is examined as a treatment or its use/effect/sensitivity.', 'The paper title does not describe the effect of Crizotinib treatment.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['NO', 'YES', 'YES'], rationale=['The study focuses on BRAF V600E-mutant solid tumors, but explicitly excludes colorectal cancer.', 'The study examines the use of crizotinib in combination with vemurafenib in patients with BRAF V600E-mutant solid tumors.', 'The study describes the effect of crizotinib as part of combination therapies, though no significant improvement in OS or PFS was observed.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'NO', 'UNCERTAIN'], rationale=['The paper mentions colorectal cancer as one of the cancers associated with ALK signaling.', 'The paper does not focus on the use, effect, or sensitivity of Crizotinib as a main treatment in clinical or experimental studies.', 'The paper does not describe the effect of Crizotinib treatment in patients or models, but rather discusses structural aspects of ALK inhibitors in general.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=['The study focuses on colorectal cancer cell lines (HCT116, DLD1, LoVo) and discusses KRAS mutant colorectal tumors.', 'The study examines the use and effect of crizotinib in cetuximab-resistant, KRAS mutant colorectal cancer cell lines.', 'The study describes the effect of crizotinib treatment, including radiosensitization, inhibition of c-Met signaling, and effects on cell migration and survival.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=["The paper discusses a patient with metastatic colorectal carcinoma, fulfilling the 'Colorectal cancer' criterion.", 'The paper examines the use of Crizotinib as a treatment in a patient with colorectal cancer and ALK gene rearrangement.', 'The paper describes the clinical response to Crizotinib treatment in the patient.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'NO', 'UNCERTAIN'], rationale=['The paper mentions colorectal cancer in the context of companion diagnostics for cetuximab and panitumumab.', 'The paper does not examine the use, effect, or sensitivity of crizotinib as a main treatment.', 'The paper does not describe the effect of crizotinib treatment.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['NO', 'YES', 'YES'], rationale=['The paper discusses a case of inflammatory myofibroblastic tumor (IMT) in a patient with ALK fusion, not colorectal cancer.', "The paper examines the use of crizotinib as treatment for the patient's IMT.", 'The paper describes the effect of crizotinib treatment, noting that the disease was stable after 4 months of treatment according to RECIST criteria.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=['The paper mentions KM12SM colorectal cancer cells, which directly relates to colorectal cancer.', 'The study examines the effect of crizotinib on NUGC4 gastric cancer cells and KM12SM colorectal cancer cells, indicating its use in the study.', 'The paper describes the effect of crizotinib treatment on delaying the progression of brain tumors in NUGC4 models and liver metastases in KM12SM models.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=['The study explicitly focuses on patients with RAS mutant advanced colorectal cancer.', 'The study examines the use of Crizotinib in combination with binimetinib as part of the treatment regimen.', 'The study describes the effect of Crizotinib treatment, including adverse events, pharmacokinetic parameters, and clinical outcomes such as stable disease.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['NO', 'NO', 'NO'], rationale=["The study does not mention 'Colorectal cancer'; it discusses general cancer stem cell properties and the interaction between c-Met and PrP.", "The study does not mention 'Crizotinib' or its use as a treatment.", "The study does not describe the effect of 'Crizotinib' treatment."])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'NO', 'UNCERTAIN'], rationale=['The study focuses on colorectal adenocarcinoma, which is a type of colorectal cancer.', 'The study does not examine the use, effect, or sensitivity of Crizotinib as a treatment; it only discusses its potential relevance based on ALK/ROS1 expression.', 'The study does not describe the effect of Crizotinib treatment on patients with colorectal cancer.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['NO', 'NO', 'NO'], rationale=['The study does not focus on patients with Colorectal cancer.', 'The study examines the use of Entrectinib, not Crizotinib.', 'The study does not describe the effect of Crizotinib treatment.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=["The paper explicitly mentions patients with BRAF-mutated colorectal cancer, satisfying the criterion related to 'Colorectal cancer'.", "The paper discusses the use of crizotinib as part of the treatment strategy (dual ALK-MET inhibitor crizotinib plus vemurafenib), satisfying the criterion related to 'Crizotinib' among main treatments.", "The paper describes the effect of crizotinib treatment in overcoming resistance and achieving clinical benefit, satisfying the criterion related to the effect of 'Crizotinib' treatment."])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'UNCERTAIN'], rationale=['The paper mentions colorectal cancer in the context of targeted therapies.', 'The paper explicitly mentions crizotinib in the list of tyrosine kinase inhibitors used in various cancers.', 'The paper does not provide specific details on the effect of crizotinib treatment in colorectal cancer.'])]

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'NO'], rationale=['The paper discusses colorectal cancer as one of the cancer types reviewed.', 'The paper mentions crizotinib as one of the innovative treatments not reimbursed under certain schemes.', 'The paper does not describe the effect of crizotinib treatment, only its reimbursement status.'])]


C:\Users\105\AppData\Local\Temp\ipykernel_3740\3670082012.py:122: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chosen_df['FullText'] = ''
C:\Users\105\AppData\Local\Temp\ipykernel_3740\3670082012.py:123: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chosen_df['FullText'] = papers0

time: 30.896138906478882

EMBEDDING...

In [ ]:
2

In [ ]:

#for treatement in treatements_eng[1:6]:
    end = time.time()
    # ________________Get clinical trials
    print('\nGETTING CLINICAL TRIALS')
    all_studies = extract.get_clinicaltrials(f'''"{fin_condition}"''', 
                                          #' OR '.join(treatements_eng), 
                                           treatement,  
                                          max_studies=200)
    print(all_studies.shape)
    all_text = all_studies.briefTitle.fillna("") + ": " + all_studies.briefSummary.fillna("")
    api = CTScreening()
    end2 = time.time()
    print('getting c.t.:', end2 - end)
    print('\nSCREENING CLINICAL TRIALS')
    ec_pred = api.run(
        population = f"Patients with {fin_condition} undergoing treatment with {treatement}",
        intervention = f"{treatement}",
        comparator = "",
        outcome = "",
        llm = os.getenv("MODEL_NAME"),
        criteria = [f"Does the trial focus on patients with '{fin_condition}'?",
                 f"Does the trial examine the use or sensitivity of '{treatement}' among main treatments?"
               ],
        papers = all_text.values.tolist(), # make for the top-100 for demo
    )
    all_studies[['s1','s2']] = [i.evaluations for i in ec_pred]
    all_studies[['r1','r2']] = [i.rationale for i in ec_pred]
    all_studies.to_csv(f"res_files/ctrials_all_df_{treatement.replace(' ','_')}_{fin_condition.replace(' ','_')}.csv", 
              index=False)
    end3 = time.time()
    print('time:', end3 - end2)
    print('\nEXTR RESULTS FROM CLINICAL TRIALS')
    ctrials_fin = extract.ctrials_res(ec_pred, all_studies)
    chosen_st = all_studies[(all_studies.screen_eval>=0)&(all_studies.hasResults==True)]
    chosen_st['res']= ctrials_fin
    chosen_st.to_csv(f"res_files/ctrials_res_df_{treatement.replace(' ','_')}_{fin_condition.replace(' ','_')}.csv", 
              index=False)
    print(ctrials_fin)
    end4 = time.time()
    print('time:', end4 - end3)
    # ________________Get papers
    print('\nGETTING PAPERS')
    search_api = PubmedAPIWrapper()
        # page_size is the max number of records to return!!!! not pages!
    tmp_inputs = {
            "page_size": 100,
            "keyword_map": {'conditions':[fin_condition], 
                            'treatments':[treatement]
                           },
            "keywords": {
                "OPERATOR": 'AND'
            }
    }
    response = search_api.build_search_query_and_get_pmid(tmp_inputs, 
                                                          api_key=pubmed_api_key)
    print(response[0],len(response[0]), response[1])
    df_papers = pmid2papers(pmid_list=response[0], 
                        api_key=pubmed_api_key)
    papers = df_papers[0]["Title"] + ": " + df_papers[0]["Abstract"].fillna("") # important to fillna
    papers = papers.tolist()
    end5 = time.time()
    print('time:', end5 - end4)
        # screening
    print('\nSCREENING PAPERS')
    api = LiteratureScreening()
    ec_predP = api.run(
        population = f"Patients with {fin_condition} undergoing treatment with {treatement}",
        intervention = f"{treatement}",
        comparator = "",
        outcome = "",
        llm = os.getenv("MODEL_NAME"),
        criteria = [f"Does the study focus on patients/models/cells with '{fin_condition}'?",
                     f"Does the study examine the use/effect/sensitivity of '{treatement}' among main treatments?", 
                    f"Does the study describe the effect of '{treatement}' treatment?"],#title_criteria + content_criteria,
        papers = papers, # make for the top-100 for demo
    )
    
    evalsP = [i.evaluations for i in ec_predP]
    word2int = {"YES": 1, "UNCERTAIN": 0, "NO": -1}
    new_evalsP = []
    for one_e in evalsP:
        new_evalsP.append([word2int.get(item, 0) for item in one_e ])
    new_evalsP = np.array(new_evalsP)  
    df_p_e = df_papers[0]
    df_p_e[['s1','s2','s3']] = new_evalsP
    df_p_e[['r1','r2','r3']] = [i.rationale for i in ec_predP]
    df_p_e.to_csv(f"res_files/papers_all_df_{treatement.replace(' ','_')}_{fin_condition.replace(' ','_')}.csv", 
              index=False)
    chosen_df = df_p_e[(df_p_e['s1']==1)&(df_p_e['s2']==1)&(df_p_e['s3']>=0)]
    print(chosen_df.shape[0])
    end6 = time.time()
    print('time:', end6 - end5)
    # if there are papers left AFTER screening
    if chosen_df.shape[0]:
        # ________________To RAG
            # full texts
        pmid_list = chosen_df.PMID.values.tolist()
        #['41213063',#'26451310',]
        print('\nGETTING FULL TEXT PAPERS')
        res = pmid2fulltext(pmid_list, api_key=pubmed_api_key)
        res = [parse_bioc_xml(r) for r in res]

        # transform the parsed xml into paper content
        papers0 = []
        for parsed in res:
            paper_content = []
            for parsed_ in parsed["passage"]:
                paper_content.append(parsed_['content'])
            paper_content = "\n".join(paper_content)
            papers0.append(paper_content)

        chosen_df['FullText'] = ''
        chosen_df['FullText'] = papers0

        pmid_list = chosen_df.PMID.values.tolist()
        papers_ch = chosen_df.FullText.values
        docs =  [Document(page_content=i, 
                          metadata={"source": j}
                         ) for i,j in zip(papers_ch,pmid_list)]
        end7 = time.time()
        print('time:', end7 - end6)
        print('\nEMBEDDING...')
        all_splits = text_splitter.split_documents(docs)
        document_ids = vector_store.add_documents(documents=all_splits)
        print('\nFIN EMBEDDING')
        end8= time.time()
        print('time:', end8 - end7)

        ii =len(pmid_list) #4
        print('\nEXTR RESULTS FROM PAPERS')
        api = StudyCharacteristicsExtraction()
        res_extracted = api.run(
            papers_inp=[pmid_list[:ii],papers_ch[:ii]],
            #fields=[f'The effectiveness of treating {fin_condition} with {treatements_eng[0]}',
            #       ],
            fields=[f'{treatement} effectiveness, string, The outcome of treating {fin_condition} with {treatement}'
                   ],
            llm=os.getenv("MODEL_NAME"),
            chunk_size=0,
            chunk_overlap=0,
            thinking=False,
            vector_store = vector_store,
        )
        papers_fin_df = pd.DataFrame([[i.fieldresult[0].value, 
                               i.fieldresult[0].source_id,
                              i.fieldresult[0]._cited_blocks,] for i in res_extracted 
                             ],
                            columns = ['result','idxs','citations'])
        papers_fin_df['id'] = pmid_list
        papers_fin_df.to_csv(f"res_files/papers_res_df_{treatement.replace(' ','_')}_{fin_condition.replace(' ','_')}.csv", 
                             index=False)
        end9 = time.time()
        print('time:', end9 - end8)
        print('\nCOMBINING RESULTS FROM CLINICAL TRIALS')
        rr = extract.combine_res(fin_condition, treatement, 
                             res_extracted, pmid_list)
        end10 = time.time()
        print('time:', end10 - end9)
        print(rr)
        
endf = time.time()
print('time:', endf - start)

In [ ]:
1

In [ ]:
endf = time.time()
print('time:', endf - start)

In [301]:
kk

'Crizotinib selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models [40369167]. Crizotinib achieved a partial response with progression-free survival of 3 months in a metastatic colorectal carcinoma patient with ALK gene rearrangement [34036227]. Crizotinib restored cetuximab sensitivity in SC [28320945]. (S)-crizotinib induces massive cell death in CRC spheroids and inhibits c-MET and ErbB3 [30692572]. EpAb2-6 improves the efficacy of crizotinib therapy in a colon cancer animal model [37543570]. Crizotinib effectively sensitizes cetuximab-resistant KRAS mutant colorectal cancer cell lines to radiation [30412912]. Crizotinib plus vemurafenib showed rapid and marked effectiveness in treating BRAF-mutated colorectal cancer [27325282]. Molecularly targeted treatment with crizotinib induced a rapid and sustained partial response [36053834]. The combination of crizotinib with MMC showed a synergistic anti-cancer effect (CI = 0.006-0.74) and reduced tumor growth (p = 0.0088) in CRC xenograft models [28886275]. Crizotinib showed a median PFS of 10.9 months and an ORR of 74% in treating colorectal cancer [37686423].'

In [347]:
import markdown as md

layers = [1,2,3]
lr = 2
dir = 'result'

with open('check.md', 'wb') as f:
    f.write('## Layer sizes\n'.encode())

    for layer in layers:
        f.write(f'* {layer}\n'.encode())

    f.write(f'## Learning rate is {lr}\n'.encode())
    f.write('## Init\n'.encode())
    f.write('Add note about init\n'.encode())
#md.markdownFromFile(input=open("check.md", "rb"), output=open("out.html", "wb"))

In [312]:
ctrials_fin

[ClinicalResult(population=30, time_frame='Dose Expansion phase: change from baseline and up to 12 months.', outcomes=[Outcome(category_name='Stable Disease', outcome=7), Outcome(category_name='Progressive Disease', outcome=22), Outcome(category_name='Early death from malignant disease', outcome=1)])]

In [313]:
chosen_st

,hasResults,nctId,briefTitle,overallStatus,briefSummary,conditions,studyType,phases,interventions,outcomeMeasures,screen_eval,r1,r2,s1,s2,res
0,True,NCT02510001,MEK and MET Inhibition in Colorectal Cancer,COMPLETED,This trial is designed to try two new cancer d...,"[Solid Tumor, Colorectal Cancer]",INTERVENTIONAL,[PHASE1],"[pf-02341066, pd-0325901, binimetinib]","[{'type': 'PRIMARY', 'title': 'Maximal Tolerat...",1,"The trial explicitly mentions 'bowel cancer', ...",The trial mentions 'Crizotinib' in the context...,YES,UNCERTAIN,population=30 time_frame='Dose Expansion phase...

In [559]:

ids_ct = to_work#all_studies[(all_studies.screen_eval>=0)&(all_studies.hasResults)]#.nctId.values
ids_p = df_papers[0][df_papers[0].screen_eval>=total_ev]#.PMID.values

In [302]:
import itertools
a = [i['value'] for i in gg[:,0] if i['value']!='NP' ]
#list(itertools.chain.from_iterable(a))
len(' '.join(a))

1344

In [321]:
papers_fin_df

,result,idxs,citations,id
0,Crizotinib selectively inhibited the growth of...,"[6, 7, 8]",[colorectal cancer (CRC) cells induce syntheti...,40369167
1,Crizotinib achieved a partial response with pr...,"[1, 2, 5]","[In conclusion, we have reported on an elderly...",34036227
2,NP,[],[],35343863
3,Crizotinib restored cetuximab sensitivity in SC.,[1],"[monoclonal antibody, cetuximab, strongly inhi...",28320945
4,NP,[],[],38212428
5,Limited activity in unselected heavily pre-tre...,"[2, 3, 8]","[In summary, inhibition of the MEK1/2 and c-ME...",40140597
6,NP,[],[],31399568
7,(S)-crizotinib induces massive cell death in C...,"[0, 7]",[(S)-crizotinib inhibits c-MET and ErbB3 in hu...,30692572
8,EpAb2-6 improves the efficacy of crizotinib th...,"[0, 1, 4]",[EpAb2-6 improves the efficacy of crizotinib t...,37543570
9,Crizotinib effectively sensitizes cetuximab-re...,[5],[crizotinib completely blocked HGF induced cel...,30412912
10,Crizotinib plus vemurafenib showed rapid and m...,[4],"[functional in vitro data, the patient was tre...",27325282
11,Molecularly targeted treatment with crizotinib...,"[3, 6]",[were found exclusively in microsatellite stab...,36053834
12,NP,[],[],36316649
13,Crizotinib combined with regorafenib and tisle...,"[6, 7, 8]",[This study reported a co-existence of a BRAF ...,38711893
14,ORR was 50% with one complete response in the,"[0, 1]",[those with ALK mutation or amplifications. Re...,37773318
15,The study assessed safety and initial efficacy...,[9],[study assessed safety and initial efficacy of...,40211189
16,The combination of crizotinib with MMC showed ...,"[1, 4]",[especially in MSI-H CRC. The combination of c...,28886275
17,Crizotinib (CZB) impacts LoVo spheroids morpho...,[7],"[In this study, the LoVo colon cancer cell lin...",34101765
18,NP,[],[],41213063
19,Crizotinib showed a median PFS of 10.9 months ...,[2],[the median PFS (10.9 months with crizotinib v...,37686423

In [330]:
print(f'Condition: {fin_condition} \n\nTreatement 1: {treatements_eng[0]}')
print(f'\nChosen clinical trials:')
for idx, name, ctres in zip(chosen_st.nctId, chosen_st.briefTitle, chosen_st.res):
    print('- https://clinicaltrials.gov/study/'+idx+' '+f"'{name}'")
    print(ctres)
print(f'\nChosen Papers:')
for i, ext_res in zip(papers_fin_df.id, papers_fin_df.result):
    print('- https://pubmed.ncbi.nlm.nih.gov/'+i+' '+f"'{1}'")
    if ext_res != 'NP':
        print(ext_res)

Condition: Colorectal cancer

Treatement 1: Crizotinib

Chosen clinical trials:
- https://clinicaltrials.gov/study/NCT02510001 'MEK and MET Inhibition in Colorectal Cancer'
population=30 time_frame='Dose Expansion phase: change from baseline and up to 12 months.' outcomes=[Outcome(category_name='Stable Disease', outcome=7), Outcome(category_name='Progressive Disease', outcome=22), Outcome(category_name='Early death from malignant disease', outcome=1)]

Chosen Papers:
- https://pubmed.ncbi.nlm.nih.gov/40369167 '1'
Crizotinib selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models.
- https://pubmed.ncbi.nlm.nih.gov/34036227 '1'
Crizotinib achieved a partial response with progression-free survival of 3 months in a metastatic colorectal carcinoma patient with ALK gene rearrangement.
- https://pubmed.ncbi.nlm.nih.gov/35343863 '1'
- https://pubmed.ncbi.nlm.nih.gov/28320945 '1'
Crizotinib restored cetuximab sensitivity in SC.
- https://pubmed.ncbi.nlm.nih.gov/38212428 '1'
- https://pubmed.ncbi.nlm.nih.gov/40140597 '1'
Limited activity in unselected heavily pre-treated patients with advanced solid tumours.
- https://pubmed.ncbi.nlm.nih.gov/31399568 '1'
- https://pubmed.ncbi.nlm.nih.gov/30692572 '1'
(S)-crizotinib induces massive cell death in CRC spheroids and inhibits c-MET and ErbB3.
- https://pubmed.ncbi.nlm.nih.gov/37543570 '1'
EpAb2-6 improves the efficacy of crizotinib therapy in a colon cancer animal model
- https://pubmed.ncbi.nlm.nih.gov/30412912 '1'
Crizotinib effectively sensitizes cetuximab-resistant KRAS mutant colorectal cancer cell lines to radiation.
- https://pubmed.ncbi.nlm.nih.gov/27325282 '1'
Crizotinib plus vemurafenib showed rapid and marked effectiveness in treating BRAF-mutated colorectal cancer.
- https://pubmed.ncbi.nlm.nih.gov/36053834 '1'
Molecularly targeted treatment with crizotinib induced a rapid and sustained partial response.
- https://pubmed.ncbi.nlm.nih.gov/36316649 '1'
- https://pubmed.ncbi.nlm.nih.gov/38711893 '1'
Crizotinib combined with regorafenib and tislelizumab obtained an obvious response in a CRC patient with BRAF V600E mutation, c-MET amplification, and TPM4-ALK fusion.
- https://pubmed.ncbi.nlm.nih.gov/37773318 '1'
ORR was 50% with one complete response in the
- https://pubmed.ncbi.nlm.nih.gov/40211189 '1'
The study assessed safety and initial efficacy of crizotinib in treating RAS mutant advanced colorectal cancer patients.
- https://pubmed.ncbi.nlm.nih.gov/28886275 '1'
The combination of crizotinib with MMC showed a synergistic anti-cancer effect (CI = 0.006-0.74) and reduced tumor growth (p = 0.0088) in CRC xenograft models.
- https://pubmed.ncbi.nlm.nih.gov/34101765 '1'
Crizotinib (CZB) impacts LoVo spheroids morphology.
- https://pubmed.ncbi.nlm.nih.gov/41213063 '1'
- https://pubmed.ncbi.nlm.nih.gov/37686423 '1'
Crizotinib showed a median PFS of 10.9 months and an ORR of 74% in treating colorectal cancer.

In [336]:
import random

from pdfme import build_pdf


random.seed(1)

def clin():
    func_r = []
    num = 1
    for i, ext_res in zip(ids_ct.values,json_resultsct):
        func_r.append([f"{num}. '{i[2]}'", 
                       f" {i[3].lower()}", 
                       f" {' '.join(i[7]).lower()}",
                       {".": " (link)", "style": "url", 
                            "uri": f'https://clinicaltrials.gov/study/{i[1]}'}, 
                      ])
        #func_r.append(['- https://clinicaltrials.gov/study/'+i[1]+' '+f"'{i[2]}'"])
        #func_r.append([ext_res])
        '''
        for j_n, j in enumerate(ext_res):
            func_r_1 = []
            func_r_1 = func_r_1+ ['Measure: ', i[-1][j_n]['title'], '\n',
                          {".s:8;i": f"Population: {j['population']}"}, '\n',
                          {".s:8;i": f"Time: {j['time_frame']}"}, '\n',
                          ]
            for out in j['outcomes']:
                func_r_1 = func_r_1+ [{".s:8;i": out['category_name']},
                                ': ',
                               {".s:8;i": out['outcome']}, '\n',
                              ]
            func_r.append(func_r_1)
        '''
        num+=1
    return func_r

def papers():
    func_r = []
    num = 1
    for i, ext_res in zip(ids_p.values, extracted_gm):
        func_r.append([f"{num}. '{i[5]}'", 
                       {".": f" (link)", "style": "url", 
                            "uri": f'https://pubmed.ncbi.nlm.nih.gov/{i[0]}'}, 
                      ])
        if ext_res[0]['source_id']:
            func_r.append([f"    {ext_res[0]['name'].replace('_',' ')}: '{ext_res[0]['value']}'"+
                          " Based on:"])
            for cb in ext_res[0]['cited_blocks']: 
                func_r.append([{".s:8;i":f"'{cb}'"}])
            #func_r.append(field['cited_blocks'])
        num+=1
    return func_r


document = {
    "style": {
        "margin_bottom": 15, "text_align": "j",
        "page_size": "letter", "margin": [60, 50]
    },
    "formats": {
        "url": {"c": "blue", "u": 1},
        "title": {"b": 1, "s": 13}
    },
    "running_sections": {
        "header": {
            "x": "left", "y": 20, "height": "top", "style": {"text_align": "r"},
            "content": [{".b": "This is a header"}]
        },
        "footer": {
            "x": "left", "y": 740, "height": "bottom", "style": {"text_align": "c"},
            "content": [{".": ["Page ", {"var": "$page"}]}]
        }
    },
    "sections": [
        {
            "style": {"page_numbering_style": "arabic"},
            "running_sections": ["footer"],
            "content": [

                {
                    ".": f"Condition: {fin_condition}", "style": "title", "label": "title1",
                },
                [{".b": f'Treatement 1: {treatements_eng[0]}'}],
                [{".b": 'Chosen clinical trials:'}],
                
                #*clin(),
                
                [{".b": 'Chosen papers:'}],
                [f'Short summary: {123}'],
                #*papers(),
                
                #{"image": "path/to/some/image.jpg"},

                
            ]
        }
    ]
}
#res_files/{treatement.replace(' ','_')}_{fin_condition.replace(' ','_')}
with open(f"j.pdf", 'wb') as f:
    build_pdf(document, f)

SyntaxError: f-string expression part cannot include a backslash (fonts.py, line 71)