In [1]:
from openai import OpenAI
import httpx
from langchain_core.documents import Document
from langchain_chroma import Chroma
from langchain_ollama import OllamaEmbeddings
import os
import numpy as np
import pandas as pd
from ollama import Client
from langchain_text_splitters import RecursiveCharacterTextSplitter

os.environ["BASE_URL"] = "http://localhost:11434/v1"
os.environ["MODEL_NAME"] ='kamekichi128/qwen3-4b-instruct-2507'
os.environ["OPENAI_API_KEY"] = 'hey'

from trialmind.pubmed import pmid2papers, PubmedAPIWrapper, pmid2biocxml, parse_bioc_xml
from trialmind.api import StudyCharacteristicsExtraction, ScreeningCriteriaGeneration,\
                            LiteratureScreening, ScreeningCriteriaCTGeneration,\
                            CTScreening
from trialmind.retrievers import split_text_into_chunks
import extract

%load_ext autoreload
%autoreload 2

In [2]:
import markdown as md

layers = [1,2,3]
lr = 2
dir = 'result'

with open('check.md', 'wb') as f:
    f.write('## Layer sizes\n'.encode())

    for layer in layers:
        f.write(f'* {layer}\n'.encode())

    f.write(f'## Learning rate is {lr}\n'.encode())
    f.write('## Init\n'.encode())
    f.write('Add note about init\n'.encode())
#md.markdownFromFile(input=open("check.md", "rb"), output=open("out.html", "wb"))

In [73]:
import pandas as pd
papers = pd.read_csv('res_files/papers_all_df_Crizotinib_Colorectal_cancer.csv')
trials = pd.read_csv('res_files/ctrials_res_df_Crizotinib_Colorectal_cancer.csv')

In [74]:
papers

,PMID,Journal,Year,Month,Day,Title,Publication Type,Authors,Abstract,s1,s2,s3,r1,r2,r3
0,41268440,Frontiers in pharmacology,2025,NaN,NaN,Case Report: HGF and NF1 mutations as putative...,"Case Reports, Journal Article","Zhitao Chen, Shan Luo, Yangjun Gu, Qiyong Li",Hepatocellular carcinoma (HCC) is a highly agg...,-1,1,1,The study focuses on hepatocellular carcinoma ...,The study examines the use and effect of crizo...,The study describes the effect of crizotinib t...
1,40526090,Oncotarget,2025,Jun,17.0,Case Report WIN-MTB-2023001 WIN International ...,"Journal Article, Case Reports","Alberto Hernando-Calvo, Razelle Kurzrock, Nadi...",Heavily pretreated metastatic colorectal cance...,1,1,0,The paper describes a patient with metastatic ...,The paper examines the use of Crizotinib as pa...,The paper does not provide sufficient detail o...
2,41213063,"Journal of environmental pathology, toxicology...",2025,NaN,NaN,Radiotherapy-Related Autophagy Genes Predict P...,Journal Article,"Mao Mao, Yichao Zhuang, Yan Chen",Numerous genes have been associated with color...,1,1,0,The study focuses on patients with colorectal ...,The study examines the sensitivity of Crizotin...,The study does not explicitly describe the eff...

In [60]:
papers[papers.PMID==412689440].Title.values[0]

IndexError: index 0 is out of bounds for axis 0 with size 0

In [65]:
pmid_list = [99,88,77,66,55,44,33,22,11,0,12,13,14]
import re
class hhey:
    def __init__(self):
        
        self.dict_h = {}
        self.h = -1
    def replacement_match(self,match):
        found_id = match.groups()[0]
        self.h+=1
        print(self.h)
        try:
            print(found_id, papers[papers.PMID==int(found_id)].Title.values[0])
            self.dict_h[h]=papers[papers.PMID==int(found_id)].Title.values[0]
        except IndexError:
            pass
        return f'[{self.h}]'

In [66]:
k.dict_h

{}

In [67]:
k = hhey()

In [68]:
re.sub(r'\[(\d+)\]', k.replacement_match, kk)

0
1
2
3
4
5
6
7
8
9

'Crizotinib selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models [0]. Crizotinib achieved a partial response with progression-free survival of 3 months in a metastatic colorectal carcinoma patient with ALK gene rearrangement [1]. Crizotinib restored cetuximab sensitivity in SC [2]. (S)-crizotinib induces massive cell death in CRC spheroids and inhibits c-MET and ErbB3 [3]. EpAb2-6 improves the efficacy of crizotinib therapy in a colon cancer animal model [4]. Crizotinib effectively sensitizes cetuximab-resistant KRAS mutant colorectal cancer cell lines to radiation [5]. Crizotinib plus vemurafenib showed rapid and marked effectiveness in treating BRAF-mutated colorectal cancer [6]. Molecularly targeted treatment with crizotinib induced a rapid and sustained partial response [7]. The combination of crizotinib with MMC showed a synergistic anti-cancer effect (CI = 0.006-0.74) and reduced tumor growth (p = 0.0088) in CRC xenograft models [8]. Crizotinib showed a median PFS of 10.9 months and an ORR of 74% in treating colorectal cancer [9].'

In [70]:
k.h

9

In [72]:
for i in range(k.h):
    print(f'[{i}]', k.dict_h[i])

KeyError: 0

In [69]:
k.dict_h

{}

In [32]:
re.findall(r'\[\d+\]',kk)

['[40369167]',
 '[34036227]',
 '[28320945]',
 '[30692572]',
 '[37543570]',
 '[30412912]',
 '[27325282]',
 '[36053834]',
 '[28886275]',
 '[37686423]']

In [100]:
from markdown_pdf import MarkdownPdf

pdf = MarkdownPdf(toc_level=4, optimize=True)
from markdown_pdf import Section

fin_condition = 'Colorectal cancer'
treatements_eng = ['Crizotinib','']

section = Section("# Title\n", toc=False)

kk = 'Crizotinib selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models [40369167]. Crizotinib achieved a partial response with progression-free survival of 3 months in a metastatic colorectal carcinoma patient with ALK gene rearrangement [34036227]. Crizotinib restored cetuximab sensitivity in SC [28320945]. (S)-crizotinib induces massive cell death in CRC spheroids and inhibits c-MET and ErbB3 [30692572]. EpAb2-6 improves the efficacy of crizotinib therapy in a colon cancer animal model [37543570]. Crizotinib effectively sensitizes cetuximab-resistant KRAS mutant colorectal cancer cell lines to radiation [30412912]. Crizotinib plus vemurafenib showed rapid and marked effectiveness in treating BRAF-mutated colorectal cancer [27325282]. Molecularly targeted treatment with crizotinib induced a rapid and sustained partial response [36053834]. The combination of crizotinib with MMC showed a synergistic anti-cancer effect (CI = 0.006-0.74) and reduced tumor growth (p = 0.0088) in CRC xenograft models [28886275]. Crizotinib showed a median PFS of 10.9 months and an ORR of 74% in treating colorectal cancer [37686423].'

text = """# Section with links

- [External link](https://github.com/vb64/markdown-pdf)
"""


k = hhey()
add_summ = re.sub(r'\[(\d+)\]', k.replacement_match, kk)

text2 = f"""# Condition: {fin_condition}

## Treatement 1: {treatements_eng[0]}

### Chosen clinical trials:
                         
{trials.res.values[0]}
                            
### Papers:

{add_summ}

"""

lit_list = '\n\n'.join([f"[{i}]  {k.dict_h.get(i, 'hh')}" for i in range(k.h+1)])
text2 = text2+lit_list

pdf.add_section(Section(text2))

pdf.save("test.pdf")

0
1
2
3
4
5
6
7
8
9

In [78]:
trials.res.values[0]

"population=30 time_frame='Dose Expansion phase: change from baseline and up to 12 months.' outcomes=[Outcome(category_name='Stable Disease', outcome=7), Outcome(category_name='Progressive Disease', outcome=22), Outcome(category_name='Early death from malignant disease', outcome=1)]3"

In [90]:
'\n'.join([f"[{i}]  {k.dict_h.get(i, 'hh')}" for i in range(k.h)])

'[0]  hh\n[1]  hh\n[2]  hh\n[3]  hh\n[4]  hh\n[5]  hh\n[6]  hh\n[7]  hh\n[8]  hh'

In [ ]:
import random

from pdfme import build_pdf


random.seed(1)

def clin():
    func_r = []
    num = 1
    for i, ext_res in zip(ids_ct.values,json_resultsct):
        func_r.append([f"{num}. '{i[2]}'", 
                       f" {i[3].lower()}", 
                       f" {' '.join(i[7]).lower()}",
                       {".": " (link)", "style": "url", 
                            "uri": f'https://clinicaltrials.gov/study/{i[1]}'}, 
                      ])
        #func_r.append(['- https://clinicaltrials.gov/study/'+i[1]+' '+f"'{i[2]}'"])
        #func_r.append([ext_res])
        '''
        for j_n, j in enumerate(ext_res):
            func_r_1 = []
            func_r_1 = func_r_1+ ['Measure: ', i[-1][j_n]['title'], '\n',
                          {".s:8;i": f"Population: {j['population']}"}, '\n',
                          {".s:8;i": f"Time: {j['time_frame']}"}, '\n',
                          ]
            for out in j['outcomes']:
                func_r_1 = func_r_1+ [{".s:8;i": out['category_name']},
                                ': ',
                               {".s:8;i": out['outcome']}, '\n',
                              ]
            func_r.append(func_r_1)
        '''
        num+=1
    return func_r

def papers():
    func_r = []
    num = 1
    for i, ext_res in zip(ids_p.values, extracted_gm):
        func_r.append([f"{num}. '{i[5]}'", 
                       {".": f" (link)", "style": "url", 
                            "uri": f'https://pubmed.ncbi.nlm.nih.gov/{i[0]}'}, 
                      ])
        if ext_res[0]['source_id']:
            func_r.append([f"    {ext_res[0]['name'].replace('_',' ')}: '{ext_res[0]['value']}'"+
                          " Based on:"])
            for cb in ext_res[0]['cited_blocks']: 
                func_r.append([{".s:8;i":f"'{cb}'"}])
            #func_r.append(field['cited_blocks'])
        num+=1
    return func_r


document = {
    "style": {
        "margin_bottom": 15, "text_align": "j",
        "page_size": "letter", "margin": [60, 50]
    },
    "formats": {
        "url": {"c": "blue", "u": 1},
        "title": {"b": 1, "s": 13}
    },
    "running_sections": {
        "header": {
            "x": "left", "y": 20, "height": "top", "style": {"text_align": "r"},
            "content": [{".b": "This is a header"}]
        },
        "footer": {
            "x": "left", "y": 740, "height": "bottom", "style": {"text_align": "c"},
            "content": [{".": ["Page ", {"var": "$page"}]}]
        }
    },
    "sections": [
        {
            "style": {"page_numbering_style": "arabic"},
            "running_sections": ["footer"],
            "content": [

                {
                    ".": f"Condition: {fin_condition}", "style": "title", "label": "title1",
                },
                [{".b": f'Treatement 1: {treatements_eng[0]}'}],
                [{".b": 'Chosen clinical trials:'}],
                
                #*clin(),
                
                [{".b": 'Chosen papers:'}],
                [f'Short summary: {123}'],
                #*papers(),
                
                #{"image": "path/to/some/image.jpg"},

                
            ]
        }
    ]
}
#res_files/{treatement.replace(' ','_')}_{fin_condition.replace(' ','_')}
with open(f"j.pdf", 'wb') as f:
    build_pdf(document, f)

In [3]:
!pip install markdown-pdf

Collecting markdown-pdf
  Downloading markdown_pdf-1.13.1-py3-none-any.whl.metadata (8.4 kB)
Collecting PyMuPDF>=1.25.3 (from markdown-pdf)
  Downloading pymupdf-1.27.1-cp310-abi3-win_amd64.whl.metadata (3.4 kB)
Collecting markdown-it-py==3.0.0 (from markdown-pdf)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: requests>=2.32.5 in D:\Programs\Anaconda\envs\olm\Lib\site-packages (from markdown-pdf) (2.32.5)
Collecting plantuml==0.3.0 (from markdown-pdf)
  Downloading plantuml-0.3.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: six==1.17.0 in D:\Programs\Anaconda\envs\olm\Lib\site-packages (from markdown-pdf) (1.17.0)
Requirement already satisfied: mdurl~=0.1 in D:\Programs\Anaconda\envs\olm\Lib\site-packages (from markdown-it-py==3.0.0->markdown-pdf) (0.1.2)
Collecting httplib2 (from plantuml==0.3.0->markdown-pdf)
  Downloading httplib2-0.31.2-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in D:\Programs\Anaconda\envs\olm\Lib\site-packages (from requests>=2.32.5->markdown-pdf) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in D:\Programs\Anaconda\envs\olm\Lib\site-packages (from requests>=2.32.5->markdown-pdf) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in D:\Programs\Anaconda\envs\olm\Lib\site-packages (from requests>=2.32.5->markdown-pdf) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in D:\Programs\Anaconda\envs\olm\Lib\site-packages (from requests>=2.32.5->markdown-pdf) (2026.1.4)
Collecting pyparsing<4,>=3.1 (from httplib2->plantuml==0.3.0->markdown-pdf)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Downloading markdown_pdf-1.13.1-py3-none-any.whl (21 kB)
Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Downloading plantuml-0.3.0-py3-none-any.whl (5.8 kB)
Downloading pymupdf-1.27.1-cp310-abi3-win_amd64.whl (19.2 MB)
   ---------------------------------------- 0.0/19.2 MB ? eta -:--:--
   ----- ---------------------------------- 2.9/19.2 MB 23.8 MB/s eta 0:00:01
   -------------------------- ------------- 12.8/19.2 MB 40.2 MB/s eta 0:00:01
   ---------------------------------------  19.1/19.2 MB 36.6 MB/s eta 0:00:01
   ---------------------------------------- 19.2/19.2 MB 31.9 MB/s  0:00:00
Downloading httplib2-0.31.2-py3-none-any.whl (91 kB)
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, PyMuPDF, markdown-it-py, httplib2, plantuml, markdown-pdf

   ---------------------------------------- 0/6 [pyparsing]
   ---------------------------------------- 0/6 [pyparsing]
   ------ --------------------------------- 1/6 [PyMuPDF]
   ------ --------------------------------- 1/6 [PyMuPDF]
   ------ --------------------------------- 1/6 [PyMuPDF]
   ------ --------------------------------- 1/6 [PyMuPDF]
   ------ --------------------------------- 1/6 [PyMuPDF]
   ------ --------------------------------- 1/6 [PyMuPDF]
  Attempting uninstall: markdown-it-py
   ------ --------------------------------- 1/6 [PyMuPDF]
    Found existing installation: markdown-it-py 4.0.0
   ------ --------------------------------- 1/6 [PyMuPDF]
   ------------- -------------------------- 2/6 [markdown-it-py]
    Uninstalling markdown-it-py-4.0.0:
   ------------- -------------------------- 2/6 [markdown-it-py]
      Successfully uninstalled markdown-it-py-4.0.0
   ------------- -------------------------- 2/6 [markdown-it-py]
   ------------- -------------------------- 2/6 [markdown-it-py]
   ------------- -------------------------- 2/6 [markdown-it-py]
   ------------- -------------------------- 2/6 [markdown-it-py]
   ------------- -------------------------- 2/6 [markdown-it-py]
   ------------- -------------------------- 2/6 [markdown-it-py]
   ------------- -------------------------- 2/6 [markdown-it-py]
   ------------- -------------------------- 2/6 [markdown-it-py]
   -------------------- ------------------- 3/6 [httplib2]
   --------------------------------- ------ 5/6 [markdown-pdf]
   ---------------------------------------- 6/6 [markdown-pdf]

Successfully installed PyMuPDF-1.27.1 httplib2-0.31.2 markdown-it-py-3.0.0 markdown-pdf-1.13.1 plantuml-0.3.0 pyparsing-3.3.2

In [2]:
from langchain_community.document_loaders import PyMuPDFLoader
import re
file_path = "docs/LuC_213_L00_DL_edited_oncobox_ru.pdf"
file_path = "docs/CC_215_L00_DL_fusion_fixed_oncobox_ru.pdf"
loader = PyMuPDFLoader(file_path, mode='single')
docs = loader.load()

'Полный[ \\n]перечень[ \\n]несиноним'

In [159]:

re.search('(Ранг.{,10}Препарат.{,10}Активированные.{,10}мишени'+\
                      '.{,10}Подавленные.{,10}мишени.{,10}Drug.{,10}score)'+\
                      f"(.*)(?:{xx})",
                      #'(.*)(Полный)',
                      docs[0].page_content.replace('\x0c',''), 
                      flags=re.DOTALL)

In [160]:
loader = PyMuPDFLoader(file_path, mode='single')
docs = loader.load()

text = re.search('База клинических испытаний:(.*)', docs[0].page_content
     ).groups()[0].strip()


# ищем след.раздел от нашей таблицы
table_oc = re.search('(?:Содержание)[^\\n]*(\\n[\D]*)', 
      docs[0].page_content.replace('\x0c',''), 
      flags=re.DOTALL).groups()[0].split('\n')
table_treats_id = table_oc.index('Полный список препаратов')
next_title = table_oc[table_treats_id+1]
xx = next_title[:25].replace(' ','[ \\n]')

table_part = re.search('(Ранг.{,10}Препарат.{,10}Активированные.{,10}мишени'+\
                      '.{,10}Подавленные.{,10}мишени.{,10}Drug.{,10}score)'+\
                      f'(.*)(?:{xx})',
                      #'(.*)(Полный)',
                      docs[0].page_content.replace('\x0c',''), 
                      flags=re.DOTALL).group()

treats=re.findall("(\s?\\n\d+([ а-яА-Я]*))"+\
          "((\\n[ a-zA-Zа\d,\n]*((?!\\n\d).)*)| )"+\
          "(\\n(- |(-?\d+\.\d+)))",
         table_part,
         flags=re.DOTALL)

treats_df = pd.DataFrame(treats, 
                         columns=['name_','treat',
                                  'm_','m2_','_',
                                  'drugscore_','score','d_']
                        )
df = treats_df[['treat','score']]
df.loc[df.score.isin(['- ','-',' -']),'score'] = '10.00'

C:\Users\105\AppData\Local\Temp\ipykernel_9636\2951793157.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df.score.isin(['- ','-',' -']),'score'] = '10.00'

In [161]:
file_path = "docs/CC_215_L00_DL_fusion_fixed_oncobox_ru.pdf"

In [162]:
f,t,df2 = extract.info_from_doc(file_path)

C:\Users\105\GitHub\TrialMind-SLR\extract.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\105\GitHub\TrialMind-SLR\extract.py:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [163]:
len(t)

75

In [164]:
f

'Colorectal cancer'

In [165]:
t

['Crizotinib',
 'Lorlatinib',
 'Nectinumab',
 'Nimotuzumab',
 'Panitumumab',
 'Cetuximab',
 'Brigatinib',
 'Ramucirumab',
 'Pomalidomide',
 'Tamoxifen',
 'Denosumab',
 'Duglucib',
 'Inavolizumab',
 'Bevacizumab',
 'Anastrozole',
 'Letrozole',
 'Fulvestrant',
 'Exemestane',
 'Buserelin',
 'Goserelin',
 'Leuprolide',
 'Triptorelin',
 'Lapatinib',
 'Afatinib',
 'Acalabrutinib',
 'Ibrutinab',
 'Alectinib',
 'Ceritinib',
 'Mogamulizumab',
 'Enfortumab vedotin',
 'Lenalidomide',
 'Ganetespib',
 'Mirvetuximab',
 'Afibrinogen',
 'Sacituzumab govitecan',
 'Gemtuzumab',
 'Tecemotide',
 'Pertuzumab',
 'Trastuzumab',
 'Ibritumomab tiuxetan',
 'Obinutuzumab',
 'Ofatumumab',
 'Rituximab',
 'Flavopiridol',
 'Medroxyprogesterone',
 'Dienogest',
 'Levonorgestrel',
 'Megestrol',
 'Rigosertib',
 'IZD-1001',
 'Copanlisib',
 'Alpelisib',
 'Thalidomide',
 'Mitotane',
 'Gilteritinib',
 'Vorinostat',
 'Inotuzumab ozogamicin',
 'Daratumumab',
 'Alemtuzumab',
 'Vorasidenib',
 'Sirolimus',
 'Temsirolimus',
 'Everolimus',
 'Idealisib',
 'Methyltestosterone',
 'Flutaximesterone',
 'Belinostat',
 'Blinatumomab',
 'Bortezomib',
 'Romidepsin',
 'Bendamustine',
 'Carmustine',
 'Lomustine',
 'Temozolomide',
 'Homoharringtonine']

In [30]:
client = OpenAI(
        base_url=os.getenv("BASE_URL"),
        api_key=os.getenv("OPENAI_API_KEY"),
        http_client=httpx.Client(verify=False)
    )

In [109]:
treat001 = ' '.join(df[df.score>=0.01].treat.values)

In [110]:
messages = [{'role':'system', 'content':'You are a helpful assistant /no_think'},
                {'role':'user', 'content':f"Translate the following medicine into English: {treat001}"}]

response = client.chat.completions.create(
    model=os.getenv("MODEL_NAME"),
    messages=messages,
    temperature=0
)
fin = response.choices[0].message.content
fin

'Crizotinib  \nLorlatinib  \nNecitumumab  \nNimotuzumab  \nPanitumumab  \nCetuximab  \nBrigatinib  \nRamucirumab  \nPomalidomide  \nToremifene  \nDenosumab  \nDuglucib (Duglucib)  \nInavolizumab  \nBevacizumab  \nAnastrozole  \nLetrozole  \nTamoxifen  \nFulvestrant  \nExemestane  \nBuserelin  \nGonadotropin-releasing hormone (GnRH) analogs: Goserelin  \nLeuprolide  \nTriptorelin  \nLapatinib  \nAfatinib  \nAcalabrutinib  \nIbrutinab  \nAlectinib  \nCeritinib  \nMogamulizumab  \nEnfortumab vedotin  \nLenalidomide  \nGanetespib  \nMirtuzumab  \nAfatinib (Afatinib)  \nSacituzumab govitecan  \nEmtuzumab  \nTecemotide  \nPerforomab  \nTrastuzumab  \nIbritumomab tiuxetan  \nObinutuzumab  \nOfatumumab  \nRituximab  \nFlavopiridol  \nMedroxyprogesterone acetate  \nDienogest  \nLevonorgestrel  \nMegestrol  \nRigosertib  \nIzaviridine  \nCopanlisib  \nAlpelisib  \nThalidomide  \nMitotane  \nGilteritinib  \nVorinostat  \nInotuzumab ozogamicin  \nMoxetumomab pasudotox  \nDaratumumab  \nAlemtuzumab  \nVorazidine  \nSorafenib  \nTemsirolimus  \nEverolimus  \nIdealisib  \nMethyltestosterone  \nFluoxymesterone  \nBelinostat  \nBlinatumomab  \nBortezomib  \nRomidepsin  \nBendamustine  \nCarboplatin  \nLomustine  \nTemozolomide  \nHomoharringtonine'

In [108]:
client.chat.completions.create(
    model=os.getenv("MODEL_NAME"),
    messages=[{'role':'system', 'content':'You are a helpful assistant /no_think'},
                {'role':'user', 'content':f"Translate into English: {'Ригосертиб, Ивозидениб, Копанлисиб '}"}],
    temperature=0
).choices[0].message.content

'Rigosertib, Ivosidenib, Copanlisib'

In [55]:
os.getenv("MODEL_NAME")

'qwen3:8b'

In [71]:
client = OpenAI(
        base_url=os.getenv("BASE_URL"),
        api_key=os.getenv("OPENAI_API_KEY"),
        http_client=httpx.Client(verify=False),
        
    )

In [69]:
from ollama import Client
client2 = Client(
  host='http://localhost:11434',
  headers={'x-some-header': 'some-value'}
)

client2.chat(model=os.getenv("MODEL_NAME"), messages=[
  {
    'role': 'user',
    'content': 'hey',
  },
    
],
      think=False,
            )

TypeError: Client.chat() got an unexpected keyword argument 'temperature'

In [88]:
%%time
client.chat.completions.create(
    model='qwen3:14b',
    messages=[{'role':'user', 'content':f"hey"}],
    temperature=0,
    extra_body={"reasoning_effort": "none"}
)

CPU times: total: 31.2 ms
Wall time: 12.5 s

ChatCompletion(id='chatcmpl-291', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='Hey! How can I assist you today? 😊', refusal=None, role='assistant', annotations=None, audio=None, function_call=None, tool_calls=None))], created=1772207881, model='qwen3:14b', object='chat.completion', service_tier=None, system_fingerprint='fp_ollama', usage=CompletionUsage(completion_tokens=12, prompt_tokens=17, total_tokens=29, completion_tokens_details=None, prompt_tokens_details=None))

In [52]:
%%time
client.chat.completions.create(
    model=os.getenv("MODEL_NAME"),
    messages=[{'role':'user', 'content':f"/set think hey"}],
    temperature=0
)

CPU times: total: 0 ns
Wall time: 14.2 s

ChatCompletion(id='chatcmpl-709', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='Hello! How can I assist you today? 😊', refusal=None, role='assistant', annotations=None, audio=None, function_call=None, tool_calls=None, reasoning='Okay, the user sent "hey /think". Let me figure out what they need. They might be testing if I can process commands or just greeting me. Since they used "/think", maybe they want me to think about something. But the message is short. I should respond politely and ask how I can assist. Keep it friendly and open-ended. Let me make sure there\'s no hidden request here. Just a simple greeting. Alright, respond with a welcoming message.\n'))], created=1772205791, model='qwen3:8b', object='chat.completion', service_tier=None, system_fingerprint='fp_ollama', usage=CompletionUsage(completion_tokens=111, prompt_tokens=13, total_tokens=124, completion_tokens_details=None, prompt_tokens_details=None))

In [3]:
fin_condition,treatements_eng,df2 = extract.info_from_doc(file_path)

C:\Users\105\GitHub\TrialMind-SLR\extract.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df.score.isin(['- ','-',' -']),'score'] = '10.00'
C:\Users\105\GitHub\TrialMind-SLR\extract.py:88: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.score = df.score.astype(float)

In [4]:
fin_condition

'Colorectal cancer'

In [5]:
treatements_eng[:5]

['Crizotinib', 'Lorlatinib', 'Nectinumab', 'Nimotuzumab', 'Panitumumab']

In [6]:
#fin_condition = 'Colorectal cancer'
#treatements_eng =  ['Crizotinib','Lorlatinib',]
pubmed_api_key= '6892c4129cef143ff92d11533848d2e0d908'#os.getenv("PUBMED_API_KEY", '')

In [7]:

search_api = PubmedAPIWrapper()
# page_size is the max number of records to return!!!! not pages!
tmp_inputs = {
        "page_size": 100,
        "keyword_map": {'conditions':[fin_condition], 
                        'treatments':[treatements_eng[0]]
                       },
        "keywords": {
            "OPERATOR": 'AND'
        }
}

response = search_api.build_search_query_and_get_pmid(tmp_inputs, 
                                                      api_key=pubmed_api_key)

df_papers = pmid2papers(
                        pmid_list=response[0], 
                        api_key=pubmed_api_key)
papers = df_papers[0]["Title"] + ": " + df_papers[0]["Abstract"].fillna("") # important to fillna
papers = papers.tolist()
papers[:1]

['Radiotherapy-Related Autophagy Genes Predict Prognosis and Reveal Immunoscape Features and Immunotherapeutic Agents in Colorectal Cancer Patients.: Numerous genes have been associated with colorectal cancer (CRC) treatment in prior studies, but the impact of radiotherapy-related autophagy genes (RRAGs) on CRC remains largely unexplored. The Cancer Genome Atlas (TCGA) and Gene Expression Omnibus (GEO) databases were implemented to screen out RRAGs significantly associated with survival, and a prognostic model was constructed. Samples were categorized into high- and low-risk groups with median riskscore. Immunomicroenvironment analysis, immunotherapy response prediction, enrichment analysis, tumor mutation analysis and drug prediction were performed in risk groups. Expression of signature genes in CRC cells was examined using quantitative reverse transcription polymerase chain reaction (qRT-PCR). There were 10 CRC-related RRAGs found. Prognostic models were built with RRAGs. Based on immune infiltration analysis, low-risk populations showed significantly greater levels of immune infiltration (P P ARHGEF17 mutation rate was 6%. Medications such as CGP-082996, Dasatinib, Erlotinib, and Salubrinal were more sensitive to high-risk group, whereas drugs such as FTI-277, DMOG, and Crizotinib were more sensitive to low-risk group. UGT1A6 and IRGM were significantly upregulated in tumor group as revealed by qRT-PCR. This study constructed a new prognostic model for CRC patients based on RRAGs, and a series of analysis results is conducive to providing more theoretical references and new insights into precision treatment of CRC patients.']

In [75]:
df_papers[0].Abstract.str.len()

0     1505
1     2070
2     1094
3     1772
4     1602
      ...
62    2389
63    1491
64    1109
65     357
66     712
Name: Abstract, Length: 67, dtype: int64

In [9]:
len(papers)

67

In [76]:
df_papers[0]

,PMID,Journal,Year,Month,Day,Title,Publication Type,Authors,Abstract
0,41213063,"Journal of environmental pathology, toxicology...",2025,,,Radiotherapy-Related Autophagy Genes Predict P...,Journal Article,"Mao Mao, Yichao Zhuang, Yan Chen",Numerous genes have been associated with color...
1,23400546,Cancer,2013,May,01,Identification of ROS1 rearrangement in gastri...,"Journal Article, Research Support, Non-U.S. Gov't","Jeeyun Lee, Seung Eun Lee, So Young Kang, In-G...","Recently, chromosomal rearrangements involving..."
2,22845480,Expert review of molecular diagnostics,2012,Jul,,Personalized medicine and pharmacogenetic biom...,"Journal Article, Research Support, N.I.H., Ext...","Frank S Ong, Kingshuk Das, Jay Wang, Hana Vaki...","In the field of oncology, clinical molecular d..."
3,40369167,Cell death and differentiation,2025,Nov,,ARID1A loss enhances sensitivity to c-MET inhi...,Journal Article,"Xu Zhang, Zihuan Wang, Yilin He, Kejin Wang, C...","ARID1A, a subunit of the SWI/SNF chromatin-rem..."
4,24992173,Applied immunohistochemistry & molecular morph...,2015,Feb,,ALK and ROS1 overexpression is very rare in co...,"Journal Article, Research Support, Non-U.S. Gov't","Michelle Houang, Christopher W Toon, Adele Cla...","Crizotinib, a small molecule tyrosine kinase i..."
...,...,...,...,...,...,...,...,...,...
62,28465216,Pharmacological research,2017,Jul,,ROS1 protein-tyrosine kinase inhibitors in the...,"Journal Article, Review",Robert Roskoski,ROS1 protein-tyrosine kinase fusion proteins a...
63,26375439,Oncotarget,2015,Sep,29,Gastrointestinal malignancies harbor actionabl...,"Journal Article, Research Support, Non-U.S. Gov't","Jeeyun Lee, Sai-Hong Ignatius Ou, Ji Min Lee, ...","Recently, MET exon 14 deletion (METex14del) ha..."
64,27565250,Fertility and sterility,2016,Nov,,Ovarian stimulation in young adult cancer surv...,"Case Reports, Journal Article, Review","H Irene Su, Meghan W Connell, Lyudmila A Bazhe...",To describe a clinical approach to and outcome...
65,38711893,AME case reports,2024,,,Partial response to crizotinib + regorafenib +...,"Case Reports, Journal Article","Yingying Huang, Shuai Zhang, Xueqing Hu, Xiang...",Colorectal cancer (CRC) with the Raf murine sa...
66,32821654,World journal of clinical oncology,2020,Jul,24,Complete response in anaplastic lymphoma kinas...,"Case Reports, Journal Article","Victoire de Salins, Gokoulakrichenane Loganada...",Oncocytic carcinoma of the thyroid is a rare d...

In [89]:

os.environ["MODEL_NAME"] ='medllama2'
os.environ["MODEL_NAME"] ='qwen3:14b'

In [90]:
%%time
api = LiteratureScreening()
ec_predP = api.run(
    population = f"Patients with {fin_condition} undergoing treatment with {treatements_eng[0]}",
    intervention = f"{treatements_eng[0]}",
    comparator = "",
    outcome = "",
    llm = os.getenv("MODEL_NAME"),
    criteria = [f"Does the study focus on patients with '{fin_condition}'?",
                 f"Does the study examine the use of '{treatements_eng[0]}'?", 
                f"Does the study describe the effect or sensitivity of '{treatements_eng[0]}' treatment?"],#title_criteria + content_criteria,
    papers = papers[:1], # make for the top-100 for demo
)
ec_predP

1
False

parsed_results in asynch [PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=['The study explicitly mentions patients with colorectal cancer.', 'The study examines the use of Crizotinib in the context of drug sensitivity analysis.', 'The study describes the sensitivity of the low-risk group to Crizotinib.'])]

OUTPUTS:  [PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=['The study explicitly mentions patients with colorectal cancer.', 'The study examines the use of Crizotinib in the context of drug sensitivity analysis.', 'The study describes the sensitivity of the low-risk group to Crizotinib.'])]
CPU times: total: 109 ms
Wall time: 1min 8s

[PaperEvaluation(evaluations=['YES', 'YES', 'YES'], rationale=['The study explicitly mentions patients with colorectal cancer.', 'The study examines the use of Crizotinib in the context of drug sensitivity analysis.', 'The study describes the sensitivity of the low-risk group to Crizotinib.'])]

In [ ]:
evalsP = [i.evaluations for i in ec_predP]

word2int = {"YES": 1, 
            "UNCERTAIN": 0,
            "NO": -1
           }
#rev_subs = { v:k for k, v in word2int.items()} # subs.iteritems() In Python 3
new_evalsP = []
for one_e in evalsP:
    new_evalsP.append([word2int.get(item, 0) for item in one_e ])
new_evalsP = np.array(new_evalsP)  
df_p_e = df_papers[0]
df_p_e['s1','s2','s3'] = new_evalsP
chosen_df = df_p_e[(df_p_e['s1']==1)&(df_p_e['s2']==1)&(df_p_e['s3']>=0)]
'''
print(new_evalsP.sum(axis=1))
df_papers[0]['screen_eval'] = -5

#.iloc[:5].copy()
df_p_e['screen_eval'] = new_evalsP.sum(axis=1)
'''
df_p_e.head(3)

In [8]:
total_ev = 3
pmid_list = df_p_e[df_p_e.screen_eval>=total_ev
                        ].PMID.values.tolist()
papers_ch = df_p_e[df_p_e.screen_eval>=total_ev].Abstract.values
papers_ch_ta = df_p_e[df_p_e.screen_eval>=total_ev].Title.values +': ' + df_p_e[df_p_e.screen_eval>=total_ev].Abstract.values
docs =  [Document(page_content=i, 
                  metadata={"source": j}
                 ) for i,j in zip(papers_ch_ta,pmid_list)]
print(papers_ch.shape)
docs[:1]

(9,)

[Document(metadata={'source': '37543570'}, page_content='Epithelial cell adhesion molecule (EpCAM) regulates HGFR signaling to promote colon cancer progression and metastasis.: Epithelial cell adhesion molecule (EpCAM) is known to highly expression and promotes cancer progression in many cancer types, including colorectal cancer. While metastasis is one of the main causes of cancer treatment failure, the involvement of EpCAM signaling in metastatic processes is unclear. We propose the potential crosstalk of EpCAM signaling with the HGFR signaling in order to govern metastatic activity in colorectal cancer.\nImmunoprecipitation (IP), enzyme-linked immunosorbent assay (ELISA), and fluorescence resonance energy transfer (FRET) was conducted to explore the extracellular domain of EpCAM (EpEX) and HGFR interaction. Western blotting was taken to determine the expression of proteins in colorectal cancer (CRC) cell lines. The functions of EpEX in CRC were investigated by proliferation, migration, and invasion analysis. The combined therapy was validated via a tail vein injection method for the metastasis and orthotopic colon cancer models.\nThis study demonstrates that the EpEX binds to HGFR and induces downstream signaling in colon cancer cells. Moreover, EpEX and HGF cooperatively mediate HGFR signaling. Furthermore, EpEX enhances the epithelial-to-mesenchymal transition and metastatic potential of colon cancer cells by activating ERK and FAK-AKT signaling pathways, and it further stabilizes active β-catenin and Snail proteins by decreasing GSK3β activity. Finally, we show that the combined treatment of an anti-EpCAM neutralizing antibody (EpAb2-6) and an HGFR inhibitor (crizotinib) significantly inhibits tumor progression and prolongs survival in metastatic and orthotopic animal models of colon cancer.\nOur findings illuminate the molecular mechanisms underlying EpCAM signaling promotion of colon cancer metastasis, further suggesting that the combination of EpAb2-6 and crizotinib may be an effective strategy for treating cancer patients with high EpCAM expression.')]

In [11]:
vector_store._client.delete_collection(vector_store._collection.name)

In [12]:
embeddings = OllamaEmbeddings(model="all-minilm")

vector_store = Chroma(
    collection_name="example_collection",
    embedding_function=embeddings,
    persist_directory="./chroma_langchain_db",  # Where to save data locally, remove if not necessary
)

text_splitter=RecursiveCharacterTextSplitter(chunk_size=256, 
                                             chunk_overlap=50)

In [13]:
all_splits = text_splitter.split_documents(docs)
document_ids = vector_store.add_documents(documents=all_splits)

In [10]:
pmid_list

['37543570',
 '37773318',
 '38711893',
 '36053834',
 '38212428',
 '40369167',
 '36316649',
 '40140597',
 '40211189']

In [14]:
vector_store.similarity_search(f"the effectiveness of treating {fin_condition} with {treatements_eng[0]}",
                               k=4,
                               filter={"source": "37543570"}
)

[Document(id='0c40220b-0ae2-4971-bf54-036f137184f9', metadata={'source': '37543570'}, page_content='we show that the combined treatment of an anti-EpCAM neutralizing antibody (EpAb2-6) and an HGFR inhibitor (crizotinib) significantly inhibits tumor progression and prolongs survival in metastatic and orthotopic animal models of colon cancer.'),
 Document(id='b3480818-2ac1-4af1-89ca-c46f7dfd1f02', metadata={'source': '37543570'}, page_content='Our findings illuminate the molecular mechanisms underlying EpCAM signaling promotion of colon cancer metastasis, further suggesting that the combination of EpAb2-6 and crizotinib may be an effective strategy for treating cancer patients with high EpCAM'),
 Document(id='07337d48-a670-48ec-9968-932829d20216', metadata={'source': '37543570'}, page_content='Western blotting was taken to determine the expression of proteins in colorectal cancer (CRC) cell lines. The functions of EpEX in CRC were investigated by proliferation, migration, and invasion analysis. The combined therapy was validated via a tail vein'),
 Document(id='67d8be7b-e3d3-46e4-a342-2793b61e7c28', metadata={'source': '37543570'}, page_content='combined therapy was validated via a tail vein injection method for the metastasis and orthotopic colon cancer models.')]

In [15]:
len(pmid_list)

9

In [15]:
os.environ["MODEL_NAME"] ='medllama2'

In [20]:
f'Crizotinib effectiveness, string, the specific percentages and numbers as outcomes of treating {fin_condition} with {treatements_eng[0]} in the analyzed paper'

'Crizotinib effectiveness, string, the specific percentages and numbers as outcomes of treating Colorectal cancer with Crizotinib in the analyzed paper'

In [18]:
ii =len(pmid_list) #4

api = StudyCharacteristicsExtraction()
extracted = api.run(
    papers_inp=[pmid_list[:ii],papers_ch[:ii]],
    #fields=[f'The effectiveness of treating {fin_condition} with {treatements_eng[0]}',
    #       ],
    fields=[f'Crizotinib effectiveness, string, the specific percentages and numbers as outcomes of treating {fin_condition} with {treatements_eng[0]} in the analyzed paper'
           ],
    llm=os.getenv("MODEL_NAME"),
    chunk_size=0,
    chunk_overlap=0,
    thinking=False,
    vector_store = vector_store,
)

['37543570', '37773318', '38711893', '36053834', '38212428', '40369167', '36316649', '40140597', '40211189']
37543570
we show that the combined treatment of an anti-EpCAM neutralizing antibody (EpAb2-6) and an HGFR inhibitor (crizotinib) significantly inhibits tumor progression and prolongs survival in metastatic and orthotopic animal models of colon cancer.
Western blotting was taken to determine the expression of proteins in colorectal cancer (CRC) cell lines. The functions of EpEX in CRC were investigated by proliferation, migration, and invasion analysis. The combined therapy was validated via a tail vein
Our findings illuminate the molecular mechanisms underlying EpCAM signaling promotion of colon cancer metastasis, further suggesting that the combination of EpAb2-6 and crizotinib may be an effective strategy for treating cancer patients with high EpCAM
combined therapy was validated via a tail vein injection method for the metastasis and orthotopic colon cancer models.
37773318
and hematologic tumors (e.g., histiocytosis, leiomyosarcoma, lymphoma, myeloma, and colorectal, neuroendocrine, ovarian, pancreatic, renal, and thyroid cancer) bearing ALK fusions/rearrangements. Many reports used crizotinib or alectinib, but each of the
lung cancer (NSCLC), a rate that may be below the viability threshold of even large-scale treatment trials. Five ALK inhibitors -alectinib, brigatinib, ceritinb, crizotinib, and lorlatinib-are FDA approved for ALK-aberrant NSCLCs, and crizotinib is also
for ALK-aberrant NSCLCs, and crizotinib is also approved for ALK-aberrant IMTs and ALCL, including in children. Herein, we review the pharmacologic tractability of ALK alterations, focusing beyond NSCLC. Importantly, the hallmark of approved indications
used crizotinib or alectinib, but each of the approved ALK inhibitors have shown activity. ALK inhibitor activity is also seen in neuroblastoma, which bear ALK mutations (rather than fusions/rearrangements), but response rates are lower (~10-20%). Current
38711893
Partial response to crizotinib + regorafenib + PD-1 inhibitor in a metastatic: Colorectal cancer (CRC) with the Raf murine sarcoma viral oncogene homolog B (
A 49-year-old Chinese male was diagnosed with ascending colon adenocarcinoma (cT3N+?M1) with liver metastases. The patient performed next-generation sequencing (NGS) using tissue and circulating tumor DNA (ctDNA), and the results showed a
This study reported a co-existence of a
36053834
GOPC-ROS1. Molecularly targeted treatment with crizotinib induced a rapid and sustained partial response. After 15 months on crizotinib disseminated tumor progression occurred and KRAS Q61H emerged in tissue and liquid biopsies. ROS1 rearrangements define
rare cases of colorectal cancer (CRC), yet little is known about the frequency, molecular characteristics, and therapeutic vulnerabilities of ROS1-driven CRC. We analyzed a clinical dataset of 40 589 patients with CRC for ROS1 genomic rearrangements and
CRCs. KRAS mutations were significantly less abundant in ROS1-rearranged vs ROS1 wild type cases. The index patient presented with chemotherapy-refractory metastatic right-sided colon cancer harboring GOPC-ROS1. Molecularly targeted treatment with
ROS1 genomic rearrangements are rare actionable drivers in microsatellite stable colorectal cancer.: c-Ros oncogene 1, receptor tyrosine kinase (ROS1) genomic rearrangements have been reported previously in rare cases of colorectal cancer (CRC), yet little
38212428
and acquired cetuximab resistance in colorectal cancer (CRC). Conversely, HGF overexpression was necessary and sufficient to induce cetuximab resistance and loss of polarity. Moreover, HGF-induced cetuximab resistance could be overcome by the downstream
the RTKs MET and RON, HGF and HGFL, respectively, are synthesized as inactive precursors that are activated by cellular proteases. Our newly generated HGF/HGFL protease inhibitors could overcome both de novo and acquired cetuximab resistance in colorectal
Inhibition of autocrine HGF maturation overcomes cetuximab resistance in colorectal cancer.: Although amplifications and mutations in receptor tyrosine kinases (RTKs) act as bona fide oncogenes, in most cancers, RTKs maintain moderate expression and remain
resistance could be overcome by the downstream MET inhibitor, crizotinib, and upstream protease inhibitors. Additionally, HAI-1, an endogenous inhibitor of HGF proteases, (i) was downregulated in CRC, (ii) exhibited increased genomic methylation that
40369167
ARID1A-deficient colorectal cancer (CRC) cells induce synthetic lethality when treated with inhibitors of c-MET receptor tyrosine kinase. c-MET specific inhibitor PHA-665752 as well as two other FDA-approved drugs, crizotinib and cabozantinib, selectively
suppressor in various cancer types. Owing to its high frequency of inactivating mutations, ARID1A has emerged as a promising target for the development of anticancer drugs. In this study, we report that ARID1A-deficient colorectal cancer (CRC) cells
drugs, crizotinib and cabozantinib, selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models. Mechanistically, we identified a tripartite functional association among ARID1A, c-MET, and NRF2, where ARID1A and
ultimately inducing ferroptosis. This study reveals a novel synthetic lethal relationship between ARID1A and c-MET signaling in promoting ferroptosis and proposes c-MET inhibitors as a potential therapeutic strategy for ARID1A-deficient CRC.
36316649
Personalized targeted therapy prescription in colorectal cancer using algorithmic analysis of RNA sequencing data.: Overall survival of advanced colorectal cancer (CRC) patients remains poor, and gene expression analysis could potentially complement
bevacizumab, bortezomib, cabozantinib, cetuximab, crizotinib, denosumab, panitumumab and regorafenib as monotherapy or in combination with chemotherapy, and information on the success of totally 39 lines of therapy was collected.
rating of targeted therapeutics. Oncobox ranks cancer drugs according to the efficiency score calculated using target genes expression and molecular pathway activation data. The patients had primary and metastatic CRC with metastases in liver, peritoneum,
Oncobox drug efficiency score was effective biomarker that could predict treatment outcomes in the experimental cohort (AUC 0.77 for all lines of therapy and 0.91 for the first line after tumor sampling). Separately for bevacizumab, it was effective in
40140597
In this study, we assessed safety of MEK1/2 inhibitor PD-0325901 with c-MET inhibitor crizotinib and determined the optimal biological doses for subsequent clinical trials.
Twenty-five patients were recruited in 4 cohorts up to doses of crizotinib 200 mg B.D continuously with PD-0325901 8 mg B.D, days 1-21 every 28 days. One in six patients exhibited a dose-limiting toxicity at this dose level. Drug-related adverse events
A phase Ia study of the MEK1/2 inhibitor PD-0325901 with the c-MET inhibitor crizotinib in patients with advanced solid cancers.: Single-agent MEK1/2 inhibition has been disappointing in clinical trials targeting RAS mutant (MT) cancers, probably due to
In this dose-escalation phase I trial, patients with advanced solid tumours received PD-0325901 with crizotinib, using a rolling-6 design to determine the maximum tolerable dose (MTD) and safety/tolerability. Blood samples for pharmacokinetics and skin
40211189
A Phase Ia/b study of MEK1/2 inhibitor binimetinib with MET inhibitor crizotinib in patients with RAS mutant advanced colorectal cancer (MErCuRIC).: Targeting RAS mutant (MT) colorectal cancer (CRC) remains a difficult challenge, mainly due to the
RASMT CRC. This dose escalation/expansion study assessed safety and initial efficacy of the MEK1/2 inhibitor binimetinib with MET inhibitor crizotinib in RASMT advanced CRC patients.
In the dose escalation phase, patients with advanced solid tumours received binimetinib with crizotinib, using a rolling- 6 design to determine the maximum tolerable dose (MTD) and safety/tolerability. A subsequent dose expansion in RASMT CRC patients
Combination binimetinib/crizotinib showed a poor tolerability with no objective responses observed in RASMT advanced CRC patients. EudraCT-Number: 2014-000463 - 40 (20/06/2014: A Sequential Phase I study of MEK1/2 inhibitors PD- 0325901 or Binimetinib
9
You are now the following python function: ```
def extract_fields_from_input_study(inputs: Dict[str, Any]) -> str:
    """
    This function is tasked with analyzing clinical trial study reports or papers to extract specific information as structured data and provide citations for the extracted information.
    The user will provide a list of fields they are interested in, along with a natural language description for each field to guide you on what content to look for and from which parts of the report to extract it.

    IMPORTANT:
    For each field described by the user, you need to:
    1. Identify and extract the relevant information from the report, based on the provided description.
       The answer should be under 200 characters. Summarize the information without losing clarity.
    2. Structure the extracted information into a standard format whenever possible (e.g., integer, numerical values, dates, keywords, list of terms).
        If standardization is not possible, the information should be presented in text format.
        If the field is not found in the report, the extracted value should be "NP".
    3. Provide a reference to the document ID from which this information was extracted.
        This citation id should be restricted to be integers only.
        You should NOT cite more than three sources for a single field.
        If the field is "NP", sources should be an empty list.
        You should try your best to provide the most relevant and specific citation for each field.
        If two or more sources are equally relevant, you can just cite one of them.

    The function returns a string representing a dictionary with each key representing a field and its extracted value.

# User provided inputs
paper_content = """{paper_content}"""
fields = """{fields}"""

inputs = {{
    "paper_content": paper_content,
    "fields": fields
}}

# Reply Format:
Return the information in the following JSON-format.
```json
{{
    [
        {{
            "name": "fieldName1",
            "value": "extractedInfo1",
            "source_id":[1, 2, 3]
        }},
        {{
            "name":"fieldName2",
            "value":"extractedInfo2",
            "source_id":[4]
        }},
        ...
    ]
}}
```
You MUST return ONLY valid JSON, Do NOT include any explanations, comments, or extra text.

1

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='significantly inhibits tumor progression and prolongs survival in metastatic and orthotopic animal models of colon cancer.', source_id=[3])])]

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='showed significant activity in colorectal cancer patients bearing ALK fusions/rearrangements (~30% response rate).', source_id=[1])])]

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Partial response to crizotinib + regorafenib + PD-1 inhibitor in a metastatic Colorectal cancer (CRC) with the Raf murine sarcoma viral oncogene homolog B (Raf/B)', source_id=[1])])]

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='induced a rapid and sustained partial response', source_id=[1])])]

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='overcome cetuximab resistance in colorectal cancer', source_id=[1])])]

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models.', source_id=[1])])]

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='NP', source_id=[])])]

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Improved overall survival in patients with advanced solid tumors.', source_id=[1])])]

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='No objective responses observed in RASMT advanced CRC patients.', source_id=[1])])]

outputs: [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='significantly inhibits tumor progression and prolongs survival in metastatic and orthotopic animal models of colon cancer.', source_id=[3])]), Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='showed significant activity in colorectal cancer patients bearing ALK fusions/rearrangements (~30% response rate).', source_id=[1])]), Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Partial response to crizotinib + regorafenib + PD-1 inhibitor in a metastatic Colorectal cancer (CRC) with the Raf murine sarcoma viral oncogene homolog B (Raf/B)', source_id=[1])]), Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='induced a rapid and sustained partial response', source_id=[1])]), Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='overcome cetuximab resistance in colorectal cancer', source_id=[1])]), Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models.', source_id=[1])]), Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='NP', source_id=[])]), Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='Improved overall survival in patients with advanced solid tumors.', source_id=[1])]), Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='No objective responses observed in RASMT advanced CRC patients.', source_id=[1])])]

In [19]:
for one_extr in extracted:
    for one_filed_res in one_extr.fieldresult:
        if one_filed_res.value!="NP":
            print(one_filed_res.value)
            print(one_filed_res._cited_blocks)
            print()

significantly inhibits tumor progression and prolongs survival in metastatic and orthotopic animal models of colon cancer.
['combined therapy was validated via a tail vein injection method for the metastasis and orthotopic colon cancer models.']

showed significant activity in colorectal cancer patients bearing ALK fusions/rearrangements (~30% response rate).
['lung cancer (NSCLC), a rate that may be below the viability threshold of even large-scale treatment trials. Five ALK inhibitors -alectinib, brigatinib, ceritinb, crizotinib, and lorlatinib-are FDA approved for ALK-aberrant NSCLCs, and crizotinib is also']

Partial response to crizotinib + regorafenib + PD-1 inhibitor in a metastatic Colorectal cancer (CRC) with the Raf murine sarcoma viral oncogene homolog B (Raf/B)
['A 49-year-old Chinese male was diagnosed with ascending colon adenocarcinoma (cT3N+?M1) with liver metastases. The patient performed next-generation sequencing (NGS) using tissue and circulating tumor DNA (ctDNA), and the results showed a']

induced a rapid and sustained partial response
['rare cases of colorectal cancer (CRC), yet little is known about the frequency, molecular characteristics, and therapeutic vulnerabilities of ROS1-driven CRC. We analyzed a clinical dataset of 40\u2009589 patients with CRC for ROS1 genomic rearrangements and']

overcome cetuximab resistance in colorectal cancer
['the RTKs MET and RON, HGF and HGFL, respectively, are synthesized as inactive precursors that are activated by cellular proteases. Our newly generated HGF/HGFL protease inhibitors could overcome both de novo and acquired cetuximab resistance in colorectal']

selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models.
['suppressor in various cancer types. Owing to its high frequency of inactivating mutations, ARID1A has emerged as a promising target for the development of anticancer drugs. In this study, we report that ARID1A-deficient colorectal cancer (CRC) cells']

Improved overall survival in patients with advanced solid tumors.
['Twenty-five patients were recruited in 4 cohorts up to doses of crizotinib 200\u2009mg B.D continuously with PD-0325901 8\u2009mg B.D, days 1-21 every 28 days. One in six patients exhibited a dose-limiting toxicity at this dose level. Drug-related adverse events']

No objective responses observed in RASMT advanced CRC patients.
['RASMT CRC. This dose escalation/expansion study assessed safety and initial efficacy of the MEK1/2 inhibitor binimetinib with MET inhibitor crizotinib in RASMT advanced CRC patients.']

In [ ]:
os.environ["MODEL_NAME"] ='qwen3:8b'#'kamekichi128/qwen3-4b-instruct-2507'

ii =len(pmid_list) #4

api = StudyCharacteristicsExtraction()
extracted0 = api.run(
    papers_inp=[pmid_list[:ii],papers_ch[:ii]],
    #fields=[f'The effectiveness of treating {fin_condition} with {treatements_eng[0]}',
    #       ],
    fields=[f'Crizotinib effectiveness, string, the specific percentages and numbers as outcomes of treating {fin_condition} with {treatements_eng[0]} in the analyzed paper'
           ],
    llm=os.getenv("MODEL_NAME"),
    chunk_size=0,
    chunk_overlap=0,
    thinking=False,
    vector_store = vector_store,
)

['37543570', '37773318', '38711893', '36053834', '38212428', '40369167', '36316649', '40140597', '40211189']
9
You are now the following python function: ```
def extract_fields_from_input_study(inputs: Dict[str, Any]) -> str:
    """
    This function is tasked with analyzing clinical trial study reports or papers to extract specific information as structured data and provide citations for the extracted information.
    The user will provide a list of fields they are interested in, along with a natural language description for each field to guide you on what content to look for and from which parts of the report to extract it.

    IMPORTANT:
    For each field described by the user, you need to:
    1. Identify and extract the relevant information from the report, based on the provided description.
       The answer should be under 200 characters. Summarize the information without losing clarity.
    2. Structure the extracted information into a standard format whenever possible (e.g., integer, numerical values, dates, keywords, list of terms).
        If standardization is not possible, the information should be presented in text format.
        If the field is not found in the report, the extracted value should be "NP".
    3. Provide a reference to the document ID from which this information was extracted.
        This citation id should be restricted to be integers only.
        You should NOT cite more than three sources for a single field.
        If the field is "NP", sources should be an empty list.
        You should try your best to provide the most relevant and specific citation for each field.
        If two or more sources are equally relevant, you can just cite one of them.

    The function returns a string representing a dictionary with each key representing a field and its extracted value.

# User provided inputs
paper_content = """{paper_content}"""
fields = """{fields}"""

inputs = {{
    "paper_content": paper_content,
    "fields": fields
}}

# Reply Format:
Return the information in the following JSON-format.
```json
{{
    [
        {{
            "name": "fieldName1",
            "value": "extractedInfo1",
            "source_id":[1, 2, 3]
        }},
        {{
            "name":"fieldName2",
            "value":"extractedInfo2",
            "source_id":[4]
        }},
        ...
    ]
}}
```
You MUST return ONLY valid JSON, Do NOT include any explanations, comments, or extra text.

1

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='NP', source_id=[])])]

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='NP', source_id=[])])]

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='NP', source_id=[])])]

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='NP', source_id=[])])]

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='NP', source_id=[])])]

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='NP', source_id=[])])]

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='NP', source_id=[])])]

parsed_results in asynch [Results(fieldresult=[FieldResult(name='Crizotinib effectiveness', value='NP', source_id=[])])]

In [ ]:
for one_extr in extracted0:
    for one_filed_res in one_extr.fieldresult:
        if one_filed_res.value!="NP":
            print(one_filed_res.value)
            print(one_filed_res._cited_blocks)
            print()

In [42]:
len('Crizotinib-IR808@BSA NPs exhibited synergistic chemophototherapy effects on tumors. In conclusion, this innovative imaging-mediated multifunctional组合t')

150

In [126]:
extracted[0].fieldresult[0]

FieldResult(name='Crizotinib Results', value='Crizotinib and cabozantinib selectively inhibited ', source_id=[0])

In [96]:
extracted[0].fieldresult[0]._cited_blocks

['colorectal cancer (CRC) cells induce synthetic lethality when treated with inhibitors of c-MET receptor tyrosine kinase. c-MET specific inhibitor PHA-665752 as well as two other FDA-approved drugs, crizotinib and cabozantinib, selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models. Mechanistically, we identified a tripartite functional association among ARID1A, c-MET, and NRF2, where ARID1A and c-MET pathways converge on the NRF2 transcription']

In [7]:
h = [[{'role': 'user', 
       'content': 'You are now the following python function: ```\ndef extract_fields_from_input_study(inputs: Dict[str, Any]) -> str:\n    """\n    This function is tasked with analyzing clinical trial study reports or papers to extract specific information as structured data and provide citations for the extracted information.\n    The user will provide a list of fields they are interested in, along with a natural language description for each field to guide you on what content to look for and from which parts of the report to extract it.\n\n    IMPORTANT:\n    For each field described by the user, you need to:\n    1. Identify and extract the relevant information from the report, based on the provided description.\n       The answer should be under 200 characters. Summarize the information without losing clarity. Add necessary context.\n    2. Structure the extracted information into a standard format whenever possible (e.g., integer, numerical values, dates, keywords, list of terms). \n        If standardization is not possible, the information should be presented in text format.\n        If the field is not found in the report, the extracted value should be "NP".\n    3. Provide a reference to the document ID from which this information was extracted.\n        This citation id should be restricted to be integers only.\n        You should NOT cite more than three sources for a single field.\n        If the field is "NP", sources should be an empty list.\n        You should try your best to provide the most relevant and specific citation for each field.\n        If two or more sources are equally relevant, you can just cite one of them.\n\n    The function returns a string representing a dictionary with each key representing a field and its extracted value.\n\n# User provided inputs\npaper_content = """(\'<source id="0"><content>suppressor in various cancer types. Owing to its high frequency of inactivating mutations, ARID1A has emerged as a promising target for the development of anticancer drugs. In this study, we report that ARID1A-deficient colorectal cancer (CRC) cells</content></source>\\n\\n<source id="1"><content>ARID1A-deficient colorectal cancer (CRC) cells induce synthetic lethality when treated with inhibitors of c-MET receptor tyrosine kinase. c-MET specific inhibitor PHA-665752 as well as two other FDA-approved drugs, crizotinib and cabozantinib, selectively</content></source>\\n\\n<source id="2"><content>ultimately inducing ferroptosis. This study reveals a novel synthetic lethal relationship between ARID1A and c-MET signaling in promoting ferroptosis and proposes c-MET inhibitors as a potential therapeutic strategy for ARID1A-deficient CRC.</content></source>\\n\\n<source id="3"><content>drugs, crizotinib and cabozantinib, selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models. Mechanistically, we identified a tripartite functional association among ARID1A, c-MET, and NRF2, where ARID1A and</content></source>\', [\'suppressor in various cancer types. Owing to its high frequency of inactivating mutations, ARID1A has emerged as a promising target for the development of anticancer drugs. In this study, we report that ARID1A-deficient colorectal cancer (CRC) cells\', \'ARID1A-deficient colorectal cancer (CRC) cells induce synthetic lethality when treated with inhibitors of c-MET receptor tyrosine kinase. c-MET specific inhibitor PHA-665752 as well as two other FDA-approved drugs, crizotinib and cabozantinib, selectively\', \'ultimately inducing ferroptosis. This study reveals a novel synthetic lethal relationship between ARID1A and c-MET signaling in promoting ferroptosis and proposes c-MET inhibitors as a potential therapeutic strategy for ARID1A-deficient CRC.\', \'drugs, crizotinib and cabozantinib, selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models. Mechanistically, we identified a tripartite functional association among ARID1A, c-MET, and NRF2, where ARID1A and\'])"""\nfields = """<field id=1>"Crizotinib effectiveness, string, The outcome of treating Colorectal cancer with Crizotinib"</field>"""\n\ninputs = {\n    "paper_content": paper_content,\n    "fields": fields\n}\n\n# Reply Format: \nReturn the information in the following JSON-format.\n```json\n{        \n    [\n        {\n            "name": "fieldName1",\n            "value": "extractedInfo1",\n            "source_id":[1, 2, 3]\n        },\n        {\n            "name":"fieldName2",\n            "value":"extractedInfo2",\n            "source_id":[4]\n        },\n        ...\n    ]\n}\n```\nYou MUST return ONLY valid JSON, Do NOT include any explanations, comments, or extra text.\n'}], [{'role': 'user', 'content': 'You are now the following python function: ```\ndef extract_fields_from_input_study(inputs: Dict[str, Any]) -> str:\n    """\n    This function is tasked with analyzing clinical trial study reports or papers to extract specific information as structured data and provide citations for the extracted information.\n    The user will provide a list of fields they are interested in, along with a natural language description for each field to guide you on what content to look for and from which parts of the report to extract it.\n\n    IMPORTANT:\n    For each field described by the user, you need to:\n    1. Identify and extract the relevant information from the report, based on the provided description.\n       The answer should be under 200 characters. Summarize the information without losing clarity. Add necessary context.\n    2. Structure the extracted information into a standard format whenever possible (e.g., integer, numerical values, dates, keywords, list of terms). \n        If standardization is not possible, the information should be presented in text format.\n        If the field is not found in the report, the extracted value should be "NP".\n    3. Provide a reference to the document ID from which this information was extracted.\n        This citation id should be restricted to be integers only.\n        You should NOT cite more than three sources for a single field.\n        If the field is "NP", sources should be an empty list.\n        You should try your best to provide the most relevant and specific citation for each field.\n        If two or more sources are equally relevant, you can just cite one of them.\n\n    The function returns a string representing a dictionary with each key representing a field and its extracted value.\n\n# User provided inputs\npaper_content = """(\'<source id="0"><content>combined therapy was validated via a tail vein injection method for the metastasis and orthotopic colon cancer models.</content></source>\\n\\n<source id="1"><content>Our findings illuminate the molecular mechanisms underlying EpCAM signaling promotion of colon cancer metastasis, further suggesting that the combination of EpAb2-6 and crizotinib may be an effective strategy for treating cancer patients with high EpCAM</content></source>\\n\\n<source id="2"><content>Western blotting was taken to determine the expression of proteins in colorectal cancer (CRC) cell lines. The functions of EpEX in CRC were investigated by proliferation, migration, and invasion analysis. The combined therapy was validated via a tail vein</content></source>\\n\\n<source id="3"><content>we show that the combined treatment of an anti-EpCAM neutralizing antibody (EpAb2-6) and an HGFR inhibitor (crizotinib) significantly inhibits tumor progression and prolongs survival in metastatic and orthotopic animal models of colon cancer.</content></source>\', [\'combined therapy was validated via a tail vein injection method for the metastasis and orthotopic colon cancer models.\', \'Our findings illuminate the molecular mechanisms underlying EpCAM signaling promotion of colon cancer metastasis, further suggesting that the combination of EpAb2-6 and crizotinib may be an effective strategy for treating cancer patients with high EpCAM\', \'Western blotting was taken to determine the expression of proteins in colorectal cancer (CRC) cell lines. The functions of EpEX in CRC were investigated by proliferation, migration, and invasion analysis. The combined therapy was validated via a tail vein\', \'we show that the combined treatment of an anti-EpCAM neutralizing antibody (EpAb2-6) and an HGFR inhibitor (crizotinib) significantly inhibits tumor progression and prolongs survival in metastatic and orthotopic animal models of colon cancer.\'])"""\nfields = """<field id=1>"Crizotinib effectiveness, string, The outcome of treating Colorectal cancer with Crizotinib"</field>"""\n\ninputs = {\n    "paper_content": paper_content,\n    "fields": fields\n}\n\n# Reply Format: \nReturn the information in the following JSON-format.\n```json\n{        \n    [\n        {\n            "name": "fieldName1",\n            "value": "extractedInfo1",\n            "source_id":[1, 2, 3]\n        },\n        {\n            "name":"fieldName2",\n            "value":"extractedInfo2",\n            "source_id":[4]\n        },\n        ...\n    ]\n}\n```\nYou MUST return ONLY valid JSON, Do NOT include any explanations, comments, or extra text.\n'}], [{'role': 'user', 'content': 'You are now the following python function: ```\ndef extract_fields_from_input_study(inputs: Dict[str, Any]) -> str:\n    """\n    This function is tasked with analyzing clinical trial study reports or papers to extract specific information as structured data and provide citations for the extracted information.\n    The user will provide a list of fields they are interested in, along with a natural language description for each field to guide you on what content to look for and from which parts of the report to extract it.\n\n    IMPORTANT:\n    For each field described by the user, you need to:\n    1. Identify and extract the relevant information from the report, based on the provided description.\n       The answer should be under 200 characters. Summarize the information without losing clarity. Add necessary context.\n    2. Structure the extracted information into a standard format whenever possible (e.g., integer, numerical values, dates, keywords, list of terms). \n        If standardization is not possible, the information should be presented in text format.\n        If the field is not found in the report, the extracted value should be "NP".\n    3. Provide a reference to the document ID from which this information was extracted.\n        This citation id should be restricted to be integers only.\n        You should NOT cite more than three sources for a single field.\n        If the field is "NP", sources should be an empty list.\n        You should try your best to provide the most relevant and specific citation for each field.\n        If two or more sources are equally relevant, you can just cite one of them.\n\n    The function returns a string representing a dictionary with each key representing a field and its extracted value.\n\n# User provided inputs\npaper_content = """(\'<source id="0"><content>Albumin-Based Cyanine Crizotinib Conjugate Nanoparticles for NIR-II Imaging-Guided Synergistic Chemophototherapy.: Colorectal cancer (CRC) is presently the third deadliest cancer in the world. This malignant cancer usually precedes the progression of</content></source>\\n\\n<source id="1"><content>effects on tumors. In conclusion, this innovative imaging-mediated multifunctional combination therapy strategy with good c-Met targeting ability may provide a new approach for colorectal cancer treatment.</content></source>\\n\\n<source id="2"><content>advanced stages of CRC and is considered to be a potent tumor biomarker. Herein, based on the well-targeted inhibitory effect of Crizotinib on c-Met positive tumor cells, the dye IR808 was covalently combined with the drug molecule Crizotinib, resulting</content></source>\\n\\n<source id="3"><content>with the drug molecule Crizotinib, resulting in the synthesis of a NIR fluorescent probe Crizotinib-IR808 targeting c-Met positive tumor cells. Then, water-insoluble Crizotinib-IR808 was fabricated by using bovine serum albumin (BSA) nanoparticles (NPs)</content></source>\', [\'Albumin-Based Cyanine Crizotinib Conjugate Nanoparticles for NIR-II Imaging-Guided Synergistic Chemophototherapy.: Colorectal cancer (CRC) is presently the third deadliest cancer in the world. This malignant cancer usually precedes the progression of\', \'effects on tumors. In conclusion, this innovative imaging-mediated multifunctional combination therapy strategy with good c-Met targeting ability may provide a new approach for colorectal cancer treatment.\', \'advanced stages of CRC and is considered to be a potent tumor biomarker. Herein, based on the well-targeted inhibitory effect of Crizotinib on c-Met positive tumor cells, the dye IR808 was covalently combined with the drug molecule Crizotinib, resulting\', \'with the drug molecule Crizotinib, resulting in the synthesis of a NIR fluorescent probe Crizotinib-IR808 targeting c-Met positive tumor cells. Then, water-insoluble Crizotinib-IR808 was fabricated by using bovine serum albumin (BSA) nanoparticles (NPs)\'])"""\nfields = """<field id=1>"Crizotinib effectiveness, string, The outcome of treating Colorectal cancer with Crizotinib"</field>"""\n\ninputs = {\n    "paper_content": paper_content,\n    "fields": fields\n}\n\n# Reply Format: \nReturn the information in the following JSON-format.\n```json\n{        \n    [\n        {\n            "name": "fieldName1",\n            "value": "extractedInfo1",\n            "source_id":[1, 2, 3]\n        },\n        {\n            "name":"fieldName2",\n            "value":"extractedInfo2",\n            "source_id":[4]\n        },\n        ...\n    ]\n}\n```\nYou MUST return ONLY valid JSON, Do NOT include any explanations, comments, or extra text.\n'}], [{'role': 'user', 'content': 'You are now the following python function: ```\ndef extract_fields_from_input_study(inputs: Dict[str, Any]) -> str:\n    """\n    This function is tasked with analyzing clinical trial study reports or papers to extract specific information as structured data and provide citations for the extracted information.\n    The user will provide a list of fields they are interested in, along with a natural language description for each field to guide you on what content to look for and from which parts of the report to extract it.\n\n    IMPORTANT:\n    For each field described by the user, you need to:\n    1. Identify and extract the relevant information from the report, based on the provided description.\n       The answer should be under 200 characters. Summarize the information without losing clarity. Add necessary context.\n    2. Structure the extracted information into a standard format whenever possible (e.g., integer, numerical values, dates, keywords, list of terms). \n        If standardization is not possible, the information should be presented in text format.\n        If the field is not found in the report, the extracted value should be "NP".\n    3. Provide a reference to the document ID from which this information was extracted.\n        This citation id should be restricted to be integers only.\n        You should NOT cite more than three sources for a single field.\n        If the field is "NP", sources should be an empty list.\n        You should try your best to provide the most relevant and specific citation for each field.\n        If two or more sources are equally relevant, you can just cite one of them.\n\n    The function returns a string representing a dictionary with each key representing a field and its extracted value.\n\n# User provided inputs\npaper_content = """(\'<source id="0"><content>and acquired cetuximab resistance in colorectal cancer (CRC). Conversely, HGF overexpression was necessary and sufficient to induce cetuximab resistance and loss of polarity. Moreover, HGF-induced cetuximab resistance could be overcome by the downstream</content></source>\\n\\n<source id="1"><content>Inhibition of autocrine HGF maturation overcomes cetuximab resistance in colorectal cancer.: Although amplifications and mutations in receptor tyrosine kinases (RTKs) act as bona fide oncogenes, in most cancers, RTKs maintain moderate expression and remain</content></source>\\n\\n<source id="2"><content>the RTKs MET and RON, HGF and HGFL, respectively, are synthesized as inactive precursors that are activated by cellular proteases. Our newly generated HGF/HGFL protease inhibitors could overcome both de novo and acquired cetuximab resistance in colorectal</content></source>\\n\\n<source id="3"><content>resistance could be overcome by the downstream MET inhibitor, crizotinib, and upstream protease inhibitors. Additionally, HAI-1, an endogenous inhibitor of HGF proteases, (i) was downregulated in CRC, (ii) exhibited increased genomic methylation that</content></source>\', [\'and acquired cetuximab resistance in colorectal cancer (CRC). Conversely, HGF overexpression was necessary and sufficient to induce cetuximab resistance and loss of polarity. Moreover, HGF-induced cetuximab resistance could be overcome by the downstream\', \'Inhibition of autocrine HGF maturation overcomes cetuximab resistance in colorectal cancer.: Although amplifications and mutations in receptor tyrosine kinases (RTKs) act as bona fide oncogenes, in most cancers, RTKs maintain moderate expression and remain\', \'the RTKs MET and RON, HGF and HGFL, respectively, are synthesized as inactive precursors that are activated by cellular proteases. Our newly generated HGF/HGFL protease inhibitors could overcome both de novo and acquired cetuximab resistance in colorectal\', \'resistance could be overcome by the downstream MET inhibitor, crizotinib, and upstream protease inhibitors. Additionally, HAI-1, an endogenous inhibitor of HGF proteases, (i) was downregulated in CRC, (ii) exhibited increased genomic methylation that\'])"""\nfields = """<field id=1>"Crizotinib effectiveness, string, The outcome of treating Colorectal cancer with Crizotinib"</field>"""\n\ninputs = {\n    "paper_content": paper_content,\n    "fields": fields\n}\n\n# Reply Format: \nReturn the information in the following JSON-format.\n```json\n{        \n    [\n        {\n            "name": "fieldName1",\n            "value": "extractedInfo1",\n            "source_id":[1, 2, 3]\n        },\n        {\n            "name":"fieldName2",\n            "value":"extractedInfo2",\n            "source_id":[4]\n        },\n        ...\n    ]\n}\n```\nYou MUST return ONLY valid JSON, Do NOT include any explanations, comments, or extra text.\n'}], [{'role': 'user', 'content': 'You are now the following python function: ```\ndef extract_fields_from_input_study(inputs: Dict[str, Any]) -> str:\n    """\n    This function is tasked with analyzing clinical trial study reports or papers to extract specific information as structured data and provide citations for the extracted information.\n    The user will provide a list of fields they are interested in, along with a natural language description for each field to guide you on what content to look for and from which parts of the report to extract it.\n\n    IMPORTANT:\n    For each field described by the user, you need to:\n    1. Identify and extract the relevant information from the report, based on the provided description.\n       The answer should be under 200 characters. Summarize the information without losing clarity. Add necessary context.\n    2. Structure the extracted information into a standard format whenever possible (e.g., integer, numerical values, dates, keywords, list of terms). \n        If standardization is not possible, the information should be presented in text format.\n        If the field is not found in the report, the extracted value should be "NP".\n    3. Provide a reference to the document ID from which this information was extracted.\n        This citation id should be restricted to be integers only.\n        You should NOT cite more than three sources for a single field.\n        If the field is "NP", sources should be an empty list.\n        You should try your best to provide the most relevant and specific citation for each field.\n        If two or more sources are equally relevant, you can just cite one of them.\n\n    The function returns a string representing a dictionary with each key representing a field and its extracted value.\n\n# User provided inputs\npaper_content = """(\'<source id="0"><content>A 49-year-old Chinese male was diagnosed with ascending colon adenocarcinoma (cT3N+?M1) with liver metastases. The patient performed next-generation sequencing (NGS) using tissue and circulating tumor DNA (ctDNA), and the results showed a</content></source>\\n\\n<source id="1"><content>This study reported a co-existence of a</content></source>\\n\\n<source id="2"><content>Partial response to crizotinib + regorafenib + PD-1 inhibitor in a metastatic: Colorectal cancer (CRC) with the Raf murine sarcoma viral oncogene homolog B (</content></source>\', [\'A 49-year-old Chinese male was diagnosed with ascending colon adenocarcinoma (cT3N+?M1) with liver metastases. The patient performed next-generation sequencing (NGS) using tissue and circulating tumor DNA (ctDNA), and the results showed a\', \'This study reported a co-existence of a\', \'Partial response to crizotinib + regorafenib + PD-1 inhibitor in a metastatic: Colorectal cancer (CRC) with the Raf murine sarcoma viral oncogene homolog B (\'])"""\nfields = """<field id=1>"Crizotinib effectiveness, string, The outcome of treating Colorectal cancer with Crizotinib"</field>"""\n\ninputs = {\n    "paper_content": paper_content,\n    "fields": fields\n}\n\n# Reply Format: \nReturn the information in the following JSON-format.\n```json\n{        \n    [\n        {\n            "name": "fieldName1",\n            "value": "extractedInfo1",\n            "source_id":[1, 2, 3]\n        },\n        {\n            "name":"fieldName2",\n            "value":"extractedInfo2",\n            "source_id":[4]\n        },\n        ...\n    ]\n}\n```\nYou MUST return ONLY valid JSON, Do NOT include any explanations, comments, or extra text.\n'}]]
print(h[0][0]['content'])

You are now the following python function: ```
def extract_fields_from_input_study(inputs: Dict[str, Any]) -> str:
    """
    This function is tasked with analyzing clinical trial study reports or papers to extract specific information as structured data and provide citations for the extracted information.
    The user will provide a list of fields they are interested in, along with a natural language description for each field to guide you on what content to look for and from which parts of the report to extract it.

    IMPORTANT:
    For each field described by the user, you need to:
    1. Identify and extract the relevant information from the report, based on the provided description.
       The answer should be under 200 characters. Summarize the information without losing clarity. Add necessary context.
    2. Structure the extracted information into a standard format whenever possible (e.g., integer, numerical values, dates, keywords, list of terms).
        If standardization is not possible, the information should be presented in text format.
        If the field is not found in the report, the extracted value should be "NP".
    3. Provide a reference to the document ID from which this information was extracted.
        This citation id should be restricted to be integers only.
        You should NOT cite more than three sources for a single field.
        If the field is "NP", sources should be an empty list.
        You should try your best to provide the most relevant and specific citation for each field.
        If two or more sources are equally relevant, you can just cite one of them.

    The function returns a string representing a dictionary with each key representing a field and its extracted value.

# User provided inputs
paper_content = """('<source id="0"><content>suppressor in various cancer types. Owing to its high frequency of inactivating mutations, ARID1A has emerged as a promising target for the development of anticancer drugs. In this study, we report that ARID1A-deficient colorectal cancer (CRC) cells</content></source>\n\n<source id="1"><content>ARID1A-deficient colorectal cancer (CRC) cells induce synthetic lethality when treated with inhibitors of c-MET receptor tyrosine kinase. c-MET specific inhibitor PHA-665752 as well as two other FDA-approved drugs, crizotinib and cabozantinib, selectively</content></source>\n\n<source id="2"><content>ultimately inducing ferroptosis. This study reveals a novel synthetic lethal relationship between ARID1A and c-MET signaling in promoting ferroptosis and proposes c-MET inhibitors as a potential therapeutic strategy for ARID1A-deficient CRC.</content></source>\n\n<source id="3"><content>drugs, crizotinib and cabozantinib, selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models. Mechanistically, we identified a tripartite functional association among ARID1A, c-MET, and NRF2, where ARID1A and</content></source>', ['suppressor in various cancer types. Owing to its high frequency of inactivating mutations, ARID1A has emerged as a promising target for the development of anticancer drugs. In this study, we report that ARID1A-deficient colorectal cancer (CRC) cells', 'ARID1A-deficient colorectal cancer (CRC) cells induce synthetic lethality when treated with inhibitors of c-MET receptor tyrosine kinase. c-MET specific inhibitor PHA-665752 as well as two other FDA-approved drugs, crizotinib and cabozantinib, selectively', 'ultimately inducing ferroptosis. This study reveals a novel synthetic lethal relationship between ARID1A and c-MET signaling in promoting ferroptosis and proposes c-MET inhibitors as a potential therapeutic strategy for ARID1A-deficient CRC.', 'drugs, crizotinib and cabozantinib, selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models. Mechanistically, we identified a tripartite functional association among ARID1A, c-MET, and NRF2, where ARID1A and'])"""
fields = """<field id=1>"Crizotinib effectiveness, string, The outcome of treating Colorectal cancer with Crizotinib"</field>"""

inputs = {
    "paper_content": paper_content,
    "fields": fields
}

# Reply Format:
Return the information in the following JSON-format.
```json
{
    [
        {
            "name": "fieldName1",
            "value": "extractedInfo1",
            "source_id":[1, 2, 3]
        },
        {
            "name":"fieldName2",
            "value":"extractedInfo2",
            "source_id":[4]
        },
        ...
    ]
}
```
You MUST return ONLY valid JSON, Do NOT include any explanations, comments, or extra text.

In [19]:
from pydantic import BaseModel, validator, Field, conlist  # This is the new version
from typing import Dict, Literal
class FieldResult(BaseModel):
    name: str = Field(description='Field name that accurately represents the content of the field based on its description.',
                     max_length=25)
    value: str = Field(description='Extracted information from the text based on the field description.',
                      max_length=200)
    source_id: conlist(int,min_length=1, max_length=3) = Field(description='Cited document IDs.')
class Results(BaseModel):
    fieldresult: list[FieldResult]#FieldResult

In [14]:
retrieved_docs = vector_store.similarity_search(f'The effectiveness of treating {fin_condition} with {treatements_eng[0]}', 
        k=2,filter={"source": '37418240'})
[i.page_content for i in retrieved_docs]

['Crizotinib-IR808@BSA NPs exhibited synergistic chemophototherapy effects on tumors. In conclusion, this innovative imaging-mediated multifunctional combination therapy strategy with good c-Met targeting ability may provide a new approach for colorectal cancer treatment.',
 'in advanced stages of CRC and is considered to be a potent tumor biomarker. Herein, based on the well-targeted inhibitory effect of Crizotinib on c-Met positive tumor cells, the dye IR808 was covalently combined with the drug molecule Crizotinib, resulting in the synthesis of a NIR fluorescent probe Crizotinib-IR808 targeting c-Met positive tumor cells. Then, water-insoluble Crizotinib-IR808 was fabricated by using bovine serum albumin (BSA)']

In [21]:
from trialmind.prompts.extraction import STUDY_FIELDS_EXTRACTION_3

In [23]:
docs_content = '\n\n'.join([i.page_content for i in retrieved_docs])
fields=[f'Crizotinib Results, string, the effectiveness of treating {fin_condition} with {treatements_eng[0]}'
           ]
user_m = f'''
            paper_content = \"\"\"{docs_content}\"\"\"
            fields = \"\"\"{fields}\"\"\"
            '''

prompt = f'''
You are a helpful assistant. Use the following context in your response:
'''

response = client.chat.completions.parse(
        model='kamekichi128/qwen3-4b-instruct-2507',
        messages=[{'role':'system', 
                   'content':STUDY_FIELDS_EXTRACTION_3},
                  {'role':'user','content':user_m}],
        temperature=0,
        response_format = Results
    )
print(response.choices[0].message.parsed)

fieldresult=[FieldResult(name='Crizotinib Effectiveness', value='Crizotinib-IR808 NPs showed synergistic chemophototherapy effects and good c-Met targeting ability, indicating potential for colorectal cancer treatment.', source_id=[1])]

## stuff

In [73]:
hh = Results(fieldresult=[FieldResult(name='Crizotinib Results', value='Crizotinib selectively inhibited the growth of ARD', source_id=[1]), FieldResult(name='Participants', value='NP', source_id=[1])])

In [83]:
i._c = ''

In [106]:
retrieved_docs = vector_store.similarity_search('Crizotinib results', k=2)
docs_content = "\n\n".join(doc.page_content for doc in retrieved_docs)
docs_content

'PD-0325901/crizotinib can be given together at pharmacologically-active doses. The MTD for PD-0325901/crizotinib was 8\u2009mg B.D (days 1-21) and 200\u2009mg B.D continuously in a 28-days cycle. The combination was further explored with an alternate MEK1/2 inhibitor in RASMT CRC patients.\n2014-000463-40.\n\nTwenty-five patients were recruited in 4 cohorts up to doses of crizotinib 200\u2009mg B.D continuously with PD-0325901 8\u2009mg B.D, days 1-21 every 28 days. One in six patients exhibited a dose-limiting toxicity at this dose level. Drug-related adverse events were in keeping with single-agent toxicity profiles. The best clinical response was stable disease in seven patients (29%).'

In [141]:
Results

__main__.Results

In [142]:
docs_content = 'drugs. In this study, we report that ARID1A-deficient colorectal cancer (CRC) cells induce synthetic lethality when treated with inhibitors of c-MET receptor tyrosine kinase. c-MET specific inhibitor PHA-665752 as well as two other FDA-approved drugs, crizotinib and cabozantinib, selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models. Mechanistically, we identified a tripartite functional'

print(docs_content)


prompt = f'''
You are a helpful assistant. Use the following context in your response:
'''

response = client.chat.completions.parse(
        model='kamekichi128/qwen3-4b-instruct-2507',
        messages=[{'role':'system', 'content':prompt+docs_content},
                  {'role':'user','content':'Crizotinib results'}],
        temperature=0,
        response_format = Results
    )
print(response.choices[0].message.parsed)

drugs. In this study, we report that ARID1A-deficient colorectal cancer (CRC) cells induce synthetic lethality when treated with inhibitors of c-MET receptor tyrosine kinase. c-MET specific inhibitor PHA-665752 as well as two other FDA-approved drugs, crizotinib and cabozantinib, selectively inhibited the growth of ARID1A-deficient CRC cells in vitro and in xenograft tumor models. Mechanistically, we identified a tripartite functional
fieldresult=[FieldResult(name='crizotinib', value='Crizotinib results in the selective inhibition of ', source_id=[-1, -1, -1]), FieldResult(name='crizotinib', value='Crizotinib, a FDA-approved c-MET inhibitor, was有效的', source_id=[-1, -1, -1]), FieldResult(name='crizotinib', value='Crizotinib effectively suppresses the growth of AR', source_id=[-1, -1, -1])]

In [143]:
response.choices[0].message.parsed

Results(fieldresult=[FieldResult(name='crizotinib', value='Crizotinib results in the selective inhibition of ', source_id=[-1, -1, -1]), FieldResult(name='crizotinib', value='Crizotinib, a FDA-approved c-MET inhibitor, was有效的', source_id=[-1, -1, -1]), FieldResult(name='crizotinib', value='Crizotinib effectively suppresses the growth of AR', source_id=[-1, -1, -1])])

In [16]:
%%time
response = client.chat.completions.create(
        model='kamekichi128/qwen3-4b-instruct-2507',
        messages=[{'role':'user','content':'hey'}],
        temperature=0,
    )
print(response.choices[0].message.content)

Hi there! 😊 How can I help you today?
CPU times: total: 0 ns
Wall time: 3.04 s

In [4]:
data = ['''


Introduction: In the phase 3 study entitled ALK in Lung cancer Trial of brigAtinib in 1st Line (ALTA-1L), which is a study of brigatinib in ALK inhibitor-naive advanced ALK-positive NSCLC, brigatinib exhibited superior progression-free survival (PFS) versus crizotinib in the two planned interim analyses. Here, we report the final efficacy, safety, and exploratory results.

Methods: Patients were randomized to brigatinib 180 mg once daily (7-d lead-in at 90 mg once daily) or crizotinib 250 mg twice daily. The primary end point was a blinded independent review committee-assessed PFS. Genetic alterations in plasma cell-free DNA were assessed in relation to clinical efficacy.

Results: A total of 275 patients were enrolled (brigatinib, n = 137; crizotinib, n = 138). At study end, (brigatinib median follow-up = 40.4 mo), the 3-year PFS by blinded independent review committee was 43% (brigatinib) versus 19% (crizotinib; median = 24.0 versus 11.1 mo, hazard ratio [HR] = 0.48, 95% confidence interval [CI]: 0.35-0.66). The median overall survival was not reached in either group (HR = 0.81, 95% CI: 0.53-1.22). Posthoc analyses suggested an overall survival benefit for brigatinib in patients with baseline brain metastases (HR = 0.43, 95% CI: 0.21-0.89). Detectable baseline EML4-ALK fusion variant 3 and TP53 mutation in plasma were associated with poor PFS. Brigatinib exhibited superior efficacy compared with crizotinib regardless of EML4-ALK variant and TP53 mutation. Emerging secondary ALK mutations were rare in patients progressing on brigatinib. No new safety signals were observed.

Conclusions: In the ALTA-1L final analysis, with longer follow-up, brigatinib continued to exhibit superior efficacy and tolerability versus crizotinib in patients with or without poor prognostic biomarkers. The suggested survival benefit with brigatinib in patients with brain metastases warrants future study.

''']

In [5]:
#from langchain.docstore.document import Document

doc =  Document(page_content=data[0], metadata={"source": "local"})
doc

Document(metadata={'source': 'local'}, page_content='\n\n\nIntroduction: In the phase 3 study entitled ALK in Lung cancer Trial of brigAtinib in 1st Line (ALTA-1L), which is a study of brigatinib in ALK inhibitor-naive advanced ALK-positive NSCLC, brigatinib exhibited superior progression-free survival (PFS) versus crizotinib in the two planned interim analyses. Here, we report the final efficacy, safety, and exploratory results.\n\nMethods: Patients were randomized to brigatinib 180 mg once daily (7-d lead-in at 90 mg once daily) or crizotinib 250 mg twice daily. The primary end point was a blinded independent review committee-assessed PFS. Genetic alterations in plasma cell-free DNA were assessed in relation to clinical efficacy.\n\nResults: A total of 275 patients were enrolled (brigatinib, n = 137; crizotinib, n = 138). At study end, (brigatinib median follow-up = 40.4 mo), the 3-year PFS by blinded independent review committee was 43% (brigatinib) versus 19% (crizotinib; median = 24.0 versus 11.1 mo, hazard ratio [HR] = 0.48, 95% confidence interval [CI]: 0.35-0.66). The median overall survival was not reached in either group (HR = 0.81, 95% CI: 0.53-1.22). Posthoc analyses suggested an overall survival benefit for brigatinib in patients with baseline brain metastases (HR = 0.43, 95% CI: 0.21-0.89). Detectable baseline EML4-ALK fusion variant 3 and TP53 mutation in plasma were associated with poor PFS. Brigatinib exhibited superior efficacy compared with crizotinib regardless of EML4-ALK variant and TP53 mutation. Emerging secondary ALK mutations were rare in patients progressing on brigatinib. No new safety signals were observed.\n\nConclusions: In the ALTA-1L final analysis, with longer follow-up, brigatinib continued to exhibit superior efficacy and tolerability versus crizotinib in patients with or without poor prognostic biomarkers. The suggested survival benefit with brigatinib in patients with brain metastases warrants future study.\n\n')

6

OllamaEmbeddings(model='all-minilm', validate_model_on_init=False, base_url=None, client_kwargs={}, async_client_kwargs={}, sync_client_kwargs={}, mirostat=None, mirostat_eta=None, mirostat_tau=None, num_ctx=None, num_gpu=None, keep_alive=None, num_thread=None, repeat_last_n=None, repeat_penalty=None, temperature=None, stop=None, tfs_z=None, top_k=None, top_p=None)

In [9]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter=RecursiveCharacterTextSplitter(chunk_size=400, 
                                             chunk_overlap=100)
all_splits = text_splitter.split_documents([doc])
len(all_splits)

embeddings = OllamaEmbeddings(model="all-minilm")

vector_store = Chroma(
    collection_name="example_collection",
    embedding_function=embeddings,
    persist_directory="./chroma_langchain_db",  # Where to save data locally, remove if not necessary
)

document_ids = vector_store.add_documents(documents=all_splits)

retrieved_docs = vector_store.similarity_search('Crizotinib results', k=2)
docs_content = "\n\n".join(doc.page_content for doc in retrieved_docs)
print(docs_content)


prompt = f'''
You are a helpful assistant. Use the following context in your response:
'''

response = client.chat.completions.create(
        model='kamekichi128/qwen3-4b-instruct-2507',
        messages=[{'role':'system', 'content':prompt+docs_content},
                  {'role':'user','content':'Crizotinib results'}],
        temperature=0,
    )
print(response.choices[0].message.content)

['e2281722-8819-4760-8ddc-a030fef6426e',
 'f72a5bd2-2df8-4f93-8054-35ccfbda5e8b',
 'fa0fe031-bf16-46eb-93b7-b55b9e203665',
 '651ffb0f-de2d-4e66-ae78-5551a5df75ea',
 'b688449b-2d03-4574-ada3-17fb1b9fd208',
 'dc0bc29f-f933-402a-8d47-451cfcc00b3e']

Results: A total of 275 patients were enrolled (brigatinib, n = 137; crizotinib, n = 138). At study end, (brigatinib median follow-up = 40.4 mo), the 3-year PFS by blinded independent review committee was 43% (brigatinib) versus 19% (crizotinib; median = 24.0 versus 11.1 mo, hazard ratio [HR] = 0.48, 95% confidence interval [CI]: 0.35-0.66). The median overall survival was not reached in either

Results: A total of 275 patients were enrolled (brigatinib, n = 137; crizotinib, n = 138). At study end, (brigatinib median follow-up = 40.4 mo), the 3-year PFS by blinded independent review committee was 43% (brigatinib) versus 19% (crizotinib; median = 24.0 versus 11.1 mo, hazard ratio [HR] = 0.48, 95% confidence interval [CI]: 0.35-0.66). The median overall survival was not reached in either

In [13]:
prompt = f'''
You are a helpful assistant. Use the following context in your response:
'''

response = client.chat.completions.create(
        model='kamekichi128/qwen3-4b-instruct-2507',
        messages=[{'role':'system', 'content':prompt+docs_content},
                  {'role':'user','content':'Crizotinib results'}],
        temperature=0,
    )
print(response.choices[0].message.content)

The crizotinib results from the study show the following:

- **Progression-Free Survival (PFS):**
  At study end, the 3-year PFS by blinded independent review committee was **19%** for patients treated with crizotinib.
  The median PFS duration was **11.1 months**.

- **Hazard Ratio (HR):**
  Compared to brigatinib, crizotinib had a hazard ratio of **0.48 (95% CI: 0.35–0.66)** for progression or death, indicating that crizotinib was less effective in delaying disease progression than brigatinib.

- **Overall Survival (OS):**
  The median overall survival was **not reached** in either treatment group, suggesting that the study was not able to provide a definitive OS benefit for either drug.

In summary, crizotinib demonstrated a lower progression-free survival rate and shorter median PFS compared to brigatinib, with a statistically significant improvement in PFS observed with brigatinib. However, overall survival was not reached in either group.

In [ ]:
ollama.embeddings(model='all-minilm', 
                  prompt='The sky is blue because of Rayleigh scattering')

Hello! How can I assist you today? 😊

In [30]:
PROMPT_RES_EXTRACTION  = '''
You are a clinical specialist analyzing clinical trial study reports. 
Your task is to to extract specific information as structured data.

# Reply Format: 
Return the information in the following JSON-format.
```json
{{        
    [
        {{
            "population": n,
            "time_frame": "time_frame",
            "outcomes":
                [
                    {{
                        "category_name": "category1",
                        "outcome": k1
                    }},
                    {{
                        "category_name": "category2",
                        "outcome": k2
                    }},
                    ...
                ]
         }},
        ...
    ]
}}
```
You MUST return ONLY valid JSON, Do NOT include any explanations, comments, or extra text.
"""
'''

In [29]:
to_work = [{'type': 'PRIMARY',
  'title': 'Clinical Response to Binimetinib Combined With PF-02341066',
  'description': 'To investigate response to treatment with RPII dose of Binimetinib with Crizotinib (PF-02341066), in patients with a) RASMT CRC or b) RASWT/cMET mut amplified CRC or c) RASWT/c-MET over-expressed CRC, as defined by stable, partially or completely responding disease, per Response Evaluation Criteria In Solid Tumors Criteria (RECIST v1.1) for target lesions and assessed by CT: Complete Response (CR), Disappearance of all target lesions; Partial Response (PR), \\>=30% decrease in the sum of the longest diameter of target lesions; Stable Disease (SD), Neither sufficient shrinkage to qualify for PR nor sufficient increase (\\>=20%) to qualify for Progressive Disease; Overall Response (OR) = CR + PR + SD',
  'populationDescription': 'Evaluable patients for the primary outcome are those patients who complete a response assessment after cycle 1 of treatment, or who progress early on treatment. 30 of the 36 recruited patients had a response assessment after cycle 1 or progressed early on treatment, and hence these 30 patients are evaluable for the primary analysis.',
  'reportingStatus': 'POSTED',
  'paramType': 'COUNT_OF_PARTICIPANTS',
  'unitOfMeasure': 'Participants',
  'timeFrame': 'Dose Expansion phase: change from baseline and up to 12 months.',
  'groups': [{'id': 'OG000',
    'title': 'Dose Expansion Phase',
    'description': 'Binimetinib 30mg BD interval dose administration Days 1-21 every 28 days PF-02341066 (Crizotinib) 250mg OD Days 1-28 continuously Dosage determined following the recommended Phase II dose identification in the dose escalation phase.\n\nPF-02341066: PF-02341066 (Crizotinib) 250mg OD or 200mg BD or 250mg BD Days 1-28 continuously\n\nBinimetinib: Binimetinib 30mg or 45 mg BD either continuously or Days 1-21 every 28 days'}],
  'denoms': [{'units': 'Participants',
    'counts': [{'groupId': 'OG000', 'value': '30'}]}],
  'classes': [{'categories': [{'title': 'Stable Disease',
      'measurements': [{'groupId': 'OG000', 'value': '7'}]},
     {'title': 'Progressive Disease',
      'measurements': [{'groupId': 'OG000', 'value': '22'}]},
     {'title': 'Early death from malignant disease',
      'measurements': [{'groupId': 'OG000', 'value': '1'}]}]}]}]
to_work

[{'type': 'PRIMARY',
  'title': 'Clinical Response to Binimetinib Combined With PF-02341066',
  'description': 'To investigate response to treatment with RPII dose of Binimetinib with Crizotinib (PF-02341066), in patients with a) RASMT CRC or b) RASWT/cMET mut amplified CRC or c) RASWT/c-MET over-expressed CRC, as defined by stable, partially or completely responding disease, per Response Evaluation Criteria In Solid Tumors Criteria (RECIST v1.1) for target lesions and assessed by CT: Complete Response (CR), Disappearance of all target lesions; Partial Response (PR), \\>=30% decrease in the sum of the longest diameter of target lesions; Stable Disease (SD), Neither sufficient shrinkage to qualify for PR nor sufficient increase (\\>=20%) to qualify for Progressive Disease; Overall Response (OR) = CR + PR + SD',
  'populationDescription': 'Evaluable patients for the primary outcome are those patients who complete a response assessment after cycle 1 of treatment, or who progress early on treatment. 30 of the 36 recruited patients had a response assessment after cycle 1 or progressed early on treatment, and hence these 30 patients are evaluable for the primary analysis.',
  'reportingStatus': 'POSTED',
  'paramType': 'COUNT_OF_PARTICIPANTS',
  'unitOfMeasure': 'Participants',
  'timeFrame': 'Dose Expansion phase: change from baseline and up to 12 months.',
  'groups': [{'id': 'OG000',
    'title': 'Dose Expansion Phase',
    'description': 'Binimetinib 30mg BD interval dose administration Days 1-21 every 28 days PF-02341066 (Crizotinib) 250mg OD Days 1-28 continuously Dosage determined following the recommended Phase II dose identification in the dose escalation phase.\n\nPF-02341066: PF-02341066 (Crizotinib) 250mg OD or 200mg BD or 250mg BD Days 1-28 continuously\n\nBinimetinib: Binimetinib 30mg or 45 mg BD either continuously or Days 1-21 every 28 days'}],
  'denoms': [{'units': 'Participants',
    'counts': [{'groupId': 'OG000', 'value': '30'}]}],
  'classes': [{'categories': [{'title': 'Stable Disease',
      'measurements': [{'groupId': 'OG000', 'value': '7'}]},
     {'title': 'Progressive Disease',
      'measurements': [{'groupId': 'OG000', 'value': '22'}]},
     {'title': 'Early death from malignant disease',
      'measurements': [{'groupId': 'OG000', 'value': '1'}]}]}]}]

In [34]:
from enum import Enum
from pydantic import BaseModel, Field

class Outcome(BaseModel):
    category_name: str = Field(description='Short description of a category')
    outcome: int = Field(description='Percent of participants')

class ClinicalResult(BaseModel):
    population: int = Field(description='Total number of participants.')
    time_frame: str = Field(description='Time frame')
    outcomes: list[Outcome]

In [35]:
messages = [{'role':'system', 'content':PROMPT_RES_EXTRACTION+' \no_think'},
                {'role':'user', 'content':f"{to_work[0]}"}]

In [38]:
response = client.chat.completions.create(
                model='qwen3:8b',
                messages=messages,
                temperature=0,
                response_format={
                    "type": "json_object",
                    "json_schema": {
                        "name": "schema",
                        "schema": ClinicalResult.model_json_schema()
                    },
                },
            )
fin = response.choices[0].message.content
answer = fin.strip('<think>\n\n</think>\n\n')
print(answer)

{
    "population": 30,
    "time_frame": "Dose Expansion phase: change from baseline and up to 12 months.",
    "outcomes": [
        {
            "category_name": "Stable Disease",
            "outcome": 7
        },
        {
            "category_name": "Progressive Disease",
            "outcome": 22
        },
        {
            "category_name": "Early death from malignant disease",
            "outcome": 1
        }
    ]
}

In [42]:
response = client.chat.completions.create(
                model='qwen3:8b',
                messages=messages,
                temperature=0,
                response_format={
                    "type": "json_schema",
                    "json_schema": {
                        "name": "schema",
                        "schema": ClinicalResult.model_json_schema()
                    },
                },
            )
fin = response.choices[0].message.content
answer = fin.strip('<think>\n\n</think>\n\n')
print(answer)

{
    "population": 30,
    "time_frame": "Dose Expansion phase: change from baseline and up to 12 months.",
    "outcomes": [
        {
            "category_name": "Stable Disease",
            "outcome": 7
        },
        {
            "category_name": "Progressive Disease",
            "outcome": 22
        },
        {
            "category_name": "Early death from malignant disease",
            "outcome": 1
        }
    ]
}

In [45]:
response = client.chat.completions.create(
                model='qwen3:8b',
                messages=messages,
                temperature=0,
                response_format={
                    "type": "json_schema",
                    "json_schema": {
                        "name": "schema",
                        "schema": ClinicalResult.model_json_schema(),
                        'strict':True,
                    },
                    
                },
            )
fin = response.choices[0].message.content
answer = fin.strip('<think>\n\n</think>\n\n')
print(answer)

{
    "population": 30,
    "time_frame": "Dose Expansion phase: change from baseline and up to 12 months",
    "outcomes": [
        {
            "category_name": "Stable Disease",
            "outcome": 7
        },
        {
            "category_name": "Progressive Disease",
            "outcome": 22
        },
        {
            "category_name": "Early death from malignant disease",
            "outcome": 1
        }
    ]
}

In [51]:
response = client.chat.completions.parse(
    model='qwen3:8b',
    messages=messages,
    response_format=ClinicalResult,
)

fin = response.choices[0].message.content
answer = fin.strip('<think>\n\n</think>\n\n')
print(answer)

{
    "population": 30,
    "time_frame": "Dose Expansion phase: change from baseline and up to 12 months",
    "outcomes": [
        {
            "category_name": "Stable Disease",
            "outcome": 7
        },
        {
            "category_name": "Progressive Disease",
            "outcome": 22
        },
        {
            "category_name": "Early death from malignant disease",
            "outcome": 1
        }
    ]
}

In [56]:
hh = response.choices[0].message.parsed
hh

ClinicalResult(population=30, time_frame='Dose Expansion phase: change from baseline and up to 12 months', outcomes=[Outcome(category_name='Stable Disease', outcome=7), Outcome(category_name='Progressive Disease', outcome=22), Outcome(category_name='Early death from malignant disease', outcome=1)])

In [58]:
client.vector_stores

In [40]:
ClinicalResult.model_validate_json(answer)

ClinicalResult(population=30, time_frame='Dose Expansion phase: change from baseline and up to 12 months.', outcomes=[Outcome(category_name='Stable Disease', outcome=7), Outcome(category_name='Progressive Disease', outcome=22), Outcome(category_name='Early death from malignant disease', outcome=1)])

In [41]:
import ollama

response = ollama.embed(
    model='qwen3-embedding',
    input='The sky is blue because of Rayleigh scattering',
)
print(response.embeddings)

ResponseError: model "qwen3-embedding" not found, try pulling it first (status code: 404)